### ISSUE TITLE
Mark file as reviewed at revision

### ISSUE THREAD

**Issue by calmh** [reviewninja/review.ninja#1000]
Hi! I'm just starting out with ReviewNinja, so I may be missing something, but here's something I'm looking for in my workflow.

A review may be large, as in containing more files and changes than I can review in a single sitting. As it is, there doesn't seem to be a way to mark a file as reviewed. What I would like to do is just click a checkmark beside the [+] or something to indicate that I've looked at this file at this revision; no need to show it again unless it changes. The next time I open the review, it would then collapse those files by default and only show me the remaining files to review.

If a file has been changed in a new commit, or by rebasing, the checkmark would be revoked. _Ideally_ it would me review just the diff since I marked as reviewed, of course. :)

**Comment by dfarr** [comment]
As ReviewNinja is no longer in active development mode (see #1132), I will close this issue.
