### ISSUE TITLE
Slack Integration with other compatible chat servers?

### ISSUE THREAD

**Issue by gabel** [reviewninja/review.ninja#1003]
If the "Slack Integration" only fires a webhook could you make the endpoint URL editable to connect review ninja with chat servers which are slack compatible like http://www.mattermost.org/?

**Comment by dfarr** [comment]
I think the best idea would be to create an integrations strategy, where you can register webhooks and some meta-data (in ReviewNinja) and custom integration handlers could forward these messages to chat services (or any type of service).

We currently take this approach with Slack, but it could be made more generic. This is an example payload:
```
{
  event: 'star',
  token: '*******',
  channel: '#general',
  sender: 'dfarr',
  pull_request: 1,
  url: 'https://github.com/reviewninja/review.ninja/pull/1'
}
```

**Comment by dfarr** [comment]
As ReviewNinja is no longer in active development mode (see #1132), I will close this issue.
