### ISSUE TITLE
Requiring specific reviewers

### ISSUE THREAD

**Issue by brntbeer** [reviewninja/review.ninja#1006]
Would it be possible to configure within a given repository or organization either a team of people who are the reviewers? If this were to be selected on the app itself, I imagine it would be like configuring how many ninja stars were needed. You'd select a team from the organization that owns the repository, and how many from that team need to approve it.

Thoughts?

**Comment by dfarr** [comment]
I like this idea. We have heard it a number of times so I think that adds a lot of weight behind it. Usually we are not inclined to add "restrictions" to code review, so I would strongly encourage this new feature to be "opt-in" only.

**Comment by brntbeer** [comment]
@dfarr definitely opt-in only. it's just unfortunately a part of some people's workflows, but honestly I don't run into it too often.

**Comment by casche** [comment]
Hey @brntbeer, this is under :construction: see #1008

**Comment by rwreynard** [comment]
#1019

**Comment by casche** [comment]
hey @brntbeer, completed with #1008, #1024 and #1030 :beers:

**Comment by brntbeer** [comment]
![](http://i3.kym-cdn.com/photos/images/original/000/615/220/0d9.gif)

Thanks @casche and @dfarr and everyone!
