### ISSUE TITLE
Updating branch with fast-foward merge from base branch should not require new ninja stars

### ISSUE THREAD

**Issue by stephanzlatarev** [reviewninja/review.ninja#1011]
When you collect ninja stars for a pull request someone else can merge a non-related pull request. This deems the branch of your pull request outdated so you cannot have it merged even if that would be a fast-forward merge. When you update it, you get to 0 ninja stars so you have to collect ninja stars anew. In a more dynamic project you may never get to a point when you have the required ninja stars and your branch is up-to-date.

Can you solve this?

I can imagine:
- either hooking a fast-forward merge with the base branch as part of the merge pull request operation; 
- or having reviewninja remember the ninja stars even after a rebase (e.g. the ninja stars may be associated with the hashed digest over the changes so the ninja stars are reset only if at least one line of code has been changed)

**Comment by disordered** [comment]
We run into this constantly, so we had to disable required check for review ninja.

**Comment by sergekukharev** [comment]
Super important for us, this behavior causes a lot of problems, if you merge to mainline all the time. Imagine you have 10 pending PR for reviews, then when single of them is merged - all others are outdated and require another review. Please, fix it or suggest a fix for someone to implement and create PR for you.

**Comment by sergekukharev** [comment]
One of the things that can help in this situation with protected branches. Go to:
https://github.com/<your-repo>/settings/branches/<your-main-branch>

and disable new GitHub feature - "Require branches to be up to date before merging".

This will still reset your ninja stars, but only if you indeed have been rebasing/merging mainline into your branch.

![protected branch develop](https://cloud.githubusercontent.com/assets/5091241/14495559/4af81312-0190-11e6-8d25-4d7fdf0a7987.png)

**Comment by agonzalezjr** [comment]
This would be a very nice feature to have.

**Comment by dfarr** [comment]
As ReviewNinja is no longer in active development mode (see #1132), I will close this issue.
