### ISSUE TITLE
Issue line number not synced between github and ninja

### ISSUE THREAD

**Issue by disordered** [reviewninja/review.ninja#1013]
If a user leaves a comment on line 50 in github, the same comment will appear on line 51 in review ninja. The same goes the opposite way, if you leave a comment on line 50 in review ninja, then in github it will appear on line 49.

**Comment by dfarr** [comment]
Hi @disordered could you please provide a screenshot or a link to this PR, the latter would be extremely useful :)

**Comment by dfarr** [comment]
Okay, it appears the way we index line numbers in a diff is wrong.

How we are currently doing it:
| index | content |
| ------- | ---------- |
| - | @@ -1,5 +1,7 @@ |
| 1 | blah blah |
| 2 | blah blah |
| - | @@ -1,5 +1,7 @@ |
| 3 | blah blah |

How we should be doing it:
| index | content |
| ------- | ---------- |
| 0 | @@ -1,5 +1,7 @@ |
| 1 | blah blah |
| 2 | blah blah |
| 4 | @@ -1,5 +1,7 @@ |
| 5 | blah blah |

**Comment by dfarr** [comment]
Will verify and fix this ASAP.

**Comment by dfarr** [comment]
https://github.com/reviewninja/parse-diff/commit/d2a8f019873d9f9fa09ea8bc94ddffe9d63de041
