### ISSUE TITLE
Gitbucket / Gogs integration

### ISSUE THREAD

**Issue by hhenkel** [reviewninja/review.ninja#1014]
Would it be possible to use Review.Ninja with gitbucket (https://github.com/gitbucket/gitbucket) or gogs (https://github.com/gogits/gogs/)? Both projects try to be a github clone and are currently in the process of modelling their apis after github.

**Comment by dfarr** [comment]
At this point in time we will not be pursuing enabling RN for GH clones. If this is something you wish to pursue we encourage you to fork this repo :smile: 

Please note that we use [node-github](https://github.com/mikedeboer/node-github) to integrate with GH's API (with the exception of oauth).
