### ISSUE TITLE
Button on Pull Request Page

### ISSUE THREAD

**Issue by amlwwalker** [reviewninja/review.ninja#1015]
Upvote capability on PR page of github - at the moment have to go to reviewninja page unecessarily

Merge button disabled/enabled buggy on review ninja page - when disabled (orange) sometimes is enabled (clickable) and when enabled (green) sometimes disabled

Add button/link to Reviewninja page to return to Pull request in github

**Comment by dfarr** [comment]
To add a ninja star without leaving GitHub, simply add a conversation comment on the PR with any of the following:
- !star
- !ninjastar
- :+1:
- :star: 

Similarly to unstar:
- !unstar
- :-1: 

Please see [here](https://github.com/reviewninja/review.ninja/issues/897) for more information.

**Comment by dfarr** [comment]
The colour of the merge button does not indicate the "mergeability" of the PR. Instead it simply indicates the *state* of the PR according to the status API. Below is a matrix of potential states (note that order corresponds to precedence).

|   | Merge possible (button enabled) | Merge not possible (button disabled) |
| --- | --- | --- |
| One status failing (red)           |   |   |
| One Status pending (orange) |   |   |
| All statuses passing (green)   |   |   |

**Comment by dfarr** [comment]
To jump back to GitHub from the RN page simply click on the PR # in the title of the PR.

![screen shot 2015-12-07 at 1 39 35 pm](https://cloud.githubusercontent.com/assets/1387834/11640618/5919c650-9ce8-11e5-8fd0-df0d86a58b9d.png)

**Comment by amlwwalker** [comment]
Thanks guys!
