### ISSUE TITLE
Pull Requests submitted by collaborators in private repositories are being automatically starred

### ISSUE THREAD

**Issue by gowong** [reviewninja/review.ninja#1022]
I have a private repo setup with one other collaborator. Every single PR that he submits is automatically starred by me even though I have never viewed the PR on review ninja and obviously never clicked the star button. Can't figure out why this is happening, but ReviewNinja is essentially useless with this behavior.

**Comment by dfarr** [comment]
Hi @gowong, are you leaving :+1: or :star: comments on the conversation for the PR in GitHub? 

These comments will automatically create a ninja star in ReviewNinja. We enabled this functionality to allow users to work with RN without having to leave GH. I could understand how this would be annoying if this is not the intention of these comments.

**Comment by gowong** [comment]
No comments are being left on the PRs. The stars are being added as soon as the PRs are created.

**Comment by dfarr** [comment]
Will close, as can not replicate. Please reopen is this resurfaces.
