### ISSUE TITLE
comments don't show up in overview if left on commit

### ISSUE THREAD

**Issue by disordered** [reviewninja/review.ninja#1025]
If a comment is left on a commit in github and not in a "Files Changed", then review ninja does not capture them, even if commit is the latest one.
To reproduce:
1. Create a pull request
2. Push a new commit to it
3. Go to github pull request details page
4. Click the link to latest commit
5. Leave a `!fix` comment in said commit
6. Note that github pull request details captures the comment, but ninja does not

**Comment by dfarr** [comment]
We actually don't support commit comments in RN. GH has three types of PR comments:
- conversation comments
- review comments (use flags here)
- commit comments

Our philosophy behind flagging problems is make the comment as specific as possible. This is why we require the flag be associated with a specific line of code, which only review comments provide. RN uses two types of comments (review and conversation), I fear introducing a third type may lead to unnecessary confusion.

**Comment by disordered** [comment]
I agree that there is no need to introduce more types of comments. However, I think it should be just merged together into the same view. If github is differentiating it somehow, it just adds to confusion.
The comments are also specific, they seem to be tied to specific commit sha and specific line.
see: https://github.com/disordered/ReviewNinja-Welcome/pull/3
I left two comments after the latest commit. First one in the commit, second in the "Files Changed". I can see both in PR, but only one in RN.
You can also click the file link in the comment header and it will open the comment on the line I left it.

That said, maybe it still comes down to the underlying problem - that there is no easy way to view a sub-diff and leave a comment. The reason I run into this problem is because on big reviews I don't want to review entire diff once again to find all changes done since last time I viewed. So I check the github PR to find the new commits and review those in github. If I forget to tab back to RN or "Files Changed" view, I end up with above problem. So maybe it is just part of what we discussed in #869 
The PR I linked above also shows this problem. If you look at the entire diff in RN it is very hard to spot that latest commit added a single letter.

**Comment by dfarr** [comment]
See #1045
