### ISSUE TITLE
Badge not being added to private repos PRs

### ISSUE THREAD

**Issue by cafesanu** [reviewninja/review.ninja#1029]
Hi! So the ninja badge comment is being added to my public Repos PRs, but for a reason no badge is being added when we create a PR on our private repo. So there is no way of going to to PR on ReviewNinja via github, making it hard to convince my team to use it.

Thanks!!!
Awesome job so far :)

**Comment by dfarr** [comment]
We use basic authentication to add our ReviewNinja comments to PRs. This works well for public repos, but unfortunately not private repos (our [ReviewNinja](https://github.com/review-ninja) user cannot add comments to your repo).

Quick fix: Add review-ninja as a collaborator to your repo (if it's an org I would suggest adding him as an outside collaborator, read access should suffice). 

Longer term fix: First, I'd like to rule-out "auto-adding" our review-ninja user to repos (feels too intrusive). Instead, we could offer a button in the settings page to invite review-ninja (only needed if repo is private), thoughts?.

**Comment by dfarr** [comment]
Just realized that our review-ninja user token did not have the proper scope to see private repos. I have just fixed this so if now add review-ninja to your private repo it should work!
