### ISSUE TITLE
Code review checklist

### ISSUE THREAD

**Issue by brianphillips** [reviewninja/review.ninja#1031]
I would love to be able to configure (on a per-repo basis perhaps) a code reviewers checklist that can be used to guide the review process.  I don't know if something simple could be done with an embedded [GFM tasklist](https://github.com/blog/1375%0A-task-lists-in-gfm-issues-pulls-comments) or if this would need to be additional functionality and state tracked in reviewninja itself.  I would also see this being useful as another pre-req for enabling merging (N ninja stars + no open issues + review checklist complete)

**Comment by dfarr** [comment]
I like the idea of a GFM tasklist, our general philosophy is when things *can* be done in GitHub (as opposed to ReviewNinja) then they *should* be done there.

We already have a nice mechanism to do this with our ninja comments (the image of a ninja with a speech bubble), just off the top of my head it would be possible to define a task list in RN and then every time a PR is created we auto-create a task list comment.

@brianphillips: just out of curiosity, what type of tasks would you include in your task list? Thanks!

**Comment by brianphillips** [comment]
@dfarr I would imagine the checklist might vary widely by project (was inspired by the discussion here: https://news.ycombinator.com/item?id=8861935).  For our purposes, it might be things like "all DB migrations backwards compatible" or "all API changes documented" or simliar.

Would building this off of a GFM tasklist still allow for blocking a merge if there are unchecked items?

**Comment by casche** [comment]
Hey @brianphillips, thanks for the suggestion. As @dfarr said, we like keeping things in GitHub that should be. Thus, I think this would be better served by using [Pull Request Templates](https://github.com/blog/2111-issue-and-pull-request-templates).

@dfarr Perhaps we might want to think about extending RN to read the ISSUE_TEMPLATE and create an issue list that must be !resolved before the status can be green?

**Comment by brianphillips** [comment]
@casche - makes sense, my suggestion predated github's launch of PR templates :)

**Comment by casche** [comment]
Hey @brianphillips no worries! Stay tuned and lets see what we can come up with...
