### ISSUE TITLE
Restrict users who can review more granularly

### ISSUE THREAD

**Issue by amlwwalker** [reviewninja/review.ninja#1032]
We are loving Review Ninja over here!

Couple of questions. One of the reasons we are implementing Review ninja is because some people are handling their own PRs. We can make the PR now require 2 stars, but there is nothing to stop them starring their own PR twice.

Is it possible to implement 

A member of a specific group/team is required to give one of the stars, while the other can be from anyone?

thanks
Alex

**Comment by dfarr** [comment]
Hey Alex, glad to hear you like ReviewNinja.

It is actually not possible to star a PR twice, so I wonder if setting the threshold to 2 would work? Alternatively you could set the threshold to 1 (from a team) and then assign your core "reviewers" to this team. When you set up a repo with a "review team" we still allow stars from anyone (including the creator of the PR), but only stars from the review team would count toward the threshold. Would this meet your requirements?

**Comment by sergekukharev** [comment]
:+1:  I would like to see such feature. People shouldn't be able to shuriken their own PR.

Thanks for amazing product, it is exactly what I expect from Code Review tool.

**Comment by casche** [comment]
Hey @sergekukharev and @amlwwalker,

As @dfarr said, if you require 2 ninja :stars: or require one from a team that you are not part of, then you will not be able to affect the status of the PR yourself. 

Therefore, if you are using [GitHub protected branches](https://github.com/blog/2051-protected-branches-and-required-status-checks), you will not be able to merge your own code. 

Does clarify? If it does not please comment and I will re-open this issue. Thanks for your interest in Review Ninja! 👍
