### ISSUE TITLE
Fix UI comment navigation for bigger PRs

### ISSUE THREAD

**Issue by warden** [reviewninja/review.ninja#1033]
See https://app.review.ninja/jenkinsci/jira-plugin/pull/72/.
There were a lot of comments and discussions made and a lot of issues were resolved in later commits.
Here are some problems:
- the fixed issues are not reflected in the comment status (in GitHub this is seen as "outdated diff")
- it is hard to navigate to the source code where the comments were actually made (my browser lags and hangs a lot and clicking on the revision:filename link below the comment does nothing in some cases) - this might be due to linking to lines that do no longer exist?
- when you enter the comment (to see the whole discussion) there is no link to the source file - that would be useful because you could have scrolled away from it while doing other things :)
- scrolling is really sluggish

**Comment by dfarr** [comment]
As ReviewNinja is no longer in active development mode (see #1132), I will close this issue.
