### ISSUE TITLE
GitHub integration has gotten inconsistent

### ISSUE THREAD

**Issue by rlamorea** [reviewninja/review.ninja#1039]
On the GitHub side, we have Review.Ninja set up as a required check to complete a pull request.

In the past few weeks the `details` link to Review.Ninja has vanished, so we have to open Review.Ninja separately and navigate to the pull request to complete the review.

A minor annoyance, but an annoyance nonetheless.

<img width="708" alt="screen shot 2016-01-21 at 10 55 11 am" src="https://cloud.githubusercontent.com/assets/3486207/12491041/aa6c6612-c02d-11e5-8a38-a61761a022a8.png">

Also, once in the Review.Ninja interface, we've noticed that the "Merge" button there no longer accurately represents the status of the pull request.

Nothing changed (that we know of) in our integration setup between GitHub and Review.Ninja.  It isn't clear if these problems stem from one side of the integration, the other, or both.

**Comment by dfarr** [comment]
Thanks for the report @rlamorea 

I am looking into this ASAP. In the meantime can you just verify that you have a webhook registered withe the URL https://app.review.ninja/github/webhook

Additionally, you may have an out-of-date webhook with a URL of https://app.review.ninja/github/webhook/XXXXXXXXXX, you may go ahead and remove this if you wish (keeping it incurs no negative effect)

**Comment by dfarr** [comment]
If it's a public repo would it be possible to provide a link?

**Comment by rlamorea** [comment]
Sorry, private repo.  But I'll check into the webhook.

**Comment by rlamorea** [comment]
Hmmm... the webhook link you provided didn't work.  And if I click on the "gear" for my repo, the only configuration items are for "Notifications", nothing else.

**Comment by dfarr** [comment]
Sorry @rlamorea, the webhook link should be present in your registered webhooks on your GH repo, I should've clarified that. For example, here are the registered webhooks for our reviewninja repo.

<img width="751" alt="screen shot 2016-01-21 at 1 53 08 pm" src="https://cloud.githubusercontent.com/assets/1387834/12495790/8fa49372-c046-11e5-9f46-a8b2310cde56.png">

Can you verify that this is configured on your repo? Thanks!

**Comment by rlamorea** [comment]
So no, we don't have https://app.review.ninja/github/webhook
Do I add it manually?

**Comment by dfarr** [comment]
Yes, please do. You can remove the old one.

That should've been updated automatically, I will explore why that was not the case.

**Comment by dfarr** [comment]
Please check the pull request, status, issue comment, and pull request review comment events

**Comment by rlamorea** [comment]
Added, and our details link is back.  Things look so much better.

I'll leave it up to you whether to close this or use it to track why the webhook didn't get updated (though I don't know if I've got any more information I could provide on that).
