### ISSUE TITLE
Mark areas that require attention/action for statuses

### ISSUE THREAD

**Issue by MitchK** [reviewninja/review.ninja#1041]
The tab "Statuses" makes the impression that everything is good, because of the checkmark and the blue/green color.

How about underlie the tab with a light orange color and change the icon if at least one of the services is pending?

Perhaps this also could be extended to the other tabs in case there is stuff inside that requires attention.

![screenshot from 2016-02-04 13 55 46](https://cloud.githubusercontent.com/assets/2472064/12831046/2e636816-cb47-11e5-935c-561896a50d88.png)

**Comment by dfarr** [comment]
Good suggestion! @MitchK PR pls?

**Comment by dfarr** [comment]
As ReviewNinja is no longer in active development mode (see #1132), I will close this issue.
