### ISSUE TITLE
Github emoticons don't work if not first thing in comment

### ISSUE THREAD

**Issue by amlwwalker** [reviewninja/review.ninja#1042]
If I leave a comment like:

> Looks Good
> :star: 

Review ninja doesnt accept that star as a ninja star. Only if its the first/only thing in the comment

**Comment by dfarr** [comment]
I cannot replicate  this problem. For me putting the :star: or :+1: anywhere in the comment seems to work.

Tested with:

testing testing testing
:star: 

this is no good :-1: 

> asdf
> :star: 

once more with :-1: in the middle
