### ISSUE TITLE
ReviewNinja status not appearing on private repo

### ISSUE THREAD

**Issue by MattMorgis** [reviewninja/review.ninja#1043]
I am not sure if this what was discussed in #1029 or if this is something slightly different.

We are running our own instance of ReviewNinja with private repos. We have a two-star requirement. 

When a team member submits a PR, our CI server performs a test build, but there is no status check from ReviewNinja. Screenshot:
![screen shot 2016-02-10 at 9 51 12 am](https://cloud.githubusercontent.com/assets/4664374/12950624/1cd1dfe4-cfdc-11e5-8956-d43c87bad6ea.png)

However, once the first NinjaStar is added to the PR, the status is updated accordingly by ReviewNinja. Screenshot:
![screen shot 2016-02-10 at 9 50 49 am](https://cloud.githubusercontent.com/assets/4664374/12950603/06a67b44-cfdc-11e5-9b44-e316cc3859e9.png)

How can we configure ReviewNinja so that it says there are 0/2 stars when the pull request is first created?

**Comment by dfarr** [comment]
Can you verify that the RN webhook has been added to your repo, and if not add it?

URL: https://app.review.ninja/github/webhook (with your instance's domain name)

With the following events:
- pull_request
- pull_request_review_comment
- issues
- issue_comment
- status

This should have been added automatically, but perhaps an error occurred, or it was manually deleted.

**Comment by MattMorgis** [comment]
Thanks, @dfarr. I actually _just_ figured out our issue by digging through #1039. 

Our instance of ReviewNinja is behind a private firewall and the new web hook was not successfully posting to our instance when a new PR was created. All resolved now, thank you for getting back to me.
