### ISSUE TITLE
ReviewNinja doesn't show commit comments from GitHub

### ISSUE THREAD

**Issue by hollasch** [reviewninja/review.ninja#1045]
If I review a pull request commit-by-commit in GitHub, then comments I enter there are not shown in ReviewNinja. This may be related to the need for ReviewNinja to provide a way to review each commit individually, but I expected that all of the comments would at least be shown.

I just tested, and a comment I enter directly on the pull request _does_ show up in ReviewNinja, but pull request comments from the contributing commits are not displayed.

**Comment by dfarr** [comment]
For RN we have opted to support holistic reviews of the PR. By treating a PR as a single entity we can make commenting less confusing (for example, comments on old commits can easily become lost). This is why we instead support PR comments (comments on the *entire* PR) and review comments (comments on specific lines in the diff).
