### ISSUE TITLE
Winston is missing in package.json

### ISSUE THREAD

**Issue by ezraroi** [reviewninja/review.ninja#1046]
I am trying to run ReviewNinja on my server and it is not starting because of missing winston module.

**Comment by dfarr** [comment]
You must be using npm v3 ;)

Winston is a peer dependency of another dependency (papertrail), that is no longer used. In npm v3, peer dependencies are no longer automatically installed. Let me remove that dependency and this should be cleared up.

**Comment by dfarr** [comment]
#1047

**Comment by dfarr** [comment]
@ezraroi, please go ahead and give it another try now

**Comment by ezraroi** [comment]
Thanks, working...
