### ISSUE TITLE
expand code in "snippets" similar to GH

### ISSUE THREAD

**Issue by yairogen** [reviewninja/review.ninja#1049]
many times when reviewing you need to some more context but UI doesn't allow to expand hidden un-changed lines.

**Comment by dfarr** [comment]
Try clicking on the "+" icon in the top right corner of a diff - is this the functionality you are looking for?

**Comment by yairogen** [comment]
not quite. this + opens the entire file and not only a few rows to give more context. 
I'd like to see some ui more similar to what reviewable offers in this aspect or at least like "regular" github review view (the "expand" option).

**Comment by dfarr** [comment]
I have tweaked this issue to be a feature request, thanks!

**Comment by dfarr** [comment]
Will close this issue as it is not a high priority feature for us, may consider re-opening in the future.
