### ISSUE TITLE
Make `starRegex` extensible?

### ISSUE THREAD

**Issue by chazeah** [reviewninja/review.ninja#1050]
Hey there,

We've just started trying out Review Ninja for our team. One thing we're realizing is that old habits die hard – people are resistant to change their existing flows/behaviors. Our team consistently uses the phrase `LGTM` to indicate "approval" on a code review. Any chance we could add the string `LGTM` to `starRegex`?
https://github.com/reviewninja/review.ninja/blob/master/src/server/services/flags.js#L49

Alternately, how about exposing it in the per-repo settings?
![image](https://cloud.githubusercontent.com/assets/899450/13618766/ce8a5fb8-e53a-11e5-9941-9576e93ab96d.png)

Thanks!
Charley

**Comment by dfarr** [comment]
Nice find in the code! I will label this as a feature request. 

We are actively looking for partners to contribute to RN, if you would like to contribute a PR for this feature, I would be happy to merge. Just let me know if you need any pointers :smile:

**Comment by dfarr** [comment]
Actually, I think GH's brand new [reactions](https://github.com/blog/2119-pull-request-and-issue-reactions) may make this feature unnecessary. If you can *react* to a PR, this may be better than a separate comment altogether.

**Comment by chazeah** [comment]
Yeah, Reactions may be a great solution. Some initial thoughts:

* Which item would the review react to? The initial PR message? e.g.
  ![image](https://cloud.githubusercontent.com/assets/899450/13888662/caeb9436-ecff-11e5-95bb-6d2ebc34c49b.png)
* Reactions don't send email notifications (on purpose). As such, though, the original author may not realize that their PR has been approved. I know our team relies on the "LGTM :+1:" emails to know they can go merge their branch. May need to add this as an optional setting or something.
* Doesn't appear Reactions data documented in the API yet.

**Comment by dfarr** [comment]
Good point about the API. GH does have a teaser on their [blog](https://developer.github.com/changes/2016-03-15-new-webhook-actions/) that could be a clue that this is coming as a webhook event.

In RN settings you can get an email when someone ninja stars a PR, so an email would be possible if we translate reactions to stars!

**Comment by diwu1989** [comment]
im starting to use review ninja with my team and this is really important to us. We want to keep the current tradition of using `LGTM` (and ONLY `LGTM`) as the regex to pass a pull request

**Comment by dfarr** [comment]
As ReviewNinja is no longer in active development mode (see #1132), I will close this issue.
