### ISSUE TITLE
Self-hosted version doesn't load after authorization

### ISSUE THREAD

**Issue by gregswift** [reviewninja/review.ninja#1052]
We recently upgraded to latest GH:Ent which supports the protected branches and required testing. I took that as an opportunity to try out reviewninja internally.  After standing the system up and adding it as an application in our GH I tried it out.  I was able to log in and authorize things, but from then on it either takes me only to the login page, doesn't load anything after the login page, or doesn't load at all.  I haven't been able to find any logs from reviewninja itself.  nginx and GH logs look fine.

Any suggestions on where to go from here?

**Comment by gregswift** [comment]
Figured out to use the following to start it:

```
forever -l forever.log -e err.log -a start app.js
```

Initial error i got was:
```
module.js:327
    throw err;
    ^

Error: Cannot find module 'node-sass-middleware'
    at Function.Module._resolveFilename (module.js:325:15)
    at Function.Module._load (module.js:276:25)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/app/src/server/app.js:10:22)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)
```

So I did an ```npm install node-sass-middleware``` and now i get:

```
Error: Failed to deserialize user out of session
    at pass (/app/node_modules/passport/lib/authenticator.js:340:19)
    at Authenticator.deserializeUser (/app/node_modules/passport/lib/authenticator.js:358:5)
    at SessionStrategy.authenticate (/app/node_modules/passport/lib/strategies/session.js:49:28)
    at attempt (/app/node_modules/passport/lib/middleware/authenticate.js:341:16)
    at authenticate (/app/node_modules/passport/lib/middleware/authenticate.js:342:7)
    at Layer.handle [as handle_request] (/app/node_modules/express/lib/router/layer.js:95:5)
    at trim_prefix (/app/node_modules/express/lib/router/index.js:312:13)
    at /app/node_modules/express/lib/router/index.js:280:7
    at Function.process_params (/app/node_modules/express/lib/router/index.js:330:12)
    at next (/app/node_modules/express/lib/router/index.js:271:10)
```

**Comment by gregswift** [comment]
Did some research on the error and found people talking about having to reset user session info. So i went to go log into the database to clear everything. Found out that mongod had stopped running. Restarted it and have moved onto this error:

```
/app/node_modules/passport-github/node_modules/passport-oauth/lib/passport-oauth/strategies/oauth2.js:66
  if (!options.clientID) throw new Error('OAuth2Strategy requires a clientID option');
                         ^

Error: OAuth2Strategy requires a clientID option
    at Strategy.OAuth2Strategy (/app/node_modules/passport-github/node_modules/passport-oauth/lib/passport-oauth/strategies/oauth2.js:66:32)
    at new Strategy (/app/node_modules/passport-github/lib/passport-github/strategy.js:61:18)
    at Object.<anonymous> (/app/src/server/passports/github.js:9:14)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at /app/src/server/app.js:220:25
    at Array.forEach (native)
    at /app/src/server/app.js:218:26
    at f (/app/node_modules/glob/node_modules/once/once.js:17:25)
    at Glob.<anonymous> (/app/node_modules/glob/glob.js:133:7)
    at emitOne (events.js:77:13)
    at Glob.emit (events.js:169:7)
```

**Comment by gregswift** [comment]
Did some research on the error and found people talking about having to reset user session info. So i went to go log into the database to clear everything. Found out that mongod had stopped running. Restarted it.  App is back to throwing no errors and not loading fully *see screenshot)
![rn-logged-in](https://cloud.githubusercontent.com/assets/372939/13801414/85c110ae-eaff-11e5-9eaf-8be88ffab797.png)

With a fresh session in a different browser clicking the sign in button doesn't do anything either.

**Comment by gregswift** [comment]
fwiw here is the strace when i load the page.  Several ```304 Not Modified``` being returned and several ```Resource temporarily unavailable```

[strace.txt](https://github.com/reviewninja/review.ninja/files/175272/strace.txt)

**Comment by gregswift** [comment]
I decided to look into the web console on the browser and found what is likely the culprit.  the app.js that is being run is not the same app.js as when i goto review.ninja. It looks like its a bootstrapper, and its using require. The web console shows:

```
ReferenceError: require is not defined
<anonymous>
 app.js:3
```

**Comment by dfarr** [comment]
Hmm strange, sounds like you've tried lots here. Let me try to wrap my head around potential problems. First question: can you confirm that all npm and bower dependancies have been loaded correctly?

You can always run `npm install` and `bower install`. Anything missing will be retrieved, thanks!

**Comment by gregswift** [comment]
```
$ npm install
-
> phantomjs@1.9.19 install /app/node_modules/phantomjs
> node install.js

PhantomJS is previously installed at phantom/bin/phantomjs

> ReviewNinja@1.2.0 postinstall /app
> bower install

npm WARN unmet dependency /app/node_modules/mongoose requires async@'1.5.2' but will load
npm WARN unmet dependency /app/node_modules/async,
npm WARN unmet dependency which is version 0.9.2
npm WARN unmet dependency /app/node_modules/karma-mocha-reporter requires karma@'>=0.13' but will load
npm WARN unmet dependency /app/node_modules/karma,
npm WARN unmet dependency which is version 0.12.37
npm WARN unmet dependency /app/node_modules/request/node_modules/form-data requires async@'^1.4.0' but will load
npm WARN unmet dependency /app/node_modules/async,
npm WARN unmet dependency which is version 0.9.2
npm WARN unmet dependency /app/node_modules/supertest/node_modules/superagent/node_modules/form-data requires async@'^1.4.0' but will load
npm WARN unmet dependency /app/node_modules/async,
npm WARN unmet dependency which is version 0.9.2
npm WARN unmet dependency /app/node_modules/browser-sync/node_modules/localtunnel/node_modules/request/node_modules/form-data requires async@'^1.4.0' but will load
npm WARN unmet dependency /app/node_modules/async,
npm WARN unmet dependency which is version 0.9.2
npm WARN unmet dependency /app/node_modules/gulp-coveralls/node_modules/coveralls/node_modules/request/node_modules/form-data requires async@'^1.4.0' but will load
npm WARN unmet dependency /app/node_modules/async,
npm WARN unmet dependency which is version 0.9.2
npm WARN unmet dependency /app/node_modules/gulp-istanbul/node_modules/istanbul requires async@'1.x' but will load
npm WARN unmet dependency /app/node_modules/async,
npm WARN unmet dependency which is version 0.9.2
npm WARN unmet dependency /app/node_modules/gulp-istanbul/node_modules/istanbul/node_modules/handlebars requires async@'^1.4.0' but will load
npm WARN unmet dependency /app/node_modules/async,
npm WARN unmet dependency which is version 0.9.2
npm WARN unmet dependency /app/node_modules/karma-coverage/node_modules/istanbul requires async@'1.x' but will load
npm WARN unmet dependency /app/node_modules/async,
npm WARN unmet dependency which is version 0.9.2
npm WARN unmet dependency /app/node_modules/karma-coverage/node_modules/istanbul/node_modules/handlebars requires async@'^1.4.0' but will load
npm WARN unmet dependency /app/node_modules/async,
npm WARN unmet dependency which is version 0.9.2
parse-diff@0.0.11 node_modules/parse-diff
├── underscore@1.6.0
├── underscore.string@2.3.3
└── coffee-script@1.7.1 (mkdirp@0.3.5)
```

Still not working.

also... the first time i had this running it at least let me log in and authorize before stopping. Now it never does anything from signup.

**Comment by dfarr** [comment]
Okay, I am fairly confident that you have RN installed properly. Most likely this is a configuration problem. Can you send me a list of your env variables? (just not your app secret :stuck_out_tongue: )

**Comment by gregswift** [comment]
```
# MongoDB Settings
export MONGODB=mongodb://127.0.0.1/reviewninja

# Client ID and Secret of your GitHub Application (described above)
export GITHUB_CLIENT=JHDFJAKFDJFKJ
export GITHUB_SECRET=KASDJKLASJDLKASJDF

# Node.js Environment
export NODE_ENV=production

# ReviewNinja server settings
export PROTOCOL=http
export HOST=reviews.me.com

# GitHub server settings
export GITHUB_PROTOCOL=https
export GITHUB_HOST=github.me.com
export GITHUB_API_HOST=github.me.com
export GITHUB_API_PATHPREFIX=/api/v3

# Custom certificates
export CERT=/certs/*
```

thanks!

**Comment by dfarr** [comment]
Okay, I think I know what's happening.

Does your company use a custom root certificate? If not please try commenting out `export CERT=/certs/*` (you may need to do `unset CERT` as well), and restarting RN. 

Node's http module uses a custom root store. We bootstrap any certificates you provide on application startup, to handle the case where a company uses a custom root certificate for their GHE instance. If this folder is empty, the [bootstrap certs](https://github.com/reviewninja/review.ninja/blob/master/src/server/app.js#L73) function will replace the module's default certs and any request to a resource over `https` will fail.

**Comment by gregswift** [comment]
Changed it to unset and restarted.. same behavior.  The only error I'm seeing is still the 

```
ReferenceError: require is not defined
<anonymous>
 app.js:3
```

**Comment by dfarr** [comment]
That's really odd, we do not use AMD on the frontend. I would not expect to see `require` at all...

**Comment by dfarr** [comment]
In your browser can you check out http://reviews.me.com/app.js and let me know what is there?

**Comment by gregswift** [comment]
It matches https://github.com/reviewninja/review.ninja/blob/master/app.js

**Comment by dfarr** [comment]
It should instead match https://github.com/reviewninja/review.ninja/blob/master/src/client/app.js.

Okay, that's interesting, can you verify that the [static files](https://github.com/reviewninja/review.ninja/blob/master/src/server/app.js#L106) are being properly bootstrapped on app startup, (should say "bootstrap static files" in the application logs). For some reason it looks like the root level files are being exposed to the client.

**Comment by dfarr** [comment]
The application logs should look something like this:

```
In server/app.js
checking configs
✓ configs seem ok
Host:        http://localhost:5000
GitHub:      https://github.com
GitHub-Api:  https://api.github.com
bootstrap certificates
bootstrap static files
apply migrations
✓ src/server/migrations/1.1.0_1.js
✓ src/server/migrations/1.1.0.js
✓ src/server/migrations/1.2.0.js
✓ src/server/migrations/1.3.2.js
✓ src/server/migrations/1.5.0_1.js
✓ src/server/migrations/1.5.0_2.js
✓ src/server/migrations/1.5.0.js
ℹ︎ Migration '1.1.0_1': skip (migration already ran)
ℹ︎ Migration '1.1.0': skip (migration already ran)
ℹ︎ Migration '1.2.0': skip (migration already ran)
ℹ︎ Migration '1.3.2': skip (migration already ran)
ℹ︎ Migration '1.5.0_1': skip (migration already ran)
ℹ︎ Migration '1.5.0_2': skip (migration already ran)
ℹ︎ Migration '1.5.0': skip (migration already ran)
bootstrap mongoose
✓ src/server/documents/action.js
✓ src/server/documents/repo.js
✓ src/server/documents/settings.js
✓ src/server/documents/slack.js
✓ src/server/documents/star.js
✓ src/server/documents/user.js
bootstrap passport
✓ src/server/passports/github.js
✓ src/server/passports/slack.js
bootstrap controller
✓ src/server/controller/badge.js
✓ src/server/controller/config.js
✓ src/server/controller/stats.js
✓ src/server/controller/user.js
✓ src/server/controller/default.js
bootstrap api
✓ src/server/api/github.js
✓ src/server/api/invitation.js
✓ src/server/api/onboard.js
✓ src/server/api/repo.js
✓ src/server/api/settings.js
✓ src/server/api/slack.js
✓ src/server/api/star.js
✓ src/server/api/status.js
✓ src/server/api/user.js
✓ src/server/api/webhook.js
bootstrap webhooks
✓ src/server/webhooks/issue_comment.js
✓ src/server/webhooks/ping.js
✓ src/server/webhooks/pull_request_review_comment.js
✓ src/server/webhooks/pull_request.js
✓ src/server/webhooks/status.js
bootstrap monkey patch
✓ bootstrapped, app listening on localhost:5000
```

**Comment by gregswift** [comment]
If i look in the forever log that is what that looks like. 

```
[ninja@reviews app]$ cat ~/.forever/forever.log 
In server/app.js
checking configs
✓ configs seem ok
Host:        http://reviews.me.com
GitHub:      https://github.me.com
GitHub-Api:  https://github.me.com
bootstrap certificates
bootstrap static files
apply migrations
Now lets create the server
✓ src/server/migrations/1.1.0.js
✓ src/server/migrations/1.1.0_1.js
✓ src/server/migrations/1.2.0.js
✓ src/server/migrations/1.3.2.js
ℹ︎ Migration '1.1.0': skip (migration already ran)
ℹ︎ Migration '1.1.0_1': skip (migration already ran)
ℹ︎ Migration '1.2.0': skip (migration already ran)
ℹ︎ Migration '1.3.2': skip (migration already ran)
bootstrap mongoose
✓ src/server/documents/action.js
✓ src/server/documents/repo.js
✓ src/server/documents/settings.js
✓ src/server/documents/star.js
✓ src/server/documents/user.js
bootstrap passport
✓ src/server/passports/github.js
bootstrap controller
✓ src/server/controller/badge.js
✓ src/server/controller/config.js
✓ src/server/controller/count.js
✓ src/server/controller/user.js
✓ src/server/controller/default.js
bootstrap api
✓ src/server/api/github.js
✓ src/server/api/invitation.js
✓ src/server/api/onboard.js
✓ src/server/api/repo.js
✓ src/server/api/settings.js
✓ src/server/api/star.js
✓ src/server/api/status.js
✓ src/server/api/user.js
✓ src/server/api/webhook.js
bootstrap webhooks
✓ src/server/webhooks/issue_comment.js
✓ src/server/webhooks/ping.js
✓ src/server/webhooks/pull_request.js
✓ src/server/webhooks/pull_request_review_comment.js
✓ src/server/webhooks/status.js

✓ bootstrapped, app listening on localhost:5000
```

**Comment by gregswift** [comment]
My original install was of master... so i did checkout the 2.0.0 tag and clear all the node_modules/* and re-run the npm install and still same behavior :/

**Comment by gregswift** [comment]
So.. just had one of our devs swing by and help me look at it. We did a curl against :5000/app.js and got the correct thing. It seems that nginx is causing the hiccup. I'm using the example from the docs

**Comment by dfarr** [comment]
I'm guessing you've modified it to listen on port 80?

```
upstream app_server {
    server 127.0.0.1:5000 fail_timeout=0;
}

server {
    listen 80;

    location / {
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header Host $http_host;
        proxy_redirect off;

        if (!-f $request_filename) {
            proxy_pass http://app_server;
            break;
        }
    }
}
```

**Comment by gregswift** [comment]
gah! ... okay... so in my testing i had tried using the nginx config we use for jenkins, similar proxy setup.  Apparently i had left that in place.  Now i am back to the nginx config yall provide, but using ssl on 443. 

The require error is gone and the ```src/server/app.js``` gets loaded instead of ```app.js```.

But still i sit at the sign in screen and dont go anywhere... except now i have no errors at all.

**Comment by dfarr** [comment]
Have you generated the certs needed for https?

If so, try changing your PROTOCOL
```
export PROTOCOL=https
```

Your callback URLs for the GH application should make sure to address your RN instance on https as well. Example: `http://reviews.me.com/auth/github/callback`

**Comment by gregswift** [comment]
I do have certs, but they are configured in nginx.  Should i re-enable the custom certs support because i'm using an internal CA?

**Comment by gregswift** [comment]
1 step forward.  changing protocol to https got me back to being able to authorize.  but then it goes back to login and wont go back in.

**Comment by dfarr** [comment]
No, these are two different certificates. Our CERTS environment variable allow you to configure a **custom root CA**, but the cert/key that are referred to in nginx enable **RN over SSL (https)**.

**Comment by dfarr** [comment]
So please do not put your SSL certs into RN, only reference them in nginx. Then if you change the PROTOCOL env variable, we may be getting somewhere!

**Comment by gregswift** [comment]
To clarify, all i did was change the protocol variable. We did go that 1 step forward, but thats it.

**Comment by dfarr** [comment]
Can you verify your callback URL looks like this `https://reviews.me.com/auth/github/callback `?

**Comment by gregswift** [comment]
```https://reviews.me.com/auth/github/callback``` pulled from github

**Comment by dfarr** [comment]
Hmm, can you verify that the user was created in your database?
```
use reviewninja
db.users.find()
```

**Comment by gregswift** [comment]
I have 2 users in my database.

```
> db.users.find()
{ "_id" : ObjectId("56eb21aee12cb8593c381f0c"), "uuid" : 1129, "token" : "longstring" }
{ "_id" : ObjectId("56ec4290e12cb8593c381f0d"), "uuid" : 607, "token" : "longstring" }
```

**Comment by dfarr** [comment]
Hmmm, this would be a longshot, but can you try revoking RN access from your account in GHE (https://github.com/settings/applications), and attempting to sign in again.

So the current state: sign in, redirect to GH, redirect to GH, authrorize RN, redirected back to RN login screen - is this correct?

**Comment by gregswift** [comment]
When I got back to this point I revoked the access and tried again. current state sounds right.  Main page, Sign In, Redirect to GH for authorize, redirect back to RN main page/signin, continues to load RN main page (with the sign in button, not just the top bar only screen i had screenshotted'

**Comment by dfarr** [comment]
Can you see if there is anything being printed out on the web console? Also check the "network" tab, sometimes GH will throw a "redirect URI mismatch" error. The network tab will look something like this:

![screen shot 2016-03-21 at 11 53 42 am](https://cloud.githubusercontent.com/assets/1387834/13930295/bdd2c1f8-ef5b-11e5-86a9-3ba45c83c664.png)

**Comment by gregswift** [comment]
your 4th one down is a 200. mine is a 304. 
![rn-network-4th](https://cloud.githubusercontent.com/assets/372939/13934412/1baee5a8-ef80-11e5-8b12-168e3580f81d.png)


but as for a general error, i'm not seeing one

**Comment by gregswift** [comment]
I'm going to take a step back and start this thing off fresh when I get a chance. Hopefully within the next week

**Comment by dfarr** [comment]
Actually, it seems like you've uncovered a bug, must've been introduced recently. Next time you authenticate and are redirected back to the login page, try doing a "hard refresh" `control+shift+r`. I am looking into this problem now.

**Comment by gregswift** [comment]
that worked

**Comment by dfarr** [comment]
:+1: hopefully will figure out a solution soon :smiley:

**Comment by gregswift** [comment]
womp womp waa.... 


```We couldn’t deliver this payload: Service Timeout ```

**Comment by gregswift** [comment]
this might be a local network layer thing.. digging further

**Comment by dfarr** [comment]
Okay, I have also fixed the "hard refresh" problem. Our SPA may have been cached, needed to ensure this header was set:
```
res.set('Cache-Control', 'private, max-age=0, no-cache, no-store');
```

If you try deploying the latest version of RN (v2.0.1), this should no longer be a problem!

**Comment by gregswift** [comment]
Looks like that worked.. I had someone who had never logged in try it and success!

Did yall add the ```node-sass-middleware``` dependency i found that I had to install separately?

**Comment by dfarr** [comment]
I'm surprised you got such an error, since we actually use [less middleware] (https://github.com/reviewninja/review.ninja/blob/master/package.json#L45)
