### ISSUE TITLE
Handling unicode emoji

### ISSUE THREAD

**Issue by flemeur** [reviewninja/review.ninja#1055]
Sometimes browsers convert the emoji for "thumbsup" to the unicode character ([U+1F44D](http://www.fileformat.info/info/unicode/char/1F44D/index.htm)). This results in the comment not being parsed by review ninja.

`👍` vs `:+1:`

Anybody else have this problem and know of a solution?

**Comment by dfarr** [comment]
Can you provide a screenshot of the this? We throw the raw comment at GH's markdown:render API, which should actually convert the emoji into an `<img>`, so not sure why this is happening. Also which browser is this happening with?

**Comment by flemeur** [comment]
I can now confirm, after further testing, that it also happens with the `:star:`, but only when using the built-in autocompletion. Confirmed in safari and chrome. If I type out `:+1:` or `:star:`, without using autocomplete, it works as expected. The funny thing is that github/the browser renders both versions of the emoji the same way. The only way to tell the difference is to click "Edit" on the comment.

I've attached some screenshots so you can see how it looks.

On github they are rendered the same way (the last comment was the only one that worked):
![screenshot from 2016-04-11 11 13 47](https://cloud.githubusercontent.com/assets/898359/14422342/9d450726-ffd6-11e5-8a58-d48bf53437eb.png)

The difference shows when opening the comment editor:
![screenshot from 2016-04-11 11 14 04](https://cloud.githubusercontent.com/assets/898359/14422352/b3ac268e-ffd6-11e5-8341-df66f7c3dbff.png)

**Comment by dfarr** [comment]
I actually didn't know that was possible! Okay, looks like RN is handling the *rendering* correctly, but it is failing to recognize that the unicode star is, in fact, a star (same with thumbs up/down, etc).

And this totally make sense, [as you can see in the code](https://github.com/reviewninja/review.ninja/blob/master/src/server/services/flags.js#L49).

So we will need to extend the regex to match unicode as well. Just doing some quick googling, it looks like [xregexp](http://xregexp.com/) is commonly used.

**Comment by flemeur** [comment]
Any timeline for a fix?

**Comment by casche** [comment]
Not yet @flemeur! but please stay tuned 📺!

**Comment by flemeur** [comment]
Fantastic! Thanks for fixing this! :+1:
