### ISSUE TITLE
Bulk enable for multiple existing repositories

### ISSUE THREAD

**Issue by pgmillon** [reviewninja/review.ninja#1056]
Hi,
At Nuxeo, we'd like to use ninjareview for our pull requests. 
We have many existing repositories (74) we need to add.
I can see there's an API (consumed by the webapp) but can we use it for bulk activation ?
Thanks.

**Comment by dfarr** [comment]
Good question, repos in RN are enabled *per user*, we basically store an array of repos associated with the user. The actual "connection" to GH is made via a webhook added in GH.

To bulk enable repos with RN, I would suggest calling [GH's create webhook API](https://developer.github.com/v3/repos/hooks/#create-a-hook), with the following information:

```json
{
  "name": "web",
  "config": {"url": "https://app.review.ninja/github/webhook", "content_type": "json"},
  "events": ["pull_request", "pull_request_review_comment", "issues", "issue_comment", "status"]
}
```

You will need to call this for each repo in your org, so before you call this you would have to make an additional call to get all repos, and then call to create a webhook for each.

Once this is done, RN will start reporting on each PR in each repo!

**Comment by pgmillon** [comment]
Hi,
I wasn't sure creating the hook on github would be enough to make RN work.
Thanks.

**Comment by dfarr** [comment]
Np :+1:

**Comment by pgmillon** [comment]
Ok just made a test, the hook on github worked.
Now I have to configure each integration threshold & notifications.
Is there any way I could do that easily since I already have the list of repositories where ninjareview will be enabled ?
