### ISSUE TITLE
Is there an option of not letting juniors to submitting code before proper review.

### ISSUE THREAD

**Issue by arun21-nit** [reviewninja/review.ninja#1057]

**Comment by dfarr** [comment]
This is not possible in GH, nor is it something we would enable (makes more sense as a repo level setting).

You could look into [protected branches](http://scn.sap.com/people/david.farr/blog/2015/10/12/enforceable-code-review-with-reviewninja), or alternatively use a **fork and pull** model for junior developers and don't give them push access on the "master" repo.

**Comment by casche** [comment]
Hi @arun21-nit,

If you use protected branches as @dfarr mentions in addition to our 'team reviewers' functionality you could prevent PR's from being merged before they receive a ⭐ from some team of experts. 

But as @dfarr mentions, I agree that in the spirit of GitHub a **fork and pull **model would be more suitable.

Thanks for the question, we hope that answers it and will close this issue.
