### ISSUE TITLE
Bulk configuration

### ISSUE THREAD

**Issue by pgmillon** [reviewninja/review.ninja#1060]
Hi,
I can enable NinjaReview for my multiple repositories with the Github API but now I need to configure each integration threshold & notifications.
Is there any way I could do that easily (74 repos with the same configuration : 2 ninja stars for the https://github.com/orgs/nuxeo/teams/reviewers/ team + notify on slack) ?
Thanks.

**Comment by casche** [comment]
Hello @pgmillon,

Thanks for the suggestion! 😃 We understand your problem but this may be an edge case and not functionality we would consider at this time.

That being said, if you have a suggestion on how you see this working please share. Or if you would like to create this functionality yourself please submit a PR.

Thanks for your interest!
