### ISSUE TITLE
reviewNinja not spotting stars in comments

### ISSUE THREAD

**Issue by amlwwalker** [reviewninja/review.ninja#1062]
We are having problems that have come about recently where Review Ninja is not acting on behalf of stars that are pushed to comments. Is this something anyone else is noticing? Perhaps Review Ninja is overloaded or something?

This used to work fine....

Also, I am sure it used to be the case that the original PR requester couldn't add a star to their own PR, but now that seems possible. Am I correct in thinking this?

**Comment by dfarr** [comment]
The PR creator can, and always could, star a PR.

I believe this is related to #1055, previously GH used to represent emojis as string (eg, a star was `:star:`), but now they are represented by unicode characters. Please follow the other issue for updates, will push code fixing this problem ASAP.
