### ISSUE TITLE
Error: Unknown authentication strategy "slack"

### ISSUE THREAD

**Issue by lifeofguenter** [reviewninja/review.ninja#1064]
Getting the following error when clicking on the "Slack button" under "Settings":

```
Apr 29 12:43:51 XXX node[19898]: Error: Unknown authentication strategy "slack"
Apr 29 12:43:51 XXX node[19898]: at attempt (/var/app/current/node_modules/passport/lib/middleware/authenticate.js:173:37)
Apr 29 12:43:51 XXX node[19898]: at authenticate (/var/app/current/node_modules/passport/lib/middleware/authenticate.js:349:7)
Apr 29 12:43:51 XXX node[19898]: at /var/app/current/src/server/controller/user.js:57:32
Apr 29 12:43:51 XXX node[19898]: at Layer.handle [as handle_request] (/var/app/current/node_modules/express/lib/router/layer.js:95:5)
Apr 29 12:43:51 XXX node[19898]: at next (/var/app/current/node_modules/express/lib/router/route.js:131:13)
Apr 29 12:43:51 XXX node[19898]: at Route.dispatch (/var/app/current/node_modules/express/lib/router/route.js:112:3)
Apr 29 12:43:51 XXX node[19898]: at Layer.handle [as handle_request] (/var/app/current/node_modules/express/lib/router/layer.js:95:5)
Apr 29 12:43:51 XXX node[19898]: at /var/app/current/node_modules/express/lib/router/index.js:277:22
Apr 29 12:43:51 XXX node[19898]: at Function.process_params (/var/app/current/node_modules/express/lib/router/index.js:330:12)
Apr 29 12:43:51 XXX node[19898]: at next (/var/app/current/node_modules/express/lib/router/index.js:271:10)
Apr 29 12:43:51 XXX node[19898]: at Function.handle (/var/app/current/node_modules/express/lib/router/index.js:176:3)
Apr 29 12:43:51 XXX node[19898]: at router (/var/app/current/node_modules/express/lib/router/index.js:46:12)
Apr 29 12:43:51 XXX node[19898]: at Layer.handle [as handle_request] (/var/app/current/node_modules/express/lib/router/layer.js:95:5)
Apr 29 12:43:51 XXX node[19898]: at trim_prefix (/var/app/current/node_modules/express/lib/router/index.js:312:13)
Apr 29 12:43:51 XXX node[19898]: at /var/app/current/node_modules/express/lib/router/index.js:280:7
Apr 29 12:43:51 XXX node[19898]: at Function.process_params (/var/app/current/node_modules/express/lib/router/index.js:330:12)
```

**Update:** This is more of a feature request, but would it be possible to bring back (as a switch) the old behaviour where you can enter credentials directly? Using a slack-button might not work inside firewalled areas (slack does not use distinctive ip ranges)

**Comment by cameronbriar** [comment]
+1

**Comment by dfarr** [comment]
That is very strange, just to verify, all you are doing:

1) go to repo settings
2) click on "add to slack"

And you are immediately shown this error?

**Comment by lifeofguenter** [comment]
Correct, on version v2.0.1

**Comment by dfarr** [comment]
Oh, is this occurring on a self hosted instance of ReviewNinja?

**Comment by lifeofguenter** [comment]
Yup :)

**Comment by dfarr** [comment]
Gotchya,

For the moment I would suggest removing any SLACK env variables from your setup. Integrating RN with slack requires an additional [web app](https://github.com/reviewninja/slack-hooks) running. If the SLACK env variables are not present than the button will be hidden on the UI.

**Comment by dfarr** [comment]
Expanding the documentation for the slack integration is piece is one of my to-dos 😄

**Comment by lifeofguenter** [comment]
I know, I did both installations ;) - e.g. I installed review.ninja first without knowing that there was a separate slackbot - the button did not show.

I found the repo (https://github.com/reviewninja/slack-hooks ?) and was able to install it and in general it seems to be running:

```
$ curl -i localhost:5001
HTTP/1.1 200 OK
Date: Fri, 29 Apr 2016 18:41:06 GMT
Content-Type: text/html;charset=UTF-8
Content-Length: 24
Server: Jetty(7.x.y-SNAPSHOT)

ReviewNinja + Slack = <3
```

Is there anything else needed for it to work?

**Comment by dfarr** [comment]
The slack app looks like its good! You need two more (undocumented, sorry) env vars:

SLACK_CLIENT
SLACK_SECRET

These are the client_id and secret of a slack developer app you need to set up. The callback URL in that app should be set to: localhost:5001/auth/slack/callback

**Comment by lifeofguenter** [comment]
Aaah.. thanks so much! Just do add some info to it:

1. Create App here: https://api.slack.com/apps/new
2. the callback URL should be set to `http://review-ninja-installation/auth/slack/callback` and **not** point to the slack-hooks app
