### ISSUE TITLE
oauth by org

### ISSUE THREAD

**Issue by lifeofguenter** [reviewninja/review.ninja#1070]
Currently anyone with a github account can use a self-hosted ReviewNinja installation? Would it be possible to only enable certain organisations?

**Comment by dfarr** [comment]
Hmmm, interesting dilemma. I do not believe there is a way to do this, short of providing a whitelist of users (which would require a code change).

One potential solution. We provide a "monkey patch" mechanism, here you can drop in code to monkey patch (or override) other code.

It *may* be possible to override our [github passport strategy](https://github.com/reviewninja/review.ninja/blob/master/src/server/passports/github.js). Here, in the [callback](https://github.com/reviewninja/review.ninja/blob/master/src/server/passports/github.js#L16), we add the user, no matter who the user is. If you were to monkey patch this, you could provide a more restrictive function that checks the user profile name against a whitelist.

**Comment by lifeofguenter** [comment]
Ah, I see. Thanks for the clarification! It might still be possible to get the users organisation via an API call after oauth?

**Comment by dfarr** [comment]
Yes, however this is not something we would implement in vanilla RN.

If you really need this feature I would suggest forking RN, or taking a look at the monkey patch route. One benefit of monkey patching is you will still be able to get the latest RN updates with a simple `git pull`.
