### ISSUE TITLE
Invite only lists organization owners

### ISSUE THREAD

**Issue by colinjoy** [reviewninja/review.ninja#1071]
I want to invite organization members to a reviewninja project, 
but only users with role "owner" are listed in the "team" tab.
Is there a way to invite regular members as well?

**Comment by dfarr** [comment]
I think I know what's happening here!

The [GH API](https://developer.github.com/v3/repos/collaborators/#list-collaborators) explains that if you are an organization owner, then all the org owners will *also* be returned in the request. Do you have many collaborators on your repo in question? It looks like we are not paginating our team view, therefore you will most likely only see the first 30 collaborators returned by GH.

**Comment by colinjoy** [comment]
the problem is not related to pagination.

The "Team" tab in ReviewNinja, that allows me to "Invite to ReviewNinja" is not showing team members (Github users that are members of the organization and have push access to the repository), but only showing the (3) Github users that are owners (admins) of the organization. Is this a configuration problem on our side, a bug, or is it expected that only admins may do code review?
