### ISSUE TITLE
Enterprise deploy should verify HOST is not default

### ISSUE THREAD

**Issue by osowskit** [reviewninja/review.ninja#1074]
I had overlooked setting the HOST parameter - mostly because of 🐔 🍳.  Thus was getting 503 errors when trying to set up webhooks because it was not pointing to my herokuapp.com instance.  Adding a webhook should detect if it is an enterprise environment and warn if HOST is pointing to the default ReviewNinja instance.

**Comment by dfarr** [comment]
ReviewNinja has been set up in order to work in a local environment *by default*. Hence, we set this value to `localhost` if one is not provided. Unfortunately I am not sure of a good way to do this, without removing the default and failing the bootstrap process if a `HOST` env variable is not provided.

Do you have any alternative suggestions?

**Comment by osowskit** [comment]
I was confused because most of the variables on the Heroku deploy are blank while others have default value.  I wouldn't expect reviewninja.herokuapp.com to work unless I've misunderstood what [`HOST`](https://github.com/reviewninja/review.ninja/blob/6ffce9f7d153b3e164c96cbd07d0c99e41df248a/app.json#L13-L16) should be set to.
<img width="473" alt="screen shot 2016-05-24 at 2 57 16 pm" src="https://cloud.githubusercontent.com/assets/768821/15521366/40960b86-21c0-11e6-87d0-9953509f3f55.png">

**Comment by dfarr** [comment]
You are right, this is a bit of a chicken/egg scenario. As it stands right now you would have to create the Heroku app, get random name (if this is what your desire), and then modify the `HOST` value to be your randomly generated name.

I think I will change the default to `<your-app-name>.herokuapp.com`. However, alternatively, you may want to set this to your own custom domain altogether. Hmmm, okay I will leave this blank and improve the help text 😄
