### ISSUE TITLE
Memory leaks on large pull requests?

### ISSUE THREAD

**Issue by killthrush** [reviewninja/review.ninja#1081]
We've enjoyed using ReviewNinja for our dev team and by and large it's worked out great.  On a lot of PRs though that aren't trivially small, we've noticed that ReviewNinja really bogs down, often causing multiple seconds of lag between keystrokes when entering comments for example.  Memory usage is through the roof too, some of our guys are reporting > 750MB in firefox.  Any idea what could be going on here?

**Comment by dfarr** [comment]
GH's API does not offer pagination on large PRs, please see [working with large commits](https://developer.github.com/v3/repos/commits/#compare-two-commits). We are currently exploring alternative solutions. 

There could also be a problem with the way we render diffs, that becomes apparent with large PRs. We will investigate this as well.

In the meantime, it is possible to use RN, completely in RN by leaving review flags (!resolve, !resolved, etc), and stars (!ninjastar, 👍, etc) in GH itself. Please see our [documentation](https://docs.review.ninja/codereview) for more information.

**Comment by dfarr** [comment]
As ReviewNinja is no longer in active development mode (see #1132), I will close this issue.
