### ISSUE TITLE
markdown rendering on the Review Status pane please

### ISSUE THREAD

**Issue by diwu1989** [reviewninja/review.ninja#1085]
![image](https://cloud.githubusercontent.com/assets/380950/16401856/af02fdbc-3c9c-11e6-91fe-eca4f6c11673.png)

**Comment by dfarr** [comment]
Odd.. we are rendering:
<img width="361" alt="screen shot 2016-06-28 at 1 43 31 pm" src="https://cloud.githubusercontent.com/assets/1387834/16431643/5de13b2a-3d36-11e6-86ec-945792411bc9.png">

Can you please double check?

**Comment by diwu1989** [comment]
this is on the Review Status pane, not the Conversation pane
![image](https://cloud.githubusercontent.com/assets/380950/16462041/5555a276-3de4-11e6-9c6d-fb6287dc1d2b.png)

**Comment by dfarr** [comment]
Oh this is the preview! (before you drill down into the thread, where the content *will* be rendered).

Hmmm, this is actually a little trickier than it appears. In the "preview" we are showing an abbreviated message (~100 characters I believe). If we render the comment into HTML, and then try to cut it off at 100 characters, we may end up with incomplete HTML.

I will have to find a new way to abbreviate the content, then we can safely do the render.

**Comment by diwu1989** [comment]
want to try https://www.npmjs.com/package/trim-html ?

**Comment by dfarr** [comment]
That'd work 👍 . This should be a quick fix, look for a PR in a few days.
