### ISSUE TITLE
Login issue on review.ninja

### ISSUE THREAD

**Issue by hostirosti** [reviewninja/review.ninja#1095]
When Signing in on https://app.review.ninja/ I get redirected to the Sign In page after Sign In. 
I tried it in incognito mode on Chrome and in Firefox, same behavior.

@dfarr can you help?

**Comment by hostirosti** [comment]
68450b8 could this change be related?

**Comment by dfarr** [comment]
I don't think thats related. In the past there was a problem with the login page being cached, can you try a hard refresh after logging in?

**Comment by hostirosti** [comment]
Tried a hard refresh, no change. Also tried with DevTools open and Cache disabled.

**Comment by hostirosti** [comment]
Even after revoking and re-granting access to ReviewNinja, I'm still seeing the Sign-In page only.

**Comment by dfarr** [comment]
Got it. The API for rendering markdown has changed, you probably have to agree to updated terms and conditions.

a94a925440dbb96c5d9f7b28a7a2ef197dad43aa

Fix is on the way!

**Comment by hostirosti** [comment]
ok, lmk when it's in :)

**Comment by dfarr** [comment]
Okay, give it another try!

**Comment by hostirosti** [comment]
Issue is fixed! Thank you a bunch @dfarr! Cheers :)
