### ISSUE TITLE
API for adding projects?

### ISSUE THREAD

**Issue by bootstraponline** [reviewninja/review.ninja#1098]
It looks like the only way to add projects is manually. It'd be nice to have an API.

**Comment by dfarr** [comment]
Added repos are simply "pinned" to the ReviewNinja homepage. To enable a RN via an API I would suggest using GH's own API.

https://developer.github.com/v3/repos/hooks/#create-a-hook

| name | config | events |
| ----- | ----- | ----- |
| web | {"url": "https://app.review.ninja/github/webhook", "content_type": "json"} | ['pull_request', 'pull_request_review_comment', 'issues', 'issue_comment', 'status'] |

**Comment by bootstraponline** [comment]
Cool. Thanks for the info.
