### ISSUE TITLE
Optionally Ignore author review

### ISSUE THREAD

**Issue by bootstraponline** [reviewninja/review.ninja#1100]
To enforce non-author review, the ninja star limit has to be set to 2. The author always has to +1 and then someone else has to +1.

On similar tools such as pullapprove.com, only one person has to +1 and the author review is ignored.

**Comment by matthewrice345** [comment]
We would greatly appreciate the option to ignore the authors +1

**Comment by jefferson-willian** [comment]
+1

**Comment by dfarr** [comment]
As ReviewNinja is no longer in active development mode (see #1132) I will close this issue.
