### ISSUE TITLE
!fix does not block merges & there's no -2

### ISSUE THREAD

**Issue by bootstraponline** [reviewninja/review.ninja#1101]
I need a way to -2 pull requests. `!fix` indicates a problem so it doesn't make sense that pull requests can be merged without outstanding problems.

**Comment by dfarr** [comment]
"-2" is something traditional of past code review tools, but does not really conform to our ReviewNinja spirit. If want to disallow merging PRs until the status is passed I would suggest looking into [protected branches](http://scn.sap.com/people/david.farr/blog/2015/10/12/enforceable-code-review-with-reviewninja).

**Comment by bootstraponline** [comment]
I have setup protected branches. Consider the following scenario:

- 2 devs +1. The review threshold of 2 is met.
- A security dev -2s to block the PR
- The PR is merged anyway. The merge button is impossible to disable after two +1s are granted.

**Comment by dfarr** [comment]
I understand, but still don't believe the code review is the proper place to block such a merge. Remember, as long as devs have push access, they can *always* merge via the command line.

I would recommend:
- fork/pull model so only "merge admins" can merge
- security dev closes the PR
- security dev raises another `!fix` comment

**Comment by bootstraponline** [comment]
> Remember, as long as devs have push access, they can always merge via the command line.

No, they can't.

> ! [remote rejected] master -> master (protected branch hook declined)

**Comment by dfarr** [comment]
I still stand by the recommendations. Will label as wontfix. 

If you want to create a PR for this feature, we will always strongly consider them.

**Comment by bootstraponline** [comment]
I moved to pullapprove.com.
