### ISSUE TITLE
Is it possible to have different policies for different branches?

### ISSUE THREAD

**Issue by MrWeeble** [reviewninja/review.ninja#1103]
This would be the use case: 
- merge to master requires at least one star from the "release management" team
- merge to develop requires at least one star from the "developers" team
- merge to any other branch requires at least one star from anyone

**Comment by dfarr** [comment]
We have avoided complex configurations due to unnecessary overhead of setting up ReviewNinja in the first place. If this is something many people are interested in, we could reconsider. Also, we are also never opposed to PRs 😛

**Comment by jot-hub** [comment]
Just wanted to register "interest" on this feature ;-)

**Comment by dfarr** [comment]
As ReviewNinja is no longer in active development mode (see #1132) I will close this issue.
