### ISSUE TITLE
CircleCI integration

### ISSUE THREAD

**Issue by teeSee** [reviewninja/review.ninja#1109]
Hi, 

I know we can use Jenkins to give review ninja star. Does review ninja support Circleci?
If yes, where can I find some documentation?

Best,

**Comment by dfarr** [comment]
@teeSee RN does not support any CI systems, these are supported on a platform (GitHub) level. The advantage of this approach is they all "talk" to the GitHub status API, and all have the ability to mark a PR as pending, failed, or successful. 

See - https://github.com/integrations
