### ISSUE TITLE
Should you be able to star your own review?

### ISSUE THREAD

**Issue by gregswift** [reviewninja/review.ninja#1110]
I just checked, and it appears that I can. Is that expected behavior or is it an issue?

**Comment by casche** [comment]
@gregswift that's by design. Some teams use it to say, "Hey, I think this is good, do you?"

If you don't want the start to count towards the review you can always increase the threshold by 1.

**Comment by casche** [comment]
@gregswift see #1100

**Comment by gregswift** [comment]
thanks @casche . Not sure how i missed that one when looking before posting.
