### ISSUE TITLE
Will ReviewNinja comment on public repos?

### ISSUE THREAD

**Issue by pchita1** [reviewninja/review.ninja#1112]
I have set up a new repo to integrate with ReviewNinja. The status check is working fine. However, I'm not seeing any auto comments in our Pull Requests from ReviewNinja. I enabled this setting during integration. The only possible reason I see is that this is a Private repo and not a Public one. Is that the reason why it's not working?

**Comment by dfarr** [comment]
@pchita1 you are correct. Please see #1029 for a quick fix to this issue.
