### ISSUE TITLE
server not starting with Mongo connection error

### ISSUE THREAD

**Issue by ezraroi** [reviewninja/review.ninja#1116]
{ [MongoError: not master and slaveOk=false]  
  name: 'MongoError',  
  message: 'not master and slaveOk=false',  
  ok: 0,  
  errmsg: 'not master and slaveOk=false',  
  code: 13435 }

**Comment by dfarr** [comment]
The one startup dependency ReviewNinja has is an open mongodb connection. This is specified with the `MONGODB` environment variable. Can you ensure this is pointing to a running mongo instance?

**Comment by ezraroi** [comment]
was a problem with our mongo cluster, thanks
