### ISSUE TITLE
Make single commits of PR visible in UI

### ISSUE THREAD

**Issue by unterstein** [reviewninja/review.ninja#1120]
Hi,

if I have 7 commits in my review, I can see this in the title line, but I do not have the possibility to select single commits to see them.

See:
<img width="644" alt="screenshot 2016-11-15 14 50 16" src="https://cloud.githubusercontent.com/assets/904420/20308166/f5ecebf6-ab42-11e6-89c2-ffd75052234a.png">

It would be great, if there were a new tab like `Diffs` or `Files` which includes a overview of this single commits.

It would be super great, if you could click on this commits to display not the whole PR but display only the difference between the selected commits.

**Comment by dfarr** [comment]
Please see #1132
