### ISSUE TITLE
Clicking on a comment links to commit when comment was created

### ISSUE THREAD

**Issue by unterstein** [reviewninja/review.ninja#1121]
Hi,

I have the following scenario:

PR with
`Commit 1`
`Comment 1` on a File on `Commit 1`
`Commit 2` fixing the stuff of `Comment 1`

When I now click on `Comment 1` on the side bar, the UI jumps to `Commit 1`. I would expect that the UI jumps to the latest commit, so that it is easy for me to check if my addressed topics are resolved now :).

I would keep the navigation between commits, like it is now:
<img width="232" alt="screenshot 2016-11-15 14 46 21" src="https://cloud.githubusercontent.com/assets/904420/20308633/203aa982-ab45-11e6-9651-cec20f4bc4f0.png">

Does it makes sense or maybe it is possible to make this configurable?

Thanks
Johannes

**Comment by dfarr** [comment]
Hi Johannes,

We have explored expanding the ability to drill down on specific commits comparisons. We made the decision to only show two commits in the "graph" to simplify what could easily become a complicated graph. As ReviewNinja is no longer in active development we will not be developing further features at this point. However, we will continue to consider PRs on a case by case basis.

Pro tip: If you know the sha of the commits you wish to compare you can change them in the URL to change your current comparison.

```
https://app.review.ninja/reviewninja/foo/pull/1/{{ commit 1 }}...{{ commit 2 }}
```
