### ISSUE TITLE
Make `$File:$Line`-Areas clickable in the review status overview

### ISSUE THREAD

**Issue by unterstein** [reviewninja/review.ninja#1123]
Hi,

when using the Review Status overview it would be super to have the area with `$hash $file:$line` clickable to focus this part in the ui.

E.g.:
Click on `afc67a5 QueueInfoConversion.scala:32` should trigger a scrolling and highlighting in the code area (left part).
<img width="326" alt="screenshot 2016-11-21 16 37 46" src="https://cloud.githubusercontent.com/assets/904420/20488876/ec0fcc46-b008-11e6-9a97-dce2caeb8c4d.png">

Cheers & Thanks
Johannes

**Comment by dfarr** [comment]
Hi Johannes,

Sorry for the delay in response. It is indeed possible to click on $file:$line to scroll to the line of code. However, there are some circumstances where a comment will be on a line of code that has been modified in a later commit, in this case it is not possible to scroll to the line of code as it does not exist in the code comparison.

Hope this helps,
David
