### ISSUE TITLE
Question: Would it be possible to hook in Github review process?

### ISSUE THREAD

**Issue by unterstein** [reviewninja/review.ninja#1124]
Hi,

would it be possible to use the new github review process to bundle comments from a single reviewer and submit all the comments as one review?
Background: In the current situation one e-mail per comment is sent, which could be grouped together to one email per review cycle.

Thanks
Johannes

**Comment by dfarr** [comment]
Hi Johannes,

With GitHub's introduction of pull request reviews we have decided to encourage migration from ReviewNinja to GitHub for code review. Please see #1132 for information on this migration. We have no plans to shutdown ReviewNinja, however, RN will no longer be in active development.

Regards,
David
