### ISSUE TITLE
"Load more" button not intuitive

### ISSUE THREAD

**Issue by MitchK** [reviewninja/review.ninja#1125]
Hi I find it not very obvious what "load more" tries to do. Overall I find the process of adding a new repository not very straight forward. 

Actual behavior:
I started off not finding my repository in the list. When I clicked "Load more", it still did not display my repository. I had to click on the button three times until it finally showed me my repository. Probably this is because I have a lot of repositories on my account

Expected behavior:
I want to click "load more" at least only once OR want to have an indication so I know need to click it a couple of more times to finally see my repository in the list. 

How about "syncing" like Travis does it?

**Comment by dfarr** [comment]
Correct, this was a tricky issue to get right due to the recursive nature of finding a repository. As ReviewNinja is no longer being actively developed we will leave adding a repo as it is currently implemented.
