### ISSUE TITLE
Migration path to GH Code Review

### ISSUE THREAD

**Issue by benboeser** [reviewninja/review.ninja#1127]
Hi dear ReviewNinja community,

many of you are aware that both GitHub.com and Github enterprise (v2.8+) now contain a built-in code review for pull requests.
The ReviewNinja team is glad to see this key feature now being part of the core platform.

At this point ReviewNinja is not going away. But you can imagine that many users may choose to use the platform functionality going forward. In an effort to support you with the transition, we are gathering pointers and information to make the transition easy.

Most ReviewNinja concepts translate into functionality in the platform offering. 
---
- Ninja stars -> Approve ... [more details](https://help.github.com/articles/approving-a-pull-request-with-required-reviews/)
- Review flags -> request changes ...[more details](https://help.github.com/articles/requesting-a-pull-request-review/)
- Enforce review -> setup protected branches (on repo settings) ...[more details](https://help.github.com/articles/about-required-reviews-for-pull-requests/)
- Team statistics (ninja stars) -> no equivalent
- Minimum number of ninja stars required  -> not supported (one is the threshold at this point)
- selected 'review team' -> not supported

Additional information
---
[Pull Request Reviews](https://help.github.com/articles/about-pull-request-reviews/)
[Review Changes](https://help.github.com/articles/reviewing-proposed-changes-in-a-pull-request/)

Beyond what ReviewNinja provided you can now also
---
- invite collaborators to review and ensure review by specific person

As mentioned above, you can still rely on our hosted offering in the coming months. Please don't expect major feature updates. We will continue to observe usage. A dramatic decrease in usage may support a decision to take ReviewNinja offline. We will inform all active users well ahead of time if that would be the case.

Thanks
ReviewNinja

**Comment by rwreynard** [comment]
Detailed info from GitHub: https://help.github.com/articles/about-pull-request-reviews/

**Comment by dfarr** [comment]
WIP:

# Migrating to GitHub pull request reviews

GitHub now offers functionality out-of-the-box enabling code reviews on pull requests. As ReviewNinja was always intended to be an "add-on" to GitHub, we encourage you to move to GitHub pull request reviews.

## Start a review

To start a review on a pull request, open the **Files changes** tab in GitHub, and leave comments on the code, selecting **Start a review** when finished. You can continue to leave multiple comments on the code. 

Once finished you can **Review changes**, select an option, and finally **Submit review**. Your options are as follows:

**Comment**: do not require a review, similar to leaving comments in ReviewNinja without a [review flag](https://docs.review.ninja/codereview/).

**Approve**: approve the pull request, equivalent to a [ninja star](https://docs.review.ninja/stars/).

**Request changes**: indicate that something needs to be resolved before merging, equivalent to leaving a [review flag](https://docs.review.ninja/codereview/) in ReviewNinja.

## Enforce a review

In settings, under branches, you can protect specific branches in your repository. Once enabled, you may require **pull request reviews** before merging. This reflects itself in the status of a pull request, similar to ReviewNinja, but with the added benefit that each review (and it's status) is individually reported.

## Review Team

Review Teams are not supported by pull request reviews. However, you may explicitly request a review from individuals on your team. These reviews are based on the honour system, an uncompleted review will not turn the merge button red. Additionally you cannot request a review from the pull request author.

## Merge Threshold

If you enforce reviews, GitHub's pull request reviews require only one approval.

**Comment by dfarr** [comment]
See #1132
