### ISSUE TITLE
Migration notice content

### ISSUE THREAD

**Issue by benboeser** [reviewninja/review.ninja#1131]

**Comment by dfarr** [comment]
ReviewNinja is no longer being actively developed. With GitHub's recent addition of [pull request reviews](https://help.github.com/articles/about-pull-request-reviews/) many of the benefits of code review offered by ReviewNinja are now available from GitHub itself.

ReviewNinja will continue to be available, we will provide advanced notice of any possible future changes. We encourage you to check out our [migration strategy](https://github.com/reviewninja/review.ninja/issues/1127) for advice and tips on moving from ReviewNinja code review to GitHub code review.

**Comment by dfarr** [comment]
We will need two versions:
- [ ] long version, for readme and www.review.ninja
- [ ] short version for application alert

**Comment by rwreynard** [comment]
ReviewNinja is no longer being actively developed. With GitHub's recent addition of [pull request reviews](https://help.github.com/articles/about-pull-request-reviews/), many of the benefits offered by ReviewNinja are now available in GitHub itself.

We have no plans to shut down ReviewNinja, so feel free to keep using it for now. We promise we'll provide ample notice if we decide to shut it down in the future. When you're ready to switch, check out our [migration guide](https://github.com/reviewninja/review.ninja/issues/1127) for advice and tips on moving from ReviewNinja to GitHub pull request reviews.

**Comment by rwreynard** [comment]
Short version

ReviewNinja is no only being actively developed. We recommend switching to GitHub's pull request reviews. See our [migration guide](https://github.com/reviewninja/review.ninja/issues/1127) for advice and tips.

**Comment by dfarr** [comment]
👍
