### ISSUE TITLE
Karma

### ISSUE THREAD

**Issue by dtornow** [reviewninja/review.ninja#340]
Manage karma points for collaborators:

- Level up if you star
- Level down if you merge a pull request without stars
- Level down if you merge a pull request with open issues

Thought's?

**Comment by casche** [comment]
Couple more ideas:

* Instead of Ninja Belt colors we could do 'Ninja Ranks', e.g. Neonate Ninja to Grand-Master Ninja ?
* What do you think of a 'Ninja Card' ?
  * The Ninja Card could contain your Karma/Ninja Stats
  * Shareable (to give you github street cred)

**Comment by benboeser** [comment]
I like the ranks (neonate to grand master). 
Shareable cards might also be a nice idea. Could draw other peoples attention to the app. 
Did you already settle on the first metrics? 
I wonder if sign-up and frequent 'sign back in' could also be on the list? 1 point every time you use the app and +5 points for meaningful actions like starring etc...?

Or can we maybe learn something from GitHubs 'streaks' and commit statistics?

**Comment by casche** [comment]
No, metrics are still open but I would prefer to start simple. We can experiment as we go to decide whether or not to include more advanced stats tracking such as streaks.

Some open questions I have
* Suggestions on the placement of the ninja rank
* I would prefer to have a "Leader Board" per repo to display the ranks for all contributors and perhaps have tool tips or some way of telling the user how the ranks are calculated. 
   * Placement of the leader board? Maybe in the pull request screen as a additional tab? So when you look at you see pull requests and there's a button for a leaderboard.

**Comment by casche** [comment]
Assuming Ninja Ranking is at the repository level:

1. Display 'Highest' rank achieved on landing page next to name/login
2. Display 'leader board' and rank/karma calculation tool tips at the repo page (See screens)
3. Display rank/karma in the star tooltip on the review page

@dtornow @dfarr @benboeser @rwreynard comments? :dancers: 

![screen shot 2015-02-02 at 4 07 42 pm](https://cloud.githubusercontent.com/assets/5832943/6008179/f0ac06d0-aaf5-11e4-93c4-c1c932cbc8b2.png)

![screen shot 2015-02-02 at 4 07 48 pm](https://cloud.githubusercontent.com/assets/5832943/6008183/f5c72cf8-aaf5-11e4-87c0-b1704054dbbc.png)

**Comment by dfarr** [comment]
The consensus is that **karma points** should exist on a repo level.

I believe we should rename this tab "Team", here we can display all collaborators for this repo. This would actually be a place to have our "invite" button.

@fabianschwarzfritz sound good?

**Comment by casche** [comment]
Comments? 

### Proposed Ranks

The indicating color is for aesthetic purposes on the tables and maybe the share card. 

Rank       | Indicating color
------------ | ------------------
Neonate  |   white	
Initiate    |  yellow
Apprentice  | orange
Journeyman  | green
Disciple    | blue
Expert      | violet
Veteran    | brown
Master      | red
Grandmaster | black

### Proposed Ninja Power
1. Comment/Close Comment (1) point
2. Add/Rmv Star (1) points
3. Login (2) point
4. Add Repo (3) points
5. Merge with no issues (3) points

Not sure yet how to properly scale the ranks..

**Comment by dfarr** [comment]
:+1: 

Add Repo, is an action each individual user must perform. It's actually more like "pin" repo to your list of repos. Still worth keeping as an action but maybe only worth one or two points.

It might also be cool to give BIG ninja points for our more "hidden" features:
- create ninjaignore file
- use "compare commit control" (not sure if technically feasible)

**Comment by fabianschwarzfritz** [comment]
I love the ranks and the ranking. @dfarr 's idea to give a good amount of points for the ```.ninjaignore``` file and the compare control is really nice :+1: . 

I would over think the ninja power for 'login', as there might be users that usually log out from Github after/using it. Given an every day use of the tool, the would then result in a good amount of points.  Another user might always be logged in to Github and would not get those points. Is logging in really worth it anything? 

However, we should support the "_I have a look at this tool_" - action and could give points for the first usage of ReviewNinja. This could be when the user is 'created' in our mongo instance and the user uses the ReviewNinja instance for the first time.

**Comment by benboeser** [comment]
:+1: on playing down the 'login' points and maybe give points for a sign-up.

**Comment by casche** [comment]
As discussed we switched from "karma" to more of a stats based record keeping. 

Stats Tracked:

1. Add ninja star
2. Remove ninja star
3. Add issue
4. Close issue
5. Add comment
6. Merge Pull Request

See #752 

![screen shot 2015-02-18 at 4 22 34 pm](https://cloud.githubusercontent.com/assets/5832943/6255927/5ed47f8e-b78a-11e4-93bb-7cb3612d8f29.png)

**Comment by fabianschwarzfritz** [comment]
In this first version, we just want to show 
 - Add ninja star,
 - Add issue
 - Merge Pull Request. 
This is done with 5a055d1. By reverting that commit, the other stats will be displayed again.

**Comment by benboeser** [comment]
@casche - let us know once we can close the team overview topic to get it shipped.

**Comment by casche** [comment]
@benboeser as of #771 it's now merged & functioning. I think this can be closed now.
