### ISSUE TITLE
Surface who has starred on PR list page

### ISSUE THREAD

**Issue by rwreynard** [reviewninja/review.ninja#371]

**Comment by fabianschwarzfritz** [comment]
Let's add a popover to the star icon and then display either a list of name or a list of images, if fetching the images does not take too long.

**Comment by rwreynard** [comment]
@fabianschwarzfritz sounds like a good idea! I'm also going to take a look at all the feedback and ideas for the pull request list view, and pull together a new version. I'm hoping I'll have time for this while I'm in Germany :)

**Comment by fabianschwarzfritz** [comment]
Okay, here is the result. Fetching the images takes a long time and you can see how they are rendered. We won't have that overhead. What we implemented now (already on prod) is a simple list of name in a tooltip when you hover over the ninja star.
