### ISSUE TITLE
Onboarding ux

### ISSUE THREAD

**Issue by rwreynard** [reviewninja/review.ninja#414]
Where should we add more info for key features for first use? E.g., MailChimp

**Comment by rwreynard** [comment]
![screen shot 2015-02-09 at 4 51 47 pm](https://cloud.githubusercontent.com/assets/4131576/6109584/1b6c69a6-b07c-11e4-81cb-15c5e708d49b.png)

@dfarr @fabianschwarzfritz  - thinking of alternative onboarding approaches: the best practice is to create an onboarding experience that uses the actual product itself (e.g., Basecamp creates a welcome project etc.). It is possible for us to do something like this, with a welcome repo that we use to show / describe all the features of ReviewNinja? Is it technically possible??

**Comment by dfarr** [comment]
We need to create a migration to ensure all onboarding prompts are not shown to pre-existing users.

**Comment by benboeser** [comment]
Status bar - 
Getting started to-do's:
1) Add ninja star 
2) Open issue
3) Merge pull request

Dim the list items that are successfully performed by the user

**Comment by benboeser** [comment]
Animate the status bar away with a nice message to the user once all steps are accomplished

**Comment by benboeser** [comment]
Once you have done all tasks, the bar updates with a different message and then doesn't show on the next login.
@rwreynard - will provide the text

**Comment by rwreynard** [comment]
*Hey, you’re done, nice job!* You’ve covered all the ReviewNinja basics, and we hope you enjoy using the tool! If you haven’t added a repo of your own yet, now’s a good time. *Add repo*.

**Comment by rwreynard** [comment]
Welcome copy for Add repo page:

**Hey username, welcome to ReviewNinja, we're glad you're here!**

To get started, add one of your own repositories, or let us show you around by adding a welcome repository to your GitHub account.

Button label: **Sure, add ReviewNinja welcome repo**

**Comment by rwreynard** [comment]
Welcome copy for Add repo page (shown first time only, dismissable):

**Hey username, welcome to ReviewNinja, we're glad you're here!**

To get started, add one of your own repositories, or let us show you around by adding a welcome repository to your GitHub account.

Button label: **Sure, add ReviewNinja welcome repo**


("add one of your own repositories" = link & same interaction as clicking "Add repo + icon")

**Comment by rwreynard** [comment]
Title of pull request (welcome repo): Review this to get started

**Comment by rwreynard** [comment]
**Thanks for letting us show you around!**

What you’re seeing here is a GitHub pull request with the code diffs showing by default. Feel free to look around.

Over on the right is a panel for issues (GitHub issues) that you can connect to a line of code, a few lines of code, or a whole pull request. 

**To open an issue about a line of code**
Click on a line number.
Enter a Title and Description and click **Submit**.
Note: you can also shift-click to select multiple lines, or click the plus icon (+) next to the Issues title to create a general issue.

Once you're satisfied that the issue has been addressed, you can go ahead and close it. 

**To close an issue**, click **Close issue**. If we’ve over-complicated that, let us know.


Another key feature, you need to know about, is Ninja stars. Ninja stars are how you communicate that a pull request is okay to merge. You can set, by repository, how many ninja stars you think pull requests should have before merging.

**To add a ninja star**, click the **ninja star** button.

When your pull request no longer has any open issues, and has received a sufficient number of ninja stars, it’s ready to merge!

**To merge the pull request**, click **Merge pull request**.

That’s it! These are the basic features of ReviewNinja to help you get started. We hope you enjoy using the tool, and please [let us know](https://github.com/reviewninja/review.ninja/issues/new) how we can make it better.

**Comment by rwreynard** [comment]
Welcome repo description: "Welcome repo for ReviewNinja to help you get started. Feel free to delete when you're done, we won't take it personally."

**Comment by gruiz17** [comment]
Everything done! All included in 1.2.0 :)
