### ISSUE TITLE
Unwanted PR comments

### ISSUE THREAD

**Issue by LeoColomb** [reviewninja/review.ninja#469]
First, thanks for your great service, it's still a room for improvements but has a very impressive start.

Nevertheless, I've an issue with, I've send you a mail, without answer, so I republish it here.

_My status_
* I'm a collaborator on https://github.com/YOURLS/YOURLS
* I've added some of my repositories, YOURLS included, to test this new and beautiful service, “just to see”
* Now every PR are commented without my permission or even the permission of the owner (repo deleted or not from my RN interface) (see https://github.com/review-ninja?tab=activity)

_Behavior blamed_
Enable an intrusive feature (PR comments) without the owner authorization, and don't allow the "adder" to disable this feature.

Thank you to disable this feature on this repo. 
:smiley_cat:

**Comment by dfarr** [comment]
I will close this issues, please follow #647
