### ISSUE TITLE
Assign PRs to 'mandatory' reviewer

### ISSUE THREAD

**Issue by benboeser** [reviewninja/review.ninja#531]

**Comment by mellybess** [comment]
Has this been implemented? If so, is there any documentation available?

**Comment by dfarr** [comment]
It is possible to assign a reviewer just below the "merge" button in ReviewNinja. (By default the button says "no assignee").

![screen shot 2015-10-26 at 11 17 13 am](https://cloud.githubusercontent.com/assets/1387834/10726463/32eea62a-7bd3-11e5-9c37-fde80ff68648.png)

This is the same as assigning a collaborator to a PR in GitHub. Will update the [documentation](https://docs.review.ninja) shortly :smile:

**Comment by mellybess** [comment]
:star2: Great thanks! And to clarify, there is no way to enforce that the assignee must be among the folks who give a ninja star in order for the review to be complete?

**Comment by dfarr** [comment]
No, our goal for ReviewNinja is to keep the stipulations minimal as to not get in people's way. Only the threshold (number of ninja stars), can be adjusted at this point in time.
