### ISSUE TITLE
Add .ninjaignore support

### ISSUE THREAD

**Issue by MitchK** [reviewninja/review.ninja#544]
Currently I'm working on a .NET solution with many projects and we have many XML files (.csproj for example), that change a lot during development cycles. Code review gets a little bit messy, but these files need to be checked in.

In a normal workflow we come to 80% XML files changes and 20% code changes. So code review is very painful for us.

It would be awesome to have something like a ```.ninjaignore``` where you can exclude file/directory patterns from code review, so you can focus on the actual code for code review.

**Comment by fabianschwarzfritz** [comment]
Idea: Optionally show excluded files in ninjafile.

**Comment by dfarr** [comment]
After much debate here our proposal for this feature.

**.ninjaignore in root of repo**

This will be exactly the same format as .gitignore file.

**only hide files in the diff**

*All* files will still be browsable in the file browser. The user will also be able to click on a prompt to "show ignored files".

**Comment by dtornow** [comment]
+1

**Comment by fabianschwarzfritz** [comment]
+1. I implemented a first version in #648.
The 'technical' implementation is done - now it's about how the hide/show functionality should look like from the ui side. 

@rwreynard let's sit together tomorrow and discuss how the 'ignored' files will be displayed. Here is how it currently look like: http://review-ninja-staging.cfapps.io/fabianschwarzfritz/Review.Ninja.Test/pull/170 
![screen shot 2015-01-14 at 2 58 20 pm](https://cloud.githubusercontent.com/assets/1759672/5749441/e13aff32-9bfd-11e4-8691-435a3bfc17e0.png)

**Comment by fabianschwarzfritz** [comment]
Better technical implementation: https://github.com/reviewninja/review.ninja/blob/master/src/server/wrap/pullRequests.js#L36 and use glob library to match files https://github.com/isaacs/node-glob . This requires no additional 'ninjaignore' service. Thanks @dfarr for that hint!

**Comment by fabianschwarzfritz** [comment]
- [ ] use glob implementation with https://github.com/isaacs/minimatch
- [ ] add info button 
- [ ] make ignore text darker
- [ ] fix height of accordeon heading because of info icon
