### ISSUE TITLE
Remove webhook warning/confirmation for repo admins

### ISSUE THREAD

**Issue by pmatias** [reviewninja/review.ninja#545]
When I try to remove a repository it says that it's removed. But then when I enter any Pull requests I see the review.ninja stuff still integrated, If I click on any related link, it will take me to the review.ninja site and I will see the repo again on the list.

Is there any other way tom completely remove the repository from review.ninja?

Thanks

**Comment by benboeser** [comment]
add to #797 ... explain how to delete ReviewNinja from a repository
Add a warning to make users aware of the behavior and link to documentation.

Alternate solution: if admin, delete webhook

**Comment by benboeser** [comment]
'do you also want to remove the webhook from your repo (this will impact all collaborators for that repo)?' ... @rwreynard

**Comment by benboeser** [comment]
animate a slide-down question area of awesomeness ...

**Comment by rwreynard** [comment]
Would you like to remove the webhook too? (heads up: this also disconnects collaborators)

Buttons: "Remove repo and webhook" "Just remove repo"

**Comment by dfarr** [comment]
This has been implemented! Look to see in the next release.

**Comment by benboeser** [comment]
:+1:

**Comment by dfarr** [comment]
This feature is now live! When you remove a repo you can also opt to remove the webhook _if_ you have admin privileges.
