### ISSUE TITLE
Threshold per repo

### ISSUE THREAD

**Issue by benboeser** [reviewninja/review.ninja#571]
Allow users to specify the minimum number of stars required to pass code review

**Comment by fabianschwarzfritz** [comment]
Set threshold per branch in settings page (by users with push access)

**Comment by dfarr** [comment]
Does a threshold *per branch* make sense? Or can it simply be repo wide?

**Comment by dtornow** [comment]
repo wide: it's a 'hint' it's not a 'control mechanism' anyways

**Comment by dfarr** [comment]
I would prefer repo wide too :smile:

**Comment by fabianschwarzfritz** [comment]
+1 for repo wide

**Comment by fabianschwarzfritz** [comment]
The functionality is implemented and it's now possible to set the threshold and enable/disable the automatic review ninja comments. The ui of the settings page is not done yet though. This is referenced in #578.
We should still think about some indication in the pull request page that the required numbers of stars in not reached yet.

**Comment by fabianschwarzfritz** [comment]
Hey @rwreynard, this is done as we discussed and merged into master, so it's visible on staging. Could you please review the changes on staging? I'll assign this to you and you can close it if you have more suggestions or see some ui-bugs.

**Comment by rwreynard** [comment]
![screen shot 2015-02-06 at 3 02 45 pm](https://cloud.githubusercontent.com/assets/4131576/6080442/a6082c70-ae11-11e4-91e3-0f11d03e09eb.png)

@fabianschwarzfritz sorry for the delay! I just checked this out on Staging (http://review-ninja-staging.cfapps.io/reviewninja/foo/pull/236) and wanted to ask you about a couple of things:

- the color of the number of reviewers (in this case "3") I thought was supposed to match the color of the button in the merge status area. The idea being if 3 is insufficient, then the status is pending and the merge button is orange, no?
- I think we talked about also having instructional text beneath the the ninja star button + reviewers number? In v. small font: "1 more ninja star needed" + the edit button to help explain what's going on and to provide another quick way to edit these settings.

**Comment by rwreynard** [comment]
Oh and is there any way for the ninja star to be centered both horizontally and vertically in the box?

**Comment by dfarr** [comment]
We need to tweak the font icon we generated to get this properly centered.

**Comment by rwreynard** [comment]
Ah, shall I open a separate issue for this? Who created the original? I can't remember :)

**Comment by dfarr** [comment]
Sure! I believe it was @withkiki

**Comment by fabianschwarzfritz** [comment]
@rwreynard I fixed the color of the number of stars and added a little text below the star button. Sorry, I was not precise with that hope the update fixes that. 

Sidenote: The button size is not accurate anymore since I centered the button, but that's addressed in #728
