### ISSUE TITLE
Update Marketing page

### ISSUE THREAD

**Issue by benboeser** [reviewninja/review.ninja#574]
Update Marketing page with latest features and stronger call to action.

Including:
link to Twitter page
new demo video (this time with background music)
user testimonials (if we can get some soon)

@withkiki @rwreynard

**Comment by fabianschwarzfritz** [comment]
Our ninja got rid of his christmas jacket and and she is now wearing her usual old clothing again.

**Comment by benboeser** [comment]
@dfarr - the demo video might be a fun one for Gabriel and @fabianschwarzfritz to collaborate on.
