### ISSUE TITLE
Setting page redesign

### ISSUE THREAD

**Issue by withkiki** [reviewninja/review.ninja#578]
Hey, Fabian, here is our new setting page. Thanks.

![screen shot 2014-12-02 at 10 19 57 am](https://cloud.githubusercontent.com/assets/7938229/5268281/ddb95a92-7a0c-11e4-9110-eb9b0adc6393.png)
![screen shot 2014-12-02 at 10 20 17 am](https://cloud.githubusercontent.com/assets/7938229/5268280/ddb9182a-7a0c-11e4-994f-b74bd4aaa2d8.png)

Icon reference:

pull request: https://octicons.github.com/icon/git-pull-request/
issue:https://octicons.github.com/icon/issue-opened/
star: see reviewninja 
check: https://octicons.github.com/icon/check/

**Comment by fabianschwarzfritz** [comment]
@rwreynard and I, we decided to go for a more descriptive settings page. This one is now on staging, let me know what both of you guys think and talk about it next week.

**Comment by fabianschwarzfritz** [comment]
@rwreynard here is a screenshot of the new checkboxes. They can also be seen on the current version on staging. Do we rather want a checkbox like this or do you prefer a checkbox in the "on-off-switch" style like on the iphone?
![screen shot 2015-01-27 at 07 52 28](https://cloud.githubusercontent.com/assets/1759672/5921573/d0883c44-a5f9-11e4-8feb-2add8a088920.png)

**Comment by fabianschwarzfritz** [comment]
New settings page is implemented

**Comment by dfarr** [comment]
I suggest looking into [UI Boostrap](http://angular-ui.github.io/bootstrap/#/popover)

**Comment by fabianschwarzfritz** [comment]
@rwreynard The tooltip is done as well. It shows up when entering -1 (an invalid value). I'll assign that one to you, please review the settings page (it's avaliable on staging) and close this one when you like it or give me feedback and suggestions. :)
