### ISSUE TITLE
Too many Permissions

### ISSUE THREAD

**Issue by hrj** [reviewninja/review.ninja#581]
```
This application will be able to read and write all public and private repo data. This includes the following:

Code
Issues
Pull requests
Wikis
Settings
Webhooks and services
Deploy keys
```
GitHub permissions are a little-coarse, but it looks like you are using the older auth model which is even more coarse.

**Comment by benboeser** [comment]
Can we be more upfront with our communication to give new users some more confidence?

**Comment by dfarr** [comment]
@hrj We have decided to introduce a "tiered" access model for ReviewNinja. We will ask only for **public** repo access until a point in time the user wishes to enable **private** access. Please refer to #380

**Comment by benboeser** [comment]
@hrj - check out the current implementation of http://review.ninja - it has a toggle feature for access now. Let us know what u think...

**Comment by hrj** [comment]
@benboeser Thanks for the heads up. But I am not sure what the flow is. After signing in with github, it immediately takes me to a "modify authorization" page. Where is the "toggle feature" that you mention?

By current implementation did you mean the code on master branch? I have not tried running reviewninja locally.

**Comment by benboeser** [comment]
@hrj seems not that easy to discover... it is the lock, that shows up in the repo view:

![screen shot 2015-02-06 at 2 13 42 pm](https://cloud.githubusercontent.com/assets/4432507/6088365/681849ba-ae0a-11e4-9d3a-3542fc10b83f.png)

Obviously not easy to discover. We will check how we can improve the 'discoverability'.

**Comment by withkiki** [comment]
Hey@hrj, We are improving the "discoverability" of the permission flow. More than the current lock button, new design is implementing, it will be more intuitive.
