### ISSUE TITLE
Better colors for the commit branch

### ISSUE THREAD

**Issue by MitchK** [reviewninja/review.ninja#597]
'Sup!

For me, when switching between the base commit and the commit where the issue was created, it is hard to distinguish what is now the current commit to compare.

Completely different colors maybe?

![issue2](https://cloud.githubusercontent.com/assets/2472064/5423478/b8a44fbc-82bf-11e4-8c17-9a18628cc33b.PNG)

Cheers

**Comment by fabianschwarzfritz** [comment]
We cut to release 1.2 today. This is left over from there. Let's do this asap.

**Comment by rwreynard** [comment]
![comparecontrolupdate](https://cloud.githubusercontent.com/assets/4131576/6065851/c6492ef2-ad68-11e4-93ab-03fe537d964a.png)

**Comment by rwreynard** [comment]
I've updated colors, and hopefully this'll be more effective at communicating which commits are being compared.

Circles: fill is the same as before: #abd8d7, stroke is now the darkest green: #126862
Stroke: only appears for selected commit comparison (no stroke for unselected) - hopefully both the color contrast and absence of stroke helps the distinction. The presence of the stroke shows what's in focus.
Arrow: was #666666, now #999999
Exclamation points: now darkest green: #126862

**Comment by fabianschwarzfritz** [comment]
Thanks Rachel :+1:
