### ISSUE TITLE
Clicking on the hyperlink in the Issues list does not scroll to the corresponding code line

### ISSUE THREAD

**Issue by PierreFritsch** [reviewninja/review.ninja#599]
In the "Review" column on the right, when I click on the hyperlink button, I would expect that the "diffs" column on the left scrolls to the position where the issue was created.
 
![screen shot 2014-12-18 at 17 30 49](https://cloud.githubusercontent.com/assets/10234267/5491715/a19f4e50-86db-11e4-910b-a75541fa6489.png)

**Comment by fabianschwarzfritz** [comment]
@PierreFritsch Cool, I hope you like the solution. I decided to make only the text and the icon on the detail view of the issue clickable and remove the tooltip on the issue list level. :smile:

**Comment by PierreFritsch** [comment]
@fabianschwarzfritz Thanks for working on this! I noticed the link appearance was adapted, however it doesn't work in my case :-(

Using Chrome 41.0 on Mac OS X Yosemite 10.10.2 on the following page:
https://review-ninja.mo.sap.corp/D049425/BugReport-ReviewNinja/pull/1/2 

When I click the link, something gets appended to the URL, but nothing happens on the left side. I also tried to select the commit base before, but then as well nothing happens.

**Comment by fabianschwarzfritz** [comment]
Thanks @PierreFritsch , I'll look into it!

**Comment by fabianschwarzfritz** [comment]
@PierreFritsch I answered your email, please feel free to come back to me if you've more questions :smile:.

After discussion with @rwreynard, more requirements for that:
 - scroll to line when clicking from list item -> detail view.
 - don't scroll when clicking on the issue on the code level directly as it might move the screen unexpected and the user is already on the code line with his mouse.
