### ISSUE TITLE
Line content in parse-diff

### ISSUE THREAD

**Issue by fabianschwarzfritz** [reviewninja/review.ninja#617]
The pull request http://review-ninja-staging.cfapps.io/reviewninja/foo/pull/199 introduces file changes. These changes are shown in the diff and this diff is depicted in the attached image. As shown there, the line with the diff information (_@@ -7,7 +7,4 @@ _) also shows part of the file content ( _A little "review" node js server for our little demo._). This content shouldn't be part of the line diff.

![screen shot 2015-01-06 at 4 07 01 pm](https://cloud.githubusercontent.com/assets/1759672/5638616/3aad0650-95be-11e4-8ef2-4b9739c56d73.png)

**Comment by fabianschwarzfritz** [comment]
As I just realized, the Github diff shows the same. That's depicted in the attached picture, as well.

![screen shot 2015-01-06 at 4 07 12 pm](https://cloud.githubusercontent.com/assets/1759672/5638728/1cee01b2-95c0-11e4-8e5b-6a8de90329b2.png)

**Comment by dfarr** [comment]
Looks good to me!
