### ISSUE TITLE
Link avatars to github

### ISSUE THREAD

**Issue by fabianschwarzfritz** [reviewninja/review.ninja#618]
We are already having a lot of links from ReviewNinja to Github, for example issues and pr's via #issuenumber. Let's also add link to the according github user profiles when clicking on the user image.

**Comment by dfarr** [comment]
Good idea!

**Comment by fabianschwarzfritz** [comment]
After a discussion with @rwreynard this is not the intende behavior, as the user does not expect to jump from review ninja to github with those links.
