### ISSUE TITLE
Fix scrolling when notification bar is present

### ISSUE THREAD

**Issue by fabianschwarzfritz** [reviewninja/review.ninja#625]
When the "add webhook" information on top of the screen is showing and I scroll down the page, the issue pane is not in the right position. 

To repoduce this issue: Go to staging (or any other deployed version where there is no webhook) and scroll down the page. The sidebar on the right with all the issues will "jump" when you scroll up and down.

The attached screenshot depicts this bug: 
![screen shot 2015-01-09 at 10 30 48 am](https://cloud.githubusercontent.com/assets/1759672/5684986/0193afca-97eb-11e4-84a1-f98a04b57039.png)

**Comment by dfarr** [comment]
This only happens when the "add webhook" information bar is shown. We set a "sticky" height to the height of the navbar, but when the navbar and alert bar is shown this height would have to be adjusted to navbar height + alert height.

**Comment by gruiz17** [comment]
I fixed it! [Here's my pull request](https://github.com/reviewninja/review.ninja/pull/741).
