### ISSUE TITLE
Could not merge from review.ninja but from github.com

### ISSUE THREAD

**Issue by fabianschwarzfritz** [reviewninja/review.ninja#630]
Given opening two pull requests with changes that do not affect each other. 

When I merge the first one an open the second pull request in review ninja, it says that I cannot merge the pull request. But I am still able to merge the pull request from github. 

@dfarr I think the ability to merge (if the merge button is 'enabled' or 'disable' should be the same for reviewninja and github. Is that right?

**Comment by dfarr** [comment]
I am going to close until we can duplicate this.
