### ISSUE TITLE
Search functionality in PR list

### ISSUE THREAD

**Issue by fabianschwarzfritz** [reviewninja/review.ninja#633]
Today I wanted to see a pull request that is already closed. I did not know the issue number but knew some keywords that describe what the pull request is about. 

For example projects with more pull request like angularjs, have a lot of pull requests (https://github.com/angular/angular.js/pulls) (currently 337). 

Currently the list of pull request does not provide any search functionality. A search functionality would enable me to find that pul request without knowing the issue number by heart.

**Comment by fabianschwarzfritz** [comment]
We could solve the issue of 'pagination' of pull requests by using the search functionality (https://developer.github.com/v3/search/#search-issues) that allows to search by 'pull request'. We could then get at least all title of the pull requests and provide a search functionality.

**Comment by dfarr** [comment]
:+1: with one caveat: is this a feature users want? @rwreynard what do you think?

**Comment by rwreynard** [comment]
No-one's specifically mentioned this idea, but folks are definitely looking for more/better ways to get to the "right" pull request (e.g., the one they need to review or re-review). I don't know that this would be a higher priority than other things we're hearing, but we can discuss.

**Comment by casche** [comment]
I propose we remove the 'author' sort and replace it with a search input that filters the list:

*Search*
![screen shot 2015-03-06 at 2 14 27 pm](https://cloud.githubusercontent.com/assets/5832943/6525869/5288900c-c40b-11e4-8770-f2a010f23e64.png)

*Search author 'dfarr'*
![screen shot 2015-03-06 at 2 14 43 pm](https://cloud.githubusercontent.com/assets/5832943/6525873/5b785bd4-c40b-11e4-960b-915d721e5173.png)

*Search 'feature'*
![screen shot 2015-03-06 at 2 17 11 pm](https://cloud.githubusercontent.com/assets/5832943/6525887/8774a40e-c40b-11e4-8308-60e5d397fe4a.png)
