### ISSUE TITLE
Mergeview status confusing

### ISSUE THREAD

**Issue by fabianschwarzfritz** [reviewninja/review.ninja#638]
Give there are two statuses on of them is in the "success" state and the other one is in the "errored" state. Then the "merge are" is red, as it is not recommended to merge. The text however shows "0 services failed" and the user has to switch to the status tab to see that one service did not fail but errored. Only after that he can know why it is not recommended to merge. 

A better text in this case would be "1 service errored"

![screen shot 2015-01-12 at 10 45 24 am](https://cloud.githubusercontent.com/assets/1759672/5708737/7911a660-9a48-11e4-9ffb-da49eb3261e4.png)

**Comment by dfarr** [comment]
This has to do with GitHub's [combined status api](https://developer.github.com/v3/repos/statuses/#get-the-combined-status-for-a-specific-ref)

"error" is not a valid *combined* state, I would imagine if a service has errored then the combined status will be set to failure.
