### ISSUE TITLE
Analytics for ReviewNinja

### ISSUE THREAD

**Issue by fabianschwarzfritz** [reviewninja/review.ninja#641]
We tried to start some analytics for ReviewNinja on https://github.com/reviewninja/review.ninja/tree/feature/keenio . How do we want to proceed with the analytics topic?

**Comment by dfarr** [comment]
I would like to define a snapshot of a PR, and whenever an event happens we save a new snapshot. That way it would be possible to show the transition of a PR over time.

**Snapshot**
- type of event
- time that event happened
- # of ninja stars
- # of closed issues
- # of open issues
- # of commits in PR
- state of PR (fail, pending, success)

**Events**
- new ninja star
- PR opened/closed/created
- issue opened/closed/created
- new commit added to PR

@dtornow thoughts?

**Comment by dtornow** [comment]
Triggered by the github callbacks?

- # number of XX *when*?
- # state *when*?

We can definitely log individual events to keen.io, but event blobs at a point in time is a tricky question

**Comment by rwreynard** [comment]
related to #340

**Comment by benboeser** [comment]
wait for legal feedback
