### ISSUE TITLE
Internal Server Error on Authorization callback

### ISSUE THREAD

**Issue by danishkhan** [reviewninja/review.ninja#642]
Error Message:
>failed to fetch user profile (Error: connect ECONNREFUSED)
    at /home/reviewninja/review.ninja/node_modules/passport-github/lib/passport-github/strategy.js:90:28
    at ClientRequest.<anonymous> (/home/reviewninja/review.ninja/node_modules/passport-github/node_modules/passport-oauth/node_modules/oauth/lib/oauth2.js:148:5)
    at ClientRequest.emit (events.js:95:17)
    at Socket.socketErrorListener (http.js:1552:9)
    at Socket.emit (events.js:95:17)
    at net.js:441:14
    at process._tickCallback (node.js:442:13)

For the callback URL I have: `https://review.octodemo.com/auth/github/callback`

In `.env` I have
>NODE_ENV=production
   PROTOCOL=https
   GITHUB_HOST=review.octodemo.com
   HOST_PORT=443
   GITHUB_PROTOCOL=https
   GITHUB_HOST=octodemo.com
   GITHUB_ENTERPRISEPATH=/api/v3
   PORT=5000

It seems like from the error it is a network issue, but I can't figure out if there is a port that I need open that isn't or if there is some other issue.

**Comment by fabianschwarzfritz** [comment]
Hi Danish,

First of all, just for your information, you're setting GITHUB_HOST twice in your .env configuration.

So here is what helps: If you're connecting to github.com just use the defaults and do net set GITHUB_API_PATHPREFIX and use the defaults.

We only yesterday made changes to the configuration of the url, so here is what you do if you have the latest version of the master branch. You did configure GITHUB_HOST, but not GITHUB_API_HOST. If you want to connect to a github enterprise version, please set the GITHUB_API_HOST _and_ the GITHUB_API_PATHPREFIX to connect to the instance correctly.

Probably your configuration with both of these variable looks like this. Please make sure that the urls I am proposing here match the urls you actually have in your internal instance.
'''
export GITHUB_API_HOST=octodemo.com
export GITHUB_API_PATHPREFIX=/api/v3
'''

If you're having an older version of reviewninja, please configure GITHUB_API_HOST. Before #643 was merged, the configuration of the path was not possible.

Let me know if that helps. 

Bests,
Fabian

**Comment by danishkhan** [comment]
Sorry that was a mistype. The first `GITHUB_HOST` is actually just the `HOST`, which is `review.octodemo.com`

I did a `git pull` and then updated the `.env` with:

>export GITHUB_API_HOST=octodemo.com
export GITHUB_API_PATHPREFIX=/api/v3

I got the below error this time when I tried connecting Review Ninja with my GitHub Enterprise user.

>SyntaxError: Unexpected token <
    at Object.parse (native)
    at /home/reviewninja/review.ninja/node_modules/passport-github/lib/passport-github/strategy.js:93:23
    at passBackControl (/home/reviewninja/review.ninja/node_modules/passport-github/node_modules/passport-oauth/node_modules/oauth/lib/oauth2.js:126:9)
    at IncomingMessage.<anonymous> (/home/reviewninja/review.ninja/node_modules/passport-github/node_modules/passport-oauth/node_modules/oauth/lib/oauth2.js:143:7)
    at IncomingMessage.emit (events.js:117:20)
    at _stream_readable.js:944:16
    at process._tickCallback (node.js:442:13)

**Comment by fabianschwarzfritz** [comment]
Cool! So the example for GITHUB_API_HOST and the GITHUB_API_PATHPREFIX values I mentioned in my previous post in the example where just example values. You probably want to make sure to use the correct url for GITHUB_API_HOST, which is probably not 'octodemo.com'. For Github itself it's 'api.github.com' - and I do not know what it is the url to your api instance.

The unexpected token is probably the beginning of an <html tag that is fetched because of a wrong url. Let me know if you can find out the correct url of your api...

**Comment by danishkhan** [comment]
I did `curl -i https://octodemo.com/api/v3/` so that's the URL for the Enterprise API

>HTTP/1.1 403 Forbidden
Server: GitHub.com
Date: Wed, 14 Jan 2015 20:00:29 GMT
Content-Type: application/json; charset=utf-8
Content-Length: 130
Status: 403 Forbidden
X-GitHub-Media-Type: github.v3
X-XSS-Protection: 1; mode=block
X-Frame-Options: deny
Content-Security-Policy: default-src 'none'
Access-Control-Allow-Credentials: true
Access-Control-Expose-Headers: ETag, Link, X-GitHub-OTP, X-RateLimit-Limit, X-RateLimit-Remaining, X-RateLimit-Reset, X-OAuth-Scopes, X-Accepted-OAuth-Scopes, X-Poll-Interval
Access-Control-Allow-Origin: *
X-GitHub-Request-Id: 469716e5-ab9c-49a5-83f9-0c4cc67b2eb7
Strict-Transport-Security: max-age=31536000; includeSubdomains; preload
X-Content-Type-Options: nosniff

{
  "message": "Must authenticate to access this API.",
  "documentation_url": "https://developer.github.com/enterprise/2.0/v3"
}


Stil lget the error message in my previous comment though.

**Comment by dfarr** [comment]
We have been updating the config variables recently. The most recent commit on master should be stable now. Make sure to pull the latest and your ``.env`` file should look something like:
```
export GITHUB_PROTOCOL=https
export GITHUB_HOST= octodemo.com
export GITHUB_API_PATHPREFIX=/api/v3
export GITHUB_API_HOST=octodemo.com
```

Sorry for the inconvenience.

**Comment by danishkhan** [comment]
:metal: 

Updating did it! Thank you @dfarr & @fabianschwarzfritz for all your help.

**Comment by dfarr** [comment]
:sunglasses:

**Comment by fabianschwarzfritz** [comment]
(y)
