### ISSUE TITLE
Issue with github enterprise and node-github client

### ISSUE THREAD

**Issue by bbaugher** [reviewninja/review.ninja#644]
The [node-github client](https://github.com/reviewninja/node-github) that you guys use seems to have an odd issue where if we specify a `http` protocol it will still use port `443` ([seen here](https://github.com/reviewninja/node-github/blob/master/index.js#L659)). The gist is there is a constant for [port](https://github.com/reviewninja/node-github/blob/master/api/v3.0.0/routes.json#L8) and review.ninja relies on the fact it gave the client the protocol `http` to choose the correct port.

**Comment by fabianschwarzfritz** [comment]
This should be fixed with #645

**Comment by bbaugher** [comment]
Thanks this fixes my issue
