### ISSUE TITLE
Enterprise config not cleaned up

### ISSUE THREAD

**Issue by bbaugher** [reviewninja/review.ninja#646]
Looks like after some [re-naming of config](https://github.com/reviewninja/review.ninja/commit/8e2b8d6b98b3f3aeae29bebca6ea5f3badca8579) the enterprise config variable was removed but is still used [here](https://github.com/reviewninja/review.ninja/blob/master/src/server/services/url.js#L40) causing the app to fail to authenticate with my enterprise setup.

**Comment by dfarr** [comment]
Thank you!

**Comment by bbaugher** [comment]
Thanks this fixed my issue
