### ISSUE TITLE
Cannot open issue in new tab

### ISSUE THREAD

**Issue by fabianschwarzfritz** [reviewninja/review.ninja#650]
When I am at the list of pull request and I use command+click on my mac to open the pull request in a new tab it doesn't work.

**Comment by dfarr** [comment]
We need to put the link in an ``<a> </a>`` tag for this this to work :smile:

**Comment by fabianschwarzfritz** [comment]
+1, just logged this I did not have a look at it. Thankd though for your quick answer :p :D

**Comment by fabianschwarzfritz** [comment]
Can't get the <a> tag in between the table: https://github.com/reviewninja/review.ninja/blob/master/src/client/templates/repo.html#L49 . Any ideas @dfarr

**Comment by dfarr** [comment]
Is this truly a painpoint for people? Can we disregard?

**Comment by fabianschwarzfritz** [comment]
No really, it was just confusing for me. Let's not worry about it now...
