### ISSUE TITLE
Newline character

### ISSUE THREAD

**Issue by dfarr** [reviewninja/review.ninja#653]
Can we be sure that \n is always the newline character? Is there another method we can use to tokenize this file?

|commit|file reference|   |
|------|--------------|---|
|48f2e5d017084668d73251e61ee2e8343fca3bc6|[src/server/api/ninjaignore.js#L23](https://github.com/reviewninja/review.ninja/blob/48f2e5d017084668d73251e61ee2e8343fca3bc6/src/server/api/ninjaignore.js#L23)|[![#652](http://app.review.ninja/assets/images/icon-alt-36.png)](http://app.review.ninja/reviewninja/review.ninja/pull/652)|

**Comment by fabianschwarzfritz** [comment]
This http://stackoverflow.com/questions/454908/split-java-string-by-new-line helps. I'll implement it that way. Thanks David :)
