### ISSUE TITLE
associate multiple (disconnected) lines to the same issue

### ISSUE THREAD

**Issue by benboeser** [reviewninja/review.ninja#654]
A few interviewees would like to be able to associate multiple (disconnected) lines to the same issue.

**Comment by dfarr** [comment]
I would suggest that we not enable this as we would no longer be able to map our highlighted lines to GitHub as we currently can. For example: https://github.com/reviewninja/review.ninja/blob/master/src/server/app.js#L25-L28

**Comment by benboeser** [comment]
Won't fix?
