### ISSUE TITLE
see statuses of “0” on the pull request list

### ISSUE THREAD

**Issue by benboeser** [reviewninja/review.ninja#658]
Another would like to see statuses of “0” on the pull request list view to help communicate functionality. He also suggested displaying build status at this level.

**Comment by rwreynard** [comment]
This applies to open, closed issues, and ninja stars

**Comment by fabianschwarzfritz** [comment]
This will be done as part of #657.

**Comment by fabianschwarzfritz** [comment]
We cut to release 1.2 today. This is left over from there. Let's do this asap.
