### ISSUE TITLE
surface open pull requests

### ISSUE THREAD

**Issue by benboeser** [reviewninja/review.ninja#659]
with a lot of organization repositories, would like to surface open pull requests, stars and issues at the repository list level.

**Comment by gsecillano** [comment]
+1

**Comment by fabianschwarzfritz** [comment]
Fetching the aggregated information produces a lot of data because we have to fetch all pr's for all repos that are enable. Won't fix: The amount of data we are fetching is not appropriate. 
Ideas&solutions welcome!
