### ISSUE TITLE
show only PRs that I need to review

### ISSUE THREAD

**Issue by benboeser** [reviewninja/review.ninja#660]
One would like to only see the reviews she’s meant to review on the Pull Request list view, with an option to view all.

**Comment by dfarr** [comment]
PR can be assigned to an individual in GH, but this does not necessarily mean "needs to review" furthermore it can only be one user.

**Comment by bbaugher** [comment]
This is also something I would like to see. I imagine this could be all reviews which I have not given a ninja star to. Similarly could there be a view for all reviews across all 'active' repos? With the above functionality I have 1 place to go to see is there anything new for me to review.

**Comment by dfarr** [comment]
I see two feature requests here.

1) Pending PR (aka open PR I have not starred). I like this approach better than using the assignee functionality in GitHub.

2) Pending PR across all 'active' repos. I see this as analogous to GH notifications. You can either see them in the context of one repo or **all** repos. Definitely an idea worth exploring!

**Comment by dfarr** [comment]
1) We are going to surface who has starred PR on the PR list view level. The status of this may be tracked here: #371 

2) I have created another issue here: #683
