### ISSUE TITLE
Re-review notification

### ISSUE THREAD

**Issue by benboeser** [reviewninja/review.ninja#663]
One would like to be notified when all issues are fixed and it’s time to go in and re-review.

**Comment by dfarr** [comment]
We actually do send a notification when *all* issues are closed. Perhaps we could re-look at the wording of this email.

**Comment by fabianschwarzfritz** [comment]
Our current text is:
*All issues have been closed for reviewninja/reviewninja #xxx.*
I think it this text cannot be clearer? Does anyone have ideas how to further improve the text?

**Comment by dfarr** [comment]
Since we already send an email for 'all issues closed' I'm going to go ahead and close this.
