### ISSUE TITLE
add comments to code diffs (as in GitHub)

### ISSUE THREAD

**Issue by benboeser** [reviewninja/review.ninja#664]
One would like to be able to also add comments to code diffs (as in GitHub). To not have to create an issue.

**Comment by benboeser** [comment]
make it easily minimizable... toggle either inline or on the side...

**Comment by benboeser** [comment]
no mixing of commenting and creating an issue

**Comment by sebastianwoinar** [comment]
+1

Creating an issue for e.g. praising something isn't semantically correct.

**Comment by dfarr** [comment]
Review Comments are now live! See #897
