### ISSUE TITLE
Email template format

### ISSUE THREAD

**Issue by benboeser** [reviewninja/review.ninja#670]
Let's revisit our email notifications and see how we can improve.

- better footer
- nicer language

**Comment by fabianschwarzfritz** [comment]
The mail notifications now have: 
- A header with "ReviewNinja"
- A footer with the reviewninja image
- A footer text that says that this email is from ReviewNinja
- A link to the marketing page. 

Does anyone have more ideas that improve the email?

**Comment by dfarr** [comment]
Let's work with @rwreynard on this one

**Comment by rwreynard** [comment]
Related to #662
