### ISSUE TITLE
Add Review Ninja to Chrome Store

### ISSUE THREAD

**Issue by filipre** [reviewninja/review.ninja#685]
we had the discussion on slack so let's move it here:
Would it be usefull or damaging if we add a shortcut to the chrome web store?

**Pros:**
- wider audience to promote review ninja since the store acts as global collection of different tools. For some it is the first place to go.
- more feedback from user since the store provides some easy review/rate tools

**Cons:**
- people (developers/github user in particular) expect a chrome app and no website
- public "inappropriate" feedback / unhelpful comments

we should include "shortcut" in the name so this could prevent wrong expections.

or is there some useful and easy functionality which could be integrated into the extention which gives some actual benefits?

**Comment by benboeser** [comment]
@filipre - are we still doing this? If not, feel free to close

**Comment by benboeser** [comment]
@withkiki - can you please provide the banner...

**Comment by gruiz17** [comment]
Closing this issue because users would generally expect an actual Chrome app/extension rather than a link to a site, and there's not a whole lot we could actually do with an extension or an app.

**Comment by benboeser** [comment]
@withkiki - didn't you design a new label for the Chrome store... are we doing this or no?

**Comment by dfarr** [comment]
I feel chrome store is for extensions and browser apps, since ReviewNinja is neither I don't feel it's a good fit - it's just a glorified bookmark. @gruiz17 @dtornow what are your thoughts on this?

**Comment by curiowls** [comment]
could be a good thing for SEO. at least one more link led to review.ninja

**Comment by gruiz17** [comment]
Agreed with David - as I said above, users would generally expect a Chrome app or an extension when they go to the Chrome store. Just having a link could potentially lead to bad reviews/a negative rep.

Unless we could come up with a way to do either and actually add value to reviewninja, I don't think we should have it on the store.

**Comment by dtornow** [comment]
Agreed with @dfarr - if it's not a chrome app, don't advertise it in the chrome app store.

**Comment by rwreynard** [comment]
Thanks for weighing in and revisiting this @gruiz17 - if it's inappropriate we definitely shouldn't do it. Not at all worth the risk of getting a negative reputation.

**Comment by curiowls** [comment]
Not sure what is the general user expectation. Chrome store is not targeting to chrome extension only (thought user may end up understand it a different way). 

Just copy and paste Google's own definition here:

>What is the Chrome Web Store?

>The Chrome Web Store lets you publish apps and games—either free or paid—where Google Chrome >users can easily find them. Whenever Chrome users create a new window or tab, they see the apps >they've installed, along with a store icon that reminds them to find more apps.

>If you already have a web app, you can create a metadata file and then publish your app in the store >within minutes. **Or you can** create and publish an app that's specialized for Chrome, such as an >extension for Chrome or a web app that's been modified to be downloaded and run on the user's >computer.

**Comment by curiowls** [comment]
Chrome specific app is described in "or you can ..."

**Comment by curiowls** [comment]
so does Firefox Marketplace. I talked with some one who was in Mozilla when the project just started. They'd like to play big, instead a convenient store for its own.

This is their current rather short description:

>The Firefox Marketplace is an open and non-proprietary online marketplace for web apps.
