### ISSUE TITLE
Resizing obfuscates issue view

### ISSUE THREAD

**Issue by casche** [reviewninja/review.ninja#691]
![screen shot 2015-01-28 at 10 29 18 am](https://cloud.githubusercontent.com/assets/5832943/5939304/e27752f2-a6d8-11e4-9db6-29e5923d3a29.png)

commit 8a337d071f829e48a9b36d60670bbe5d1d42f76f
Merge: 628b1eb 0b29cc5
Author: Fabian Schwarz-Fritz <fabian@schwarz-fritz.de>
Date:   Tue Jan 27 11:34:44 2015 -0800

    Merge pull request #687 from reviewninja/feature/fixcolor

**Comment by casche** [comment]
Looks like it's happening around 1075px

**Comment by gruiz17** [comment]
I'm working on this.

**Comment by gruiz17** [comment]
[Link to branch](https://github.com/reviewninja/review.ninja/compare/gabe-1075px-css-fix?expand=1)

Alright, I fixed this up.

Before: 
![screen shot 2015-01-28 at 4 31 03 pm](https://cloud.githubusercontent.com/assets/2757082/5950171/90529224-a70b-11e4-9395-73d663b8b1cd.png)

After:
![screen shot 2015-01-28 at 4 30 49 pm](https://cloud.githubusercontent.com/assets/2757082/5950175/9d58f3a0-a70b-11e4-8d52-93d259a0bd58.png)

**Comment by dfarr** [comment]
:+1: the only thing we need to do differently is the ``width: 95%`` for the ``issues`` class. This is why the bottom border you see in the screenshots is not stretching the full width.

**Comment by gruiz17** [comment]
Weird, this didn't get closed on GitHub itself, even though we closed it on reviewninja.
