### ISSUE TITLE
Possible to remove this?

### ISSUE THREAD

**Issue by dfarr** [reviewninja/review.ninja#693]
Could we use a single middleware and use something like ``arg.fun + ':' + arg.obj`` as the keen event name?

|commit|file reference|pull request|   |
|------|--------------|------------|---|
|4d8ed2352ca0f3467139850faf70a17ddde2a94a|[src/server/app.js#L9](https://github.com/reviewninja/review.ninja/blob/4d8ed2352ca0f3467139850faf70a17ddde2a94a/src/server/app.js#L9)| #692 |[![#692](http://app.review.ninja/assets/images/icon-alt-36.png)](http://app.review.ninja/reviewninja/review.ninja/pull/692)|

**Comment by casche** [comment]
I don't see why not. These are always present?

**Comment by dfarr** [comment]
yep!
