### ISSUE TITLE
Need different approach

### ISSUE THREAD

**Issue by dfarr** [reviewninja/review.ninja#695]
This will cause the issues in the sidebar to not stretch the full width

|commit|file reference|pull request|   |
|------|--------------|------------|---|
|2f0672f13eabdd1d451e0ade40df23583eb47055|[src/client/assets/styles/app.scss#L9](https://github.com/reviewninja/review.ninja/blob/2f0672f13eabdd1d451e0ade40df23583eb47055/src/client/assets/styles/app.scss#L9)| #694 |[![#694](http://app.review.ninja/assets/images/icon-alt-36.png)](http://app.review.ninja/reviewninja/review.ninja/pull/694)|

**Comment by gruiz17** [comment]
done. :)
