### ISSUE TITLE
Enable reviewninja on https

### ISSUE THREAD

**Issue by dfarr** [reviewninja/review.ninja#696]
This will also fix our [websocket issues](http://docs.run.pivotal.io/release-notes/index.html).

**Comment by gruiz17** [comment]
I'll take a look at this.

**Comment by gruiz17** [comment]
The way Pivotal recommends HTTPS to be done is integration with CloudFlare, [as shown in these instructions](http://docs.run.pivotal.io/marketplace/integrations/cloudflare/). We need to get a pro plan for SSL, though.

**Comment by DavidTPate** [comment]
I think this project shows promise, but the fact that is doesn't even have support for HTTPS is just insane to me especially considering that it can be used for Private Projects. That means that any private projects that would use this tool will have to transfer what they are viewing on Github through Review Ninja in plaintext.

This is something that CloudFlare support quite easily, https://www.cloudflare.com/ssl

**Comment by dfarr** [comment]
Thanks @DavidTPate! We plan on switching to cloudfare soon, will keep this thread updated.

**Comment by DavidTPate** [comment]
Has there been any progress on this? I'd really love to use your product but it is just unacceptable to do so with everything being communicated in Plaintext especially considering that you guys proxy everything retrieved from Github via SSL through a Plaintext connection.

Do you need help getting this setup or something?

**Comment by dfarr** [comment]
This is now our top priority.

No help needed, cloud fare is pretty easy :smile: thanks for the feedback!

**Comment by DavidTPate** [comment]
Perfect, thanks for the updated.

**Comment by dfarr** [comment]
Cloudfare does not support for websockets if not on an enterprise plan. Will investigate an alternate solution.

**Comment by dfarr** [comment]
This is now live! All users will be prompted to "add a webhook" again as the old webhook will be on http.
