### ISSUE TITLE
Error logging

### ISSUE THREAD

**Issue by fabianschwarzfritz** [reviewninja/review.ninja#701]
We should add some logging functionality to review.ninja to have a better overview about what's happening on our production instance. We could deliver that together with #641

**Comment by dfarr** [comment]
In the past we explored [loggly](https://www.loggly.com/) and [rollbar](https://rollbar.com/). @gruiz17 maybe something you could explore?

**Comment by gruiz17** [comment]
After a bit of research and testing logging on login/logout, I've decided to use [Papertrail](https://papertrailapp.com/).

* Slack webhook integration, live feed, and alerting are all free.
* Interface is simple, you can add searches + alerts pretty painlessly.
* Automatically detects different systems - separates logs from production, logs from my Macbook, etc.

Question is what on the server should I attach logging to?

**Comment by gruiz17** [comment]
Alright, Papertrail is integrated.

https://github.com/reviewninja/review.ninja/commit/06e136a1f72098790cc702910a75ed1bc37f515d

**Comment by dfarr** [comment]
:+1:

**Comment by fabianschwarzfritz** [comment]
I am getting a lint error for https://github.com/reviewninja/review.ninja/blob/master/src/server/services/papertrail.js#L2  saying 
```2:0  warning  Expected an assignment or function call and instead saw an expression  no-unused-expressions```, that was not there before. 
@gruiz17  You can use ```grunt lint``` to run lint and see the warning yourself. Is it possible to fix that warning or are deliberately having that one?

**Comment by gruiz17** [comment]
fixed it ayyy

https://github.com/reviewninja/review.ninja/commit/d64c509e0f1671f5cb5716562369ec94bee3045f
