### ISSUE TITLE
check if no err

### ISSUE THREAD

**Issue by dfarr** [reviewninja/review.ninja#702]
``if(!err)``

|commit|file reference|pull request|   |
|------|--------------|------------|---|
|114300392035fed9e84793cf97db93dd0bffc116|[src/server/api/issue.js#L89](https://github.com/reviewninja/review.ninja/blob/114300392035fed9e84793cf97db93dd0bffc116/src/server/api/issue.js#L89)| #692 |[![#692](http://app.review.ninja/assets/images/icon-alt-36.png)](http://app.review.ninja/reviewninja/review.ninja/pull/692)|

**Comment by dfarr** [comment]
or maybe this does not need to be in the callback?

**Comment by casche** [comment]
hmm, yeah good point.

**Comment by casche** [comment]
changed
