### ISSUE TITLE
keen instead of keen.client

### ISSUE THREAD

**Issue by dfarr** [reviewninja/review.ninja#703]
Can we just say ``var keen = new Keen()``? This way instead of using ``keen.client.addEvent`` we can just say ``keen.addEvent``

|commit|file reference|pull request|   |
|------|--------------|------------|---|
|114300392035fed9e84793cf97db93dd0bffc116|[src/server/services/keenio.js#L4-L6](https://github.com/reviewninja/review.ninja/blob/114300392035fed9e84793cf97db93dd0bffc116/src/server/services/keenio.js#L4-L6)| #692 |[![#692](http://app.review.ninja/assets/images/icon-alt-36.png)](http://app.review.ninja/reviewninja/review.ninja/pull/692)|

**Comment by casche** [comment]
done
