### ISSUE TITLE
please remove console.log

### ISSUE THREAD

**Issue by dfarr** [reviewninja/review.ninja#713]
|commit|file reference|pull request|   |
|------|--------------|------------|---|
|aae738d1ddd4db6c024627797e37740932c555f5|[src/server/controller/user.js#L25](https://github.com/reviewninja/review.ninja/blob/aae738d1ddd4db6c024627797e37740932c555f5/src/server/controller/user.js#L25)| #712 |[![#712](http://app.review.ninja/assets/images/icon-alt-36.png)](http://app.review.ninja/reviewninja/review.ninja/pull/712)|

**Comment by gruiz17** [comment]
aight fixed
