### ISSUE TITLE
Display build status on Pull Request list view

### ISSUE THREAD

**Issue by rwreynard** [reviewninja/review.ninja#718]

**Comment by dfarr** [comment]
We cannot know this information. Many build systems will integrate with unique "contexts". For example travis uses "continuous-integration/travis" but other build systems will have a different context and we cannot which repos have which build systems.

**Comment by rwreynard** [comment]
Fair enough, but let's figure out if there's anything we can do to help users know which pull requests to bother reviewing (it comes up regularly that for many it's a waste of time looking at a pull request with a failed build).
