### ISSUE TITLE
More readable Legal Terms?

### ISSUE THREAD

**Issue by hrj** [reviewninja/review.ninja#726]
I just tried to give ReviewNinja a spin and was shown a wall of text under "Legal Terms". The width and height of the `div` is small and the text is grey colored. Apart from that, the text is legally obese.

### screenshot
![screenshot](http://i.imgur.com/3Z0aF2A.png)

Can this be made more readable?

Else, most users are just going to blindly accept it.

**Comment by dfarr** [comment]
We can definitely work on the style, unfortunately obesity is out of our jurisdiction :smile:

**Comment by dfarr** [comment]
Improved contrast :smile: 

![screen shot 2015-02-10 at 15 13 22](https://cloud.githubusercontent.com/assets/1387834/6138611/79a58f50-b137-11e4-859a-07486e1d6d3a.png)
