### ISSUE TITLE
Review Ninja Marketing

### ISSUE THREAD

**Issue by MitchK** [reviewninja/review.ninja#727]
Some ideas for Review Ninja marketing: 

**Goals**
Make Review.Ninja more popular, get more feedback to make Review.Ninja better

**Premise**
Delta of new features decreases, features are considered stable

**Analysis**

 * How do our existing users actually use Review.Ninja? How many are active? How many have left?
 * How many users/projects can we possibly attract? Get a feeling for numbers

**Strategy**

 * Do we actually want to grow? 
 * How can we keep users?
 * How do we want to manage our brand/product? 

**Evaluate Methods**

 * **Search Engine Optimization** - How many people we can get from search engines at all (how many actually search for code review tools)
 * **Automated person-to-person reminders** - Might be annoying, but many services nowadays use something like "Hey dude, I'm the CEO Bill Dermott from SAP, do you need help with Review.Ninja?"
 * **Public Toolathon** - Something like a big collaboration project over a week we could also announce on hacker news? "The mystical white page" :)
 * **Invite projects and people** - How about addressing repositories/users directly?
 * ...

Any thoughts/ideas from your side?

**Comment by dfarr** [comment]
We are currently in the process of enabling two services to get more of a handle on the analysis side. These will be keenio and papertrail. 

I would be nice to have a better idea of **releases** with nice write-ups including new features and bug fixes. Have you ever seen slacks new release messages? They are awesome and a good model. Currently when we release we create an orphan branch and force push to ``release``, this gives us a lot of flexibility for releases, it would be nice to explore a way to auto-increment the version when we do this. This could increase transparency into our development process.

**Comment by MitchK** [comment]
> I would be nice to have a better idea of releases with nice write-ups including new features and bug fixes. 

Great idea, but what I don't like about release write-ups is just the mass of text. You could perhaps categorize them like: "New cool stuff", "Bug fixes" and to make it more interactive and transparent, you could link issues or pull requests to those messages, so people even just contributing issues see: "Awesome, that was me!"

**Comment by MitchK** [comment]
https://github.com/reviewninja/review.ninja/issues/733

**Comment by MitchK** [comment]
https://github.com/reviewninja/review.ninja/issues/733

**Comment by MitchK** [comment]
https://github.com/reviewninja/review.ninja/issues/733
