### ISSUE TITLE
Re-create ninja star icon

### ISSUE THREAD

**Issue by rwreynard** [reviewninja/review.ninja#728]
At the moment the ninja star icon sits too high within the button (should be centered vertically & horizontally). It would be great to finally fix this as part of 1.3.

**Comment by withkiki** [comment]
![screen shot 2015-02-09 at 7 47 56 am](https://cloud.githubusercontent.com/assets/7938229/6109497/fc32b988-b02f-11e4-9f4d-d6a09757432f.png)

**Comment by fabianschwarzfritz** [comment]
The css adjustments I applied caused the ninja button to be larger. Now the two buttons (star and star number) don't have the same size anymore.
