### ISSUE TITLE
413 error being thrown when loading pull screen

### ISSUE THREAD

**Issue by lee-40square** [reviewninja/review.ninja#731]
Actually I'm also getting a 400 and a 422 but let's start the 413. :-)

![screen shot 2015-02-09 at 10 14 16 pm](https://cloud.githubusercontent.com/assets/683267/6122563/51c69aca-b0aa-11e4-9f7e-5725d2a7538c.png)

**Comment by dfarr** [comment]
422: This occurs when a milestone has not been created. This is intended behaviour as we lazily create the milestone only when you create the first issue.

Can you provide a console log of the 413 and the 404?

Thanks!
