### ISSUE TITLE
Unable to create an issue (endless busy indicator)

### ISSUE THREAD

**Issue by i810697** [reviewninja/review.ninja#732]
Using SAP corporate github and corporate review.ninja.  When reviewing a pull request on review.ninja, getting an infinite busy indicator when I hit "submit".

**Comment by dfarr** [comment]
Can you check what level of access you have to the project? In order to create an issue you need at least push level access. We recently pushed an update internally which removes the "issue create" button if the user does not have sufficient privileges.

**Comment by i810697** [comment]
Hmm  Here is our "owner's group"...

![image](https://cloud.githubusercontent.com/assets/10167851/6148161/09151152-b1cd-11e4-84ef-2fab8ea85be9.png)

I will try to revoke and re-add the application in our github.

**Comment by i810697** [comment]
Hmm  I revoked and re-added Review.Ninja (corporate) to our github project and I still get this issue:

![image](https://cloud.githubusercontent.com/assets/10167851/6148327/9351cac6-b1ce-11e4-881a-e0ecb894386a.png) 

If you want we can have a look at this together...

**Comment by benboeser** [comment]
@dfarr - is this because of the new permission levels? Maybe if @i810697 enables private repos and disables them again, it may help? I tried on the internal instance with a similar setup and it worked just fine. Strange.

@i810697 try clicking:
![privrepo](https://cloud.githubusercontent.com/assets/4432507/6160045/89e24580-b212-11e4-814d-45dac6e009f6.png)

**Comment by dfarr** [comment]
@benboeser unfortunately this will not be the solution, if this was a private repo it would not possible to navigate to it in the first place.

**Comment by benboeser** [comment]
@i810697 - can you check if this works now?

**Comment by i810697** [comment]
Works!  Thanks!
