### ISSUE TITLE
Newsletter for on-premise admins

### ISSUE THREAD

**Issue by benboeser** [reviewninja/review.ninja#742]
Let's create a channel to users who decide to install their own instances of ReviewNinja.
E.g: simple sign up for a dedicated newsletter.

use case: inform about updates, keep in the loop in case of migration requirements, etc

**Comment by dfarr** [comment]
We now have a way to sign up for an "enterprise" email list [here](https://enterprise.review.ninja). @benboeser perhaps we could do an email blast to our current list talking about enterprise and ask people to sign up to a secondary list for future information?

**Comment by rwreynard** [comment]
#1018
