### ISSUE TITLE
Possible to remove this?

### ISSUE THREAD

**Issue by dfarr** [reviewninja/review.ninja#753]
|commit|file reference|pull request|   |
|------|--------------|------------|---|
|bca07c2ac03890dd1f26b98e788662fd62e24e6d|[src/client/controller/repo.js#L65](https://github.com/reviewninja/review.ninja/blob/bca07c2ac03890dd1f26b98e788662fd62e24e6d/src/client/controller/repo.js#L65)| #752 |[![#752](http://app.review.ninja/assets/images/icon-alt-36.png)](http://app.review.ninja/reviewninja/review.ninja/pull/752)|

**Comment by fabianschwarzfritz** [comment]
Removed.

**Comment by casche** [comment]
Forgot that i left that there. Good find :+1:
