### ISSUE TITLE
Unable to add repository (where I am not a collaborator) on initial screen

### ISSUE THREAD

**Issue by ReneLaengert** [reviewninja/review.ninja#757]
Is it intended that I can only add repositories where I am a collaborator of?
![screen shot 2015-02-20 at 11 43 00](https://cloud.githubusercontent.com/assets/6905966/6308043/b424eb9c-b8f5-11e4-85be-157177ca1aef.png)

In the end it is at least possible to directly access it anyways:
e.g. http://app.review.ninja/angular/angular.js

**Comment by thojansen** [comment]
Maybe for this a _discover_ or _explore_ mode would be nice. I guess you do not really want to enable it, but just have a look at it. For repos not using the tool at all, you would also need some information.

**Comment by dtornow** [comment]
It is indeed the intended behavior: Although review ninja uses a light weight integration approach it does affect a repository e.g. by adding milestones, adding pull request comments, and setting the commit status. First review ninja will not work properly without collaborator access. Second even if review ninja worked properly you do not want *somebody else* to enable that behavior on *your* repository.

Github provides discover and explore, I don't think there is a need to duplicate this functionality. If repository owners wanted you to know that they review code with review ninja they may include a review ninja badge in the Readme

**Comment by ReneLaengert** [comment]
Alright then, so that fact should be made transparent somehow. The explaination line "Type username or organization to find a repository" implies for me that I can find any repositories just like in the GitHub search field...

**Comment by benboeser** [comment]
will implement once search API is official
