### ISSUE TITLE
Opening new tab when navigating from GitHub to ReviewNinja?

### ISSUE THREAD

**Issue by ReneLaengert** [reviewninja/review.ninja#759]
I found different behaviour in navigation from GitHub to ReviewNinja.

When clicking on the ninja itself a new tab is opened in the browser, but when clicking on the underlined "Details" link it opens in the same tab. Which way is preferred?

![screen shot 2015-02-20 at 15 29 24](https://cloud.githubusercontent.com/assets/6905966/6311376/bf77f0b8-b916-11e4-980f-293eaa48ec80.png)

**Comment by benboeser** [comment]
we don't have control over the way GitHub opens up tabs. It is consistent within ReviewNinja
