### ISSUE TITLE
Tab color update

### ISSUE THREAD

**Issue by benboeser** [reviewninja/review.ninja#763]

**Comment by fabianschwarzfritz** [comment]
TODO: Open/closed buttons in sidebar are now in wrong color!

**Comment by fabianschwarzfritz** [comment]
This is not because of #776, but because of the commit https://github.com/reviewninja/review.ninja/commit/bc0d8de7b20635511f64f27f49da8a7da58e6cf2 that is already on master. I proposed a solution via a scss _mixin_ in Pull Request #788 . @dfarr It works, but do you think that's a proper solution?

**Comment by fabianschwarzfritz** [comment]
I solved this one already :)
