### ISSUE TITLE
Marketing Page Implementation

### ISSUE THREAD

**Issue by benboeser** [reviewninja/review.ninja#766]
Apply new design

**Comment by curiowls** [comment]
The purpose of this style tile is to provide quick reference to style need when implement. It also works as as a quick reference if any new elements need to be added later.

Let me know if you think there is anything missing.

![styletile-v1](https://cloud.githubusercontent.com/assets/5951398/6461054/64d0638c-c151-11e4-88d1-f9874fabb55a.png)

**Comment by curiowls** [comment]
Media 768px and above

![marketingpagenew-bigscreen](https://cloud.githubusercontent.com/assets/5951398/6461292/3e0da334-c153-11e4-8135-9884b605c920.png)

**Comment by curiowls** [comment]
Content width is set according to the 12 column layout except the following content box. It is fix width for media 768px and above. This image show the look around 768px while the one above demonstrate the look around 1200px.

![marketingpagenew-tabletlanscape](https://cloud.githubusercontent.com/assets/5951398/6461497/4d7430b6-c155-11e4-8c28-e485493e4841.png)

**Comment by curiowls** [comment]
The look of top bar when screen is scrolled up.

![marketingpagenew-topnav](https://cloud.githubusercontent.com/assets/5951398/6461623/74a0e6d8-c156-11e4-9956-3a8581fe8c0a.png)

**Comment by curiowls** [comment]
media width 767 and below. 

The are several section that need specific styling to make it looks and works best for small screen. They are marked on this image.

![marketingpagenew-phone](https://cloud.githubusercontent.com/assets/5951398/6461747/bd397c24-c157-11e4-952f-f123068e60e4.png)

**Comment by dfarr** [comment]
@withkiki can I get an updated logo, the one in the images above?

**Comment by withkiki** [comment]
@dfarr    
ux.review.ninja file---- new marketing page ----images ------ logo
