### ISSUE TITLE
Default with ||

### ISSUE THREAD

**Issue by fabianschwarzfritz** [reviewninja/review.ninja#773]
This could be shrinked to 
```tokens[repo] = tokens[repo] || [];```
That's also the common way of doing for default values in JS, I think. What do you thinks?

|commit|file reference|pull request|   |
|------|--------------|------------|---|
|ce34ffbd79f0bf5132016392448e8d540cd55a68|[src/server/migrations/1.1.0.js#L24](https://github.com/reviewninja/review.ninja/blob/ce34ffbd79f0bf5132016392448e8d540cd55a68/src/server/migrations/1.1.0.js#L24)| #769 |[![#769](http://app.review.ninja/assets/images/icon-alt-36.png)](http://app.review.ninja/reviewninja/review.ninja/pull/769)|

**Comment by dfarr** [comment]
:+1: but since this is a one time migration I'm going to leave it
