### ISSUE TITLE
Invitation failed: type email

### ISSUE THREAD

**Issue by benboeser** [reviewninja/review.ninja#778]
allow user to enter a known email address, if invitation fails

**Comment by rwreynard** [comment]
#780

**Comment by fabianschwarzfritz** [comment]
After the test work again, I'll merge and we can see it on staging.

**Comment by fabianschwarzfritz** [comment]
![screen shot 2015-03-06 at 12 09 16 pm](https://cloud.githubusercontent.com/assets/1759672/6535416/bb41ec68-c3f9-11e4-9a1a-ec53b88a6367.png)

**Comment by fabianschwarzfritz** [comment]
Fixed with #808.
