### ISSUE TITLE
create issues tab pops open with insufficient permissions

### ISSUE THREAD

**Issue by dfarr** [reviewninja/review.ninja#789]
When we hide the "create issue button" we need to also disable the form from popping open when user selects a line number.

**Comment by fabianschwarzfritz** [comment]
I added a first permission check: When we click the line number now, no popup opens. The mouse hover over still changes to a link - that is something I will fix next week :+1:

**Comment by dfarr** [comment]
Let's leave the mouse hover, I think it still makes sense!
