### ISSUE TITLE
Safari Push Notifications

### ISSUE THREAD

**Issue by casche** [reviewninja/review.ninja#792]
What does everyone thing about adding Safari Push notifications for things like : 

1. New PR created
2. Star on one of your PRs
3. Issue on one of your PRs
4. Others?

For more info: https://developer.apple.com/videos/wwdc/2013/?id=614

Essentially we would have an options area where the user can configure the push notifications. Regardless of whether or not Review Ninja is opened in Safari, the user would receive Push Notifications on their desktop.

**Comment by casche** [comment]
Perhaps also for our enterprise customers who have no interest in Apple Safari Push notifications we could make this configurable: on/off from a platform perspective.

**Comment by dfarr** [comment]
I think this is a good idea but not worth pursuing right now. @dtornow @benboeser what do you guys think?

**Comment by thojansen** [comment]
I :heart: this idea. Initial sign up needs to be via safari and then any browser is supported for delivering push events on a mac. Could be a great alternative to mail notifications.

:+1:

**Comment by dfarr** [comment]
I will close this due to inactivity, we can reopen in the future if we want.
