### ISSUE TITLE
Activity reporting

### ISSUE THREAD

**Issue by benboeser** [reviewninja/review.ninja#795]
teams start asking to be able to report on topics like:

- frequency of code reviews per org
- reports per branch
- review comment quality (would require a rating feature per comment)
- .. more user research required to identify more info

**Comment by benboeser** [comment]
- % of pull requests ninja stars met (to answer: did we follow the 4 eye principle?)
- what orgs do a better job than others?

**Comment by dfarr** [comment]
State of PR on merge:
- ninja stars
- open issues
- closed issues
- who created PR
- who merged PR
