### ISSUE TITLE
Update Documentation Website

### ISSUE THREAD

**Issue by benboeser** [reviewninja/review.ninja#797]
- add latest features
- ensure consistency
- check language
- rethink structure

**Comment by benboeser** [comment]
@casche - are you a good writer? We will all pitch in for this one, later this week... But would be great if you could take a stab at some of the topics. The documentation repo is under: https://github.com/reviewninja/docs.review.ninja

Let me know.

**Comment by casche** [comment]
@benboeser No I'm a terrible writer, but that doesn't mean I cannot try. I'll take a look after #779

**Comment by casche** [comment]
Potential Structure:

1. Quickstart 
2. Github OAuth Scope
3. Working with Repositories
   * Searching & Adding
   * Removing
4. Identifying Pull Requests
  * List structure 
  * Open Vs Closed
  * Search 
5. Collaboration 
  * Team List
  * Invitations
6. Configuration Review Ninja
   * Thresholds
   * Notifications
7. Reviewing Code
   * Diffs
   * Issues
   * Merging & Ninja Stars 
   * Comments
8. Troubleshooting 
   * Missing web hooks ?
