### ISSUE TITLE
Display combined status on PR list view

### ISSUE THREAD

**Issue by benboeser** [reviewninja/review.ninja#798]

**Comment by benboeser** [comment]
maybe like GitHub displays combined status as a small circle

**Comment by fabianschwarzfritz** [comment]
I implemented the logic for that on branch ```feature/display-status```. Should I wait for a design proposal or just come up with something? @rwreynard @withkiki 
![screen shot 2015-03-06 at 8 15 09 pm](https://cloud.githubusercontent.com/assets/1759672/6540023/a7795c18-c43d-11e4-8990-91369ff5dbdb.png)

**Comment by fabianschwarzfritz** [comment]
Thanks @rwreynard. I'll implement the display of the status as github displays the status.

**Comment by fabianschwarzfritz** [comment]
Foudn bug in that implementation, reverted and will retry...

**Comment by fabianschwarzfritz** [comment]
Fixed bug in #823 .
