### ISSUE TITLE
Comments inline instead of on the right

### ISSUE THREAD

**Issue by lee-40square** [reviewninja/review.ninja#799]
The PR comments section along the right feels crowded. I think if the right side was used for navigation linking to the associated code section and the comments were inline in that section, it might have a better UI flow.

**Comment by benboeser** [comment]
Hi @lee-40square - this has been debated back and forth in the past. Let's experiment with this and see what feels better.

**Comment by lee-40square** [comment]
Sounds good. Rachel reached out to me as well so I guess we'll have a call. Great product and heading in the right direction!

Like I said though, I think the right sidebar is still necessary but as a navigation to the sections of code that have comment, IMHO.

Seems like a really fun project. :-)

**Comment by golubev** [comment]
I have the same feeling that the right column is not the best place for commenting. The main reason for me is that the textarea is too narrow for me, and comment editing is much less handy than in the original GitHub's PRs.

**Comment by dfarr** [comment]
Personally, I like the code off to the side as it does not impede in the code. However, GitHub solves this by allowing comments to be toggled on/off, which may be something we could steal :)

@rwreynard would be curious to get your thoughts?

**Comment by rwreynard** [comment]
@dfarr yes we've heard both: helpful to have comments "out of the way" & really unhelpful to have comments "out of the way"

we talked a while back about letting this be a developer's choice - display comments inline or pop them off to the side (or hide them altogether). I'm fine with GitHub's approach.

**Comment by bergvandenp** [comment]
@rwreynard I'm thinking about a sort of hybrid solution:

- add inline comments to a PR that appear on the right (or focus inputtext on the right to insert "inline" comment)
- be able to hide (or drag the width of) the right bar

The result be to be able to read the PR using the full width and be able to comment inline or in the conversation view"

I'm not a fan of per user settings.

**Comment by dfarr** [comment]
As ReviewNinja is no longer in active development mode (see #1132), I will close this issue.
