### ISSUE TITLE
Deleted User null

### ISSUE THREAD

**Issue by fabianschwarzfritz** [reviewninja/review.ninja#813]
When a Github user is deleted, the user property of a pull request of that user is null. This fails here https://github.com/reviewninja/review.ninja/blob/master/src/client/controller/repo.js#L27 .  With a ```TypeError: Cannot read property 'login' of null```. 

Also, the image link of that user is broken: 
![screen shot 2015-03-09 at 12 37 51 pm](https://cloud.githubusercontent.com/assets/1759672/6562811/28332718-c659-11e4-842e-3543d5833d3d.png) 

The user of this example is this github user is the creator of this Pull Request: https://github.com/reviewninja/foo/pull/284 .

**Comment by dfarr** [comment]
We should use a default avatar in this case, good catch!

**Comment by fabianschwarzfritz** [comment]
@dfarr I started to implement a solution. The _ghost_ user seems to be a good solution: https://github.com/ghost. It's the user that Github references to when there is not user and it exists in the gh:e as well as in the github.com version. When using Githubs api, the user is null. In this case we can fetch the _ghost_ user and enhance the json with that user.

 In the referenced commit ```06c0191```, I fetch the ghost user when the user of Githubs ```pullRequests:getAll``` is null. With this, the _ghost_ user is shown in the pull request list now.

However, the user is null not only for pull requests list, but also for the issues, single pull request and so on. (```pullReqeust:get```, ```issues:get```, ```issues:getComments```).

Getting the ghost user is in a different service, so that we can reuse it. The  _/wrap/_ directory could then enhance the json with the ghost user everywhere is it missing. What I don't like about this: We'd have to do that in every Github entity that references a (possibly delted) github user...

**Comment by dfarr** [comment]
@fabianschwarzfritz can we close this?
