### ISSUE TITLE
Change to just email?

### ISSUE THREAD

**Issue by dfarr** [reviewninja/review.ninja#819]
toemail looks like "toe mail" :)

|commit|file reference|pull request|   |
|------|--------------|------------|---|
|588d803a22e365da9b67acd29212c3d234e836f9|[src/client/controller/repo.js#L101](https://github.com/reviewninja/review.ninja/blob/588d803a22e365da9b67acd29212c3d234e836f9/src/client/controller/repo.js#L101)| #808 |[![#808](http://app.review.ninja/assets/images/icon-alt-36.png)](http://app.review.ninja/reviewninja/review.ninja/pull/808)|

**Comment by fabianschwarzfritz** [comment]
done
