### ISSUE TITLE
activate CLA assist for ReviewNinja

### ISSUE THREAD

**Issue by benboeser** [reviewninja/review.ninja#829]

**Comment by Saulis** [comment]
Does this issue imply on adding a feature for signing and checking a contribution license agreement? 

If so, what's the status?

**Comment by thojansen** [comment]
[cla assistant](https://github.com/cla-assistant/cla-assistant) is activated and will check that all incomming PRs are checked for signed CLAs. Note that this a separate service and integrates into ReviewNinja as any other service using the status API via the "Services" tab.

**Comment by Saulis** [comment]
Ah, I wasn't familiar with cla assistant before. This is excellent, thank you!
