### ISSUE TITLE
Separation production/dev

### ISSUE THREAD

**Issue by fabianschwarzfritz** [reviewninja/review.ninja#830]
So @gruiz17, you want to get the minified version of ```app.js``` (```app.min.js```) only to prod and the normal version of ```app.js``` only to dev?
Could we not simply use the info from the ```.env``` file there to differentiate both files?

|commit|file reference|pull request|   |
|------|--------------|------------|---|
|3360b712c3121480fb29d11119b1cb4abda5e2bf|[src/client/home.html#L103-L106](https://github.com/reviewninja/review.ninja/blob/3360b712c3121480fb29d11119b1cb4abda5e2bf/src/client/home.html#L103-L106)| #815 |[![#815](http://app.review.ninja/assets/images/icon-alt-36.png)](http://app.review.ninja/reviewninja/review.ninja/pull/815)|

**Comment by gruiz17** [comment]
yo

https://github.com/reviewninja/review.ninja/commit/a9d256bd30d5becacc8c7c09033549542682e0e7

-uglify now produces html file with single script tag
-so now if it's on production mode, server knows to use the html with this tag
