### ISSUE TITLE
Proposal: Open lines issues directly from the code

### ISSUE THREAD

**Issue by MitchK** [reviewninja/review.ninja#832]
Currently we do a lot of code refactoring for CI Connect. I usually do code review locally first and usually find a lot of lines I would like to discuss with my colleagues.

Right now, I add a TODO comment so I later can remember which line I would like to discuss with my colleagues. And here comes the problem: I can't remember all my TODO tags :confounded: 

I think of a feature that would make ReviewNinja much more Ninja-like. Create a line issue in ReviewNinja by creating source code comments.

I thought something like:
```
function doSomethingWith(obj) {
    obj.doSomething();
}
```
would result in:
```
function doSomethingWith(obj) {
    // @ninja Dude, do you even check for null??
    obj.doSomething();
}
```

I also thought about a little bit about the implementation:

 * On a new commit on a pull request, check all committed files for @ninja annotations
 * For each @ninja you find, create an issue for the **next** line
 * If you want to select multiple lines, use something like @ninja+2, where @ninja+1 would be the same as @ninja
 * Always re-create the issue as long as it is there

Cheers

**Comment by dfarr** [comment]
I am extremely hesitant to integrate RN **at the code level**, even if it is simply a comment. That being said I fully understand your angle.

@dtornow thoughts?

**Comment by fabianschwarzfritz** [comment]
Yep, same here, I am not concerned at all with some ```// TODO``` comments, but as soon as you integrate the ```@ninja``` annotation/comment, it interacts with ReviewNinja. This means necessarily that this annotation/comment is checked into the git history and therefore in the code. Are there other tools that do something similar?
It's fast and seemed a good idea in the first place, but when taking a close look I doubt it's good practice to have those things in code that is checked into version control. @dtornow Curious about your opinion!

**Comment by klaernie** [comment]
I would definitely like to see a feature like this. But I would propose to generally create issues similar to the line comments functionality. So if review ninja gets a pull request open issues for all TODOs that are newly introduced in this PR. This would keep it clean from ninja-specifics and would also be directly attached to the PR that introduces them.

**Comment by thojansen** [comment]
This would be a good use case for "bots" or "enhanced services" which can show information in line level. I would not auto-create issues here but just surface that information.

**Comment by klaernie** [comment]
Would it be an option, that review ninja  surfaces these code lines as issue suggestions? I would be happy to have them listed automatically and just click a materialize button for each one.

**Comment by dfarr** [comment]
Will close for now, can reopen in the future if this is something we wish to pursue.
