### ISSUE TITLE
Code review page Ninja Star now is an letter "a"

### ISSUE THREAD

**Issue by withkiki** [reviewninja/review.ninja#833]
@dfarr 
![screen shot 2015-03-15 at 10 58 36 pm](https://cloud.githubusercontent.com/assets/7938229/6661283/1b8f7c2e-cb67-11e4-88ed-1e0f7fd178c6.png)
 ?

**Comment by dfarr** [comment]
Can anyone duplicate? This will happen only if our ninja font fails to load.

**Comment by withkiki** [comment]
Now is normal, only happened once. - Jie

**Comment by dfarr** [comment]
I will close for now
