### ISSUE TITLE
New 'ReviewNinja badge'

### ISSUE THREAD

**Issue by benboeser** [reviewninja/review.ninja#834]
The ReviewNinja badge is currently not showing any information. Maybe we can show open PRs number and also revisit the design?

**Comment by withkiki** [comment]
We can have a team short discussion about what info that need & good to display, then redesign it.

Best,
Jie Xiong
User Experience & Visual Designer
Products and Innovation | SAP LABS
3410 Hillview Avenue Palo Alto CA 94304 USA  |  +1 603 286 0430

**Comment by gabel** [comment]
If you rework the badge, please consider using the http://shields.io standard and support svg Versions.

![ninja stars-132-38b3ac](https://cloud.githubusercontent.com/assets/242039/6960936/2544a398-d927-11e4-9de4-b81edef5c0da.png)

![pull requests-32-38b3ac](https://cloud.githubusercontent.com/assets/242039/6960953/487462d6-d927-11e4-940a-0373cebdf87e.png)

![merged with-confidence-38b3ac](https://cloud.githubusercontent.com/assets/242039/6961016/af10031a-d927-11e4-9d6b-108bdfde14fd.png)

**Comment by withkiki** [comment]
Thank you, Ben. I’ll take a look. See you tomorrow.- Best, Jie

**Comment by dfarr** [comment]
These are awesome! Thank you @gabel, I especially like the ninja stars badge :+1:

**Comment by withkiki** [comment]
Since most of people very like the simple "shields "style. We will go with this look.

![screen shot 2015-05-08 at 9 13 29 am](https://cloud.githubusercontent.com/assets/7938229/7540430/90776450-f562-11e4-92d2-2aca06171e70.png)
