### ISSUE TITLE
Proposal: Add split view

### ISSUE THREAD

**Issue by cmsolomon** [reviewninja/review.ninja#843]
I prefer the side by side diff view, as opposed to the combined view - I'm probably not alone.

**Comment by benboeser** [comment]
Hi @cmsolomon - thanks for raising this. The side by side topic did come up a couple of times in the past. We will work with our design team and see how this might be accommodated in the future.

**Comment by mihai-chiorean** [comment]
+1

**Comment by SeanDunford** [comment]
![I concur](http://s23.postimg.org/xq71aimiz/concurmeme.jpg)

**Comment by gruiz17** [comment]
![loki.gif](https://cloud.githubusercontent.com/assets/2757082/7600885/db903d9e-f8c4-11e4-8e13-b3e6465cd71d.gif)

**Comment by dfarr** [comment]
![success-gif](https://cloud.githubusercontent.com/assets/1387834/11673165/69da75f0-9dcb-11e5-9781-36aa73810a8a.gif)
