### ISSUE TITLE
define goals for Google Analytics 

### ISSUE THREAD

**Issue by curiowls** [reviewninja/review.ninja#856]
As I looking into Google Analytics, I think the first thing we need is to define our goals.

What do we want to do/understand?

Here are some general info I can think of:
Bounce rate,
Page views,
Time on site,
Time on page.

viewing rate for certain content, e.g. introduction video.
subscription rate

thoughts?

**Comment by rwreynard** [comment]
I think it would be helpful to distinguish between "website" analytics for our static marketing content, and also figure out what we can track and how to track meaningful metrics within our "single page applications"

For our marketing sites, I think the single most important metric will always be conversion rate. 

For our single page applications, I think we care about retention rate, and then % of our customers who invite others to use RN, that's probably one reliable measure of the tools perceived value. What else? Number of returns in a period would show how integral the tool is to a team's workflow.
