### ISSUE TITLE
Ninja star is not displaying

### ISSUE THREAD

**Issue by lee-40square** [reviewninja/review.ninja#866]
The Ninja star is not displaying.

![screen shot 2015-04-07 at 3 49 24 pm](https://cloud.githubusercontent.com/assets/683267/7034304/dee1fc1e-dd3d-11e4-8ead-f76cf9fea4fe.png)

**Comment by dfarr** [comment]
Thanks @lee-40square if you refresh your page this should go away, looking into permanent solutions currently.

**Comment by dfarr** [comment]
Haven't seen this in a while, will close for now and reopen if it reappears.
