### ISSUE TITLE
Pull Requests for Org instead of Repo

### ISSUE THREAD

**Issue by casche** [reviewninja/review.ninja#867]
I'm wondering who else falls into a similar situation....

We have one project that has many repo's. When there are multiple pull requests across repos it's a little tedious to have to go to each repo to view them. It would be helpful to be able to view Pull Requests by organization instead.

This would offer another capability not present in Github.

**Comment by casche** [comment]
Visually 'linking' PR across repos and organizations would be nice... imagine a 'merge-all' button that merges multiple pull requests across organizations.

**Comment by dfarr** [comment]
We should explore grouping repositories and/or surfacing more information on repo list page.

**Comment by dfarr** [comment]
Will close for now as not high priority.
