### ISSUE TITLE
Automatically close issues on ninja star

### ISSUE THREAD

**Issue by dfarr** [reviewninja/review.ninja#868]
When the author of one or multiple issues ninja stars a PR we could automatically close all issues he created.

Thoughts?

**Comment by dtornow** [comment]
+1 only the issues authored by the user who stars, correct?

**Comment by dfarr** [comment]
@dtornow yes, very important caveat

**Comment by withkiki** [comment]
+1, in design, will have a reminder/warning note before this user star it.

**Comment by dfarr** [comment]
Will offer review comment "flags" instead, see #897
