### ISSUE TITLE
Clicking a file link in issue does not scroll the diff

### ISSUE THREAD

**Issue by disordered** [reviewninja/review.ninja#870]
If issue was created on a code line, clicking the file link does nothing (I assume, it should scroll the diff to show it).
Tested on OS X 10.10.3 Chrome 42.0.2311.90 and Windows 7 Chrome 41.0.2272.101

**Comment by dfarr** [comment]
Could you please provide a link to the PR? Would like to investigate further. Currently "scroll to issue" works by clicking here:

![screen shot 2015-04-26 at 2 00 59 pm](https://cloud.githubusercontent.com/assets/1387834/7339237/b8aaa3c8-ec1c-11e4-9491-b209878f3231.png)

**Comment by disordered** [comment]
I have sent you an email to address listed on your profile.
