### ISSUE TITLE
Allow closing issue in pull request commit

### ISSUE THREAD

**Issue by disordered** [reviewninja/review.ninja#871]
Let's assume we have a pull request with some issues.
Requester then fixes some of the issues and pushes a commit (to said pull request).
If commit message contains "ninja-chop #" (or whatever you deem appropriate ninja action) in the commit message, then mentioned issue on review is closed with a link to commit diff.

**Comment by dfarr** [comment]
[This is actually already possible with GitHub](https://help.github.com/articles/closing-issues-via-commit-messages/)

So a message such as `close #123` where the `123`corresponds to the issue will close that issue.

**Comment by disordered** [comment]
Github actually closes the issue only when the commit is merged to main branch (see second paragraph of the documentation). This request is to be able to close issues that were created in the review of a pull request, while the pull request is still not merged. Issues that do not belong to the pull request, should not be closed, obviously.

**Comment by dfarr** [comment]
Good point! Thanks @disordered will add this as a feature request.

**Comment by dfarr** [comment]
We will alternatively provide this in review comments. Please see #897.
