### ISSUE TITLE
Is review.ninja able to auto-merge PRs if ninja stars are met?

### ISSUE THREAD

**Issue by else** [reviewninja/review.ninja#873]
Is it possible to let review ninja automatically merge PRs if the ninja star threshold is met?

Thanks for contributing to open-source.

**Comment by dfarr** [comment]
Hi Simon, this is not possible with ReviewNinja - is this a feature you would be interested in?

**Comment by dfarr** [comment]
I am hesitant to implement an "auto-merge" feature as this could triggered unintentionally.

**Comment by MitchK** [comment]
If done right from the UI/UX side, the risk could be mitigated. I think this could definitely add value on top of PRs.

This could be done context aware:
 * Warning: This ninja star will merge the pull request. Are you sure to merge? Options: withdraw star/just give star/merge it!
 * Warning: The pull request will be auto-merged once the following services ran through successful:  Service A, Service B, Service C
 * ...

**Comment by else** [comment]
:+1:

**Comment by thojansen** [comment]
What about a ":+1:" which also gives a ninja star. I think this will cause more trouble than it will help.

Also this could be done as a separate service (similar to the GitHub Auto-Deployment).
