### ISSUE TITLE
Show new activity in issues

### ISSUE THREAD

**Issue by disordered** [reviewninja/review.ninja#879]
Maybe I don't know where to look, but I can't figure out how to tell (besides scouring through emails) that there was new activity on issues since last visit. Suggestions:
- In issue list mark issues that received new comments, were closed, reopened, created
- In issue details view note whether issue was closed/reopened and mark all new comments

**Comment by dfarr** [comment]
GitHub has a handy notifications area. Try clicking the "inbox" icon in the header bar up top. Any issue that is linked to ReviewNinja will have a ninja icon you can click on to job to ReviewNinja.

**Comment by disordered** [comment]
Ah, haven't thought of that. However, I still think it is just a better version of "scouring through emails".
Something like this would not require the user to constantly switch context.
List view:
![list](https://cloud.githubusercontent.com/assets/5319649/7389785/c4779fe2-ee71-11e4-8eff-806286488535.png)
Issue view:
![details](https://cloud.githubusercontent.com/assets/5319649/7389789/c8ecd59c-ee71-11e4-8ffe-3f0aa442dfb4.png)

**Comment by dfarr** [comment]
Thanks @disordered I am labelling this as a feature request. We would need a strategy for how to know *what* a user has already seen in order to implement this, I think these are some very good suggestions!

**Comment by disordered** [comment]
I suppose you could use Github notification API. It seems you can get the notifications since specific time. It also seems, you can mark them as read, so you could sync it with Github notifications in "inbox".

See https://developer.github.com/v3/activity/notifications/

**Comment by withkiki** [comment]
:+1:

**Comment by dfarr** [comment]
Will close as we have moved away from Issues to "Review comments"

**Comment by disordered** [comment]
I think it still applies. Even the UI that I proposed is almost the same. Just replace "issue" with "comment" in my suggestion.
It is still very hard to see new activity in review. At least you can now track it via github notification inbox. However, opening a comment on review ninja still does not mark notification as read. On the other hand, viewing the same comment in github PR review, does.

I think this issue still applies, just the context is slightly different.

**Comment by dfarr** [comment]
As ReviewNinja is no longer in active development mode (see #1132), I will close this issue.
