### ISSUE TITLE
New orgs are not displayed

### ISSUE THREAD

**Issue by MitchK** [reviewninja/review.ninja#886]
I've just noticed that when I create a new organization, it was not displayed in ReviewNinja.

I think it is because of the latest GitHub updates where you explicitly need to enable the organization for ReviewNinja on GitHub.

Solution:
Go to your profile => Applications => ReviewNinja => Enable your org manually. Then ReviewNinja catches the org.

I don't think this really bad but may be confusing for people not knowing this. This is how Travis does it: 
![capture](https://cloud.githubusercontent.com/assets/2472064/7443079/7c8ce1a6-f132-11e4-9a84-79d87b6b7bf2.PNG)

**Comment by dfarr** [comment]
Yep, this has to do with GitHub's new org API. Good idea!

**Comment by dfarr** [comment]
In order to get the correct link we need to call [this api](https://developer.github.com/v3/oauth_authorizations/#check-an-authorization), which we would need to implement in node-github. See more [here](https://github.com/mikedeboer/node-github/issues/85).

**Comment by brntbeer** [comment]
Curious if this is still an issue. I had an issue similar to this lately, but it just took a little bit for the organization or repositories to even be shown. Still an issue?

**Comment by dfarr** [comment]
Yep, still an issue. If "Third-party application access policy" is enabled on an org, repos will not show up until approved.

**Comment by dfarr** [comment]
We can take some inspiration from Travis

![screen shot 2015-11-23 at 3 34 11 pm](https://cloud.githubusercontent.com/assets/1387834/11353450/16247afc-91f8-11e5-9c70-0f40a2191ef2.png)
