### ISSUE TITLE
Integration with Slack?

### ISSUE THREAD

**Issue by damianesteban** [reviewninja/review.ninja#887]
I'm loving Review Ninja so far, my only issue is that it doe have (official) Slack integration.  Are there any plans for this in the future?

**Comment by gruiz17** [comment]
Oooh, this sounds like it could be really awesome. Thanks for the idea! I'll get to work on this right away :)

**Comment by dfarr** [comment]
We have created a [slack integration repo](https://github.com/reviewninja/reviewninja-slack)! Very early stage but feel free to let us know what you're looking for @damianesteban

**Comment by damianesteban** [comment]
You guys are seriously amazing.

On Wednesday, May 6, 2015, David Farr <notifications@github.com> wrote:

> We have created a slack integration repo
> <https://github.com/reviewninja/reviewninja-slack>! Very early stage but
> feel free to let us know what you're looking for @damianesteban
> <https://github.com/damianesteban>
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/reviewninja/review.ninja/issues/887#issuecomment-99520706>
> .
>


-- 





[image: --]
Damian Esteban
[image: https://]about.me/DamianEsteban
<https://about.me/DamianEsteban?promo=email_sig>

**Comment by dfarr** [comment]
This has been implemented! Check out the new settings page to enable slack integration.
