### ISSUE TITLE
New way to "flag problems"

### ISSUE THREAD

**Issue by dfarr** [reviewninja/review.ninja#897]
We have gotten feedback from the community that creating **milestones** and **issues** in order to track problems with a pull request is too intrusive. 

I propose we take a route that focuses on two workflows GitHub already provides for reviewing a pull request.
- issue comments
- review comments

### Issue comments

Issue comments (in GitHub a pull request *is treated like* an issue) are the current de-facto code review mechanism. Any solution we provide in ReviewNinja should incorporate issue comments so as to support projects already using this workflow.

### Review comments

Review comments are comments tied to a unified diff position. These comments can be tracked over the lifecycle of a pull request, even when new commits are added or commits are squashed. 

**Comments in GitHub are hidden when the line content of the head commit no longer matches the content of the commit when the comment was created.**

I propose we add support for **flags** on review comments. If a review comment is flagged we will set the pull request as "failing" via the [Status API](https://developer.github.com/v3/repos/statuses/). Once all flagged comment threads are resolved and the pull request has reached the required number of ninja stars we will set the status to "successful".

Here is an example comment thread:
![screen shot 2015-05-18 at 4 33 45 pm](https://cloud.githubusercontent.com/assets/1387834/7692691/b860b95a-fd7b-11e4-96eb-b6adada66201.png)

By using "exclamation mark flags" we can support users who wish to continue using GitHub only. However, if a user decides to opt-in to ReviewNinja, we could offer a nicer user experience including:
- no hidden review comment threads in diffs
- showing the diff between the commit *when the review comment was created* and the current head commit (in the above example we would be able to see that the semi-colon was in fact inserted)
- buttons to automatically add flags (!fix), and resolve review threads
- etc.

### Commit comments

For ReviewNinja I suggest we do not support commit comments as these comments can easily be lost when new commits are added and/or squashed.

Please feel free to post your thoughts and suggestions about this proposal!

**Comment by dfarr** [comment]
### Potential flags

Flag a review comment thread:
- !fix
- !resolve

Resolve a review comment thread:
- !fixed
- !resolved
- !completed

**Comment by fwalch** [comment]
Sounds great! One thing that's missing for a full opt-in approach is a way to give (and take?) ninja stars via a flag in an issue comment. FWIW, at Neovim, we use "LGTM" (looks good to me) comments.

**Comment by dfarr** [comment]
Good suggestion! Currently a comment of +1 or :+1: will create a ninja star, this will only work on **Issue comments**, would make sense to also offer a flag and perhaps extend to review comments.

**Comment by casche** [comment]
For us we just need to make sure that the code has been reviewed by someone and ninja starred. And basically 'who has not reviewed'. So whether the issues are comments or GitHub issues will not adversely affect how we use RN.

Eliminating the # of issues created would be a general improvement :+1: Especially if this provides wide spread user adoption. :clap:

**Comment by gabel** [comment]
:+1: The change to comments instead of issues will fit better in our workflow.

**Comment by benboeser** [comment]
:+1:

**Comment by huangp** [comment]
Coming from https://github.com/reviewninja/review.ninja/issues/902#issuecomment-104805945

This proposal will work well with our current work flow (as we don't enable github issues). But what we use right now is to use github/markdown special checkbox syntax `- [ ]` to keep track of issues in pull request. There is a grease monkey script to collect and display all this checkboxes. If review ninja can provide similar feature (e.g. a central board to display all review issues) that will be great.

**Comment by seanf** [comment]
Just FYI, this is the greasemonkey script for github checkboxes which @huangp mentioned: http://userscripts-mirror.org/scripts/show/455500

**Comment by dfarr** [comment]
We have quietly made this feature live! :fireworks: 

Please check it out and feel free to give us feedback here, I will keep this issue open until we have updated our documentation and ironed out any potential bugs.

**Comment by fwalch** [comment]
Looks very nice! Quick question: is there a way to retract a ninja star with a GitHub comment (I know it's possible with a button on the ReviewNinja website)? If you retracted your star on ReviewNinja, it doesn't seem to be possible to re-add it with a GitHub comment, is this intentional?

**Comment by dfarr** [comment]
Currently there is no way to unstar directly in GitHub.

Proposal: :-1: and -1 removes a ninja star, would this work?

**Comment by casche** [comment]
@dfarr I think so. It makes sense because we have +1 & :+1:
