### ISSUE TITLE
Allow optional text selections to be stored along with issues / comments

### ISSUE THREAD

**Issue by sschuberth** [reviewninja/review.ninja#901]
It would be nice if comments / issues could be "attached" to a selection within a line. That way one could e.g. easily highlight the word in a line that should get a typo fixed.

Recent versions of Gerrit also have this feature, and the way it works is that you first use the mouse to select / highlight text in a line, and then click in the gutter of that line to add a comment. Basically, all that needs to be done is to store an optional selection range along with the comment, and let the web UI highlight that selection in the line if there is one. That's why I was putting the word "attached" in quotes in the first paragraph, because the issue / comment would still be attached to the line, but the line would get the text selection highlighted.

**Comment by dfarr** [comment]
ReviewNinja is deeply integrated with Github. Recently we switched to fully supporting review comments. With review comments, comments are made on lines of code and nothing else for simplicity. This association is core to ReviewNinja, and would require a very good reason to change, we also highly value this simplicity. 

I am marking this as "won't fix", if circumstances change in the future we can revisit this issue.
