### ISSUE TITLE
Can not create issue

### ISSUE THREAD

**Issue by huangp** [reviewninja/review.ninja#902]
First time user. See this as one example. http://app.review.ninja/zanata/zanata-server/pull/825

When I try to create a new issue, what I see is a bunch of not found in browser console:
```
WebSocket connection to 'ws://app.review.ninja/socket.io/?EIO=3&transport=websocket&sid=ICGREPGhNkxRfYppAACM' failed: Error during WebSocket handshake: Unexpected response code: 400
http://app.review.ninja/api/webhook/get Failed to load resource: the server responded with a status of 404 (Not Found)
angular.js:8495 POST http://app.review.ninja/api/issue/add 404 (Not Found)angular.js:8495 (anonymous function)angular.js:8291 sendReqangular.js:8025 serverRequestangular.js:11498 wrappedCallbackangular.js:11498 wrappedCallbackangular.js:11584 (anonymous function)angular.js:12608 Scope.$evalangular.js:12420 Scope.$digestangular.js:12712 Scope.$applyangular.js:18980 (anonymous function)jquery.js:4409 jQuery.event.dispatchjquery.js:4095 elemData.handle
angular.js:8495 POST http://app.review.ninja/api/github/wrap 403 (Forbidden)
angular.js:8495 POST http://app.review.ninja/api/webhook/get 404 (Not Found)
```

**Comment by dfarr** [comment]
Creating issues in ReviewNinja creates issues in ReviewNinja, please enable issues on [your repository](https://github.com/zanata/zanata-server).

Please also take a look at [this proposal](https://github.com/reviewninja/review.ninja/issues/897) that would change the manner in which "code comments" are made, it is likely we will implement soon.

**Comment by seanf** [comment]
Do you mean creating issues in ReviewNinja creates issues in *GitHub*?  

We don't use GitHub Issues because they don't integrate with our existing issue system (Bugzilla).  I wouldn't like to enable issues because it will probably lead to users creating issues which are never seen or addressed.

**Comment by dfarr** [comment]
Yes ReviewNinja currently creates issues in GitHub. 

Sounds like another reason in a growing number of reasons to implement the changes proposed in #897. Thanks! I'm going to go ahead and close this issue, please follow the progress in the other issue.
