### ISSUE TITLE
Green/Blue deployment including simple integration tests

### ISSUE THREAD

**Issue by MitchK** [reviewninja/review.ninja#910]
Hi,

I was notified in Slack by the new release - amazing work guys!
When ReviewNinja got redeployed, there was a 404 for 30-60 seconds. 

How about a green/blue deployment? Works awesome with Cloud Foundry: http://docs.pivotal.io/pivotalcf/devguide/deploy-apps/blue-green.html

Before doing the final switch you could also some simple integration tests. The simplest would be:

```
curl -fkIL http://app.review.ninja
```

which will return a non-zero code and make the Travis build fail if any other HTTP code than 2XX was returned.

**Comment by dfarr** [comment]
:+1: I think this is a must, but needs to be automated!

**Comment by dfarr** [comment]
Woooo! Will leave this issue open until we have blue/green deployment on production

To do before go-live:
- [ ] rename review-ninja to review-ninja-blue
- [ ] create review-ninja-green and set env variables
- [ ] rename review-ninja-staging-blue to review-ninja-staging
- [ ] delete review-ninja-staging-green
- [ ] disable blue/green deployment on staging
- [ ] enable blue/green deployment on production (`.travis.yml` and `.blue-green.sh`)

**Comment by MitchK** [comment]
Wunderbar :+1:
