### ISSUE TITLE
nodemon

### ISSUE THREAD

**Issue by MitchK** [reviewninja/review.ninja#913]
This works great for development. To also consider operations, I would propose to add a flag like ```NODEMON=true```.

Another idea would be to get rid of nodemon and use a tool like this: https://github.com/rvoicilas/inotify-tools/wiki

|commit|file reference|pull request|   |
|------|--------------|------------|---|
|5f0484210117adc1ea96bbd6ae1e7033e9ff2b55|[docker-compose.yml#L5](https://github.com/reviewninja/review.ninja/blob/5f0484210117adc1ea96bbd6ae1e7033e9ff2b55/docker-compose.yml#L5)| #911 |[![#911](http://app.review.ninja/assets/images/icon-alt-36.png)](http://app.review.ninja/reviewninja/review.ninja/pull/911)|

**Comment by dfarr** [comment]
docker-compose is suggested for development only right now.

We are hoping to offer another repo with a "productive" docker-compose setup soon!
