### ISSUE TITLE
Issues disapear on UI under special conditions

### ISSUE THREAD

**Issue by MitchK** [reviewninja/review.ninja#914]
How to reproduce:

 1. Create line issue by marking a line and save it
 2. Create another issue by clicking on a line, but don't save it. Hit cancel
 3. The previous issue disappeared on the UI, reloading the site helps.

**Comment by dfarr** [comment]
I can't reproduce this Mitch, any other ideas?

**Comment by MitchK** [comment]
Hm... odd. Can't reproduce now either. I'll reopen once I experience this issue again.
