### ISSUE TITLE
Say hi from Jie (Miss you all)

### ISSUE THREAD

**Issue by withkiki** [reviewninja/review.ninja#915]
Hello, the awesome hella sick ninja team,

This is Jie from Citrus lane, Just want to say hey to everyone! Today is my day one, so far so good, getting busy, already went through a big meeting. Hope you guys doing well in HanaHaus. Have a nice day!

Best,
Jie Xiong
UX Designer Citrus Lane
http://www.citruslane.com/
Email: jie.xiong@citruslane.com
Contact: 603-286-0430

**Comment by dfarr** [comment]
Jie we miss you, come back :cry:

**Comment by benboeser** [comment]
Hey Jie, njoy the new gig... make it awesome!

**Comment by withkiki** [comment]
Are you guys still in HanaHaus? Planning a visit next week.
