### ISSUE TITLE
Slack Integration env variables

### ISSUE THREAD

**Issue by ijunes** [reviewninja/review.ninja#916]
I am running a fork locally, and was curious how to get slack integration to work?

What are the SLACK_HOST SLACK_PORT and SLACK_PATH values supposed to be set as?

**Comment by gruiz17** [comment]
Good question! The `SLACK_PORT` and `SLACK_PATH` variables are mainly used for if you're trying to deploy an instance internally. Therefore, you have two options:

1) You could simply set `SLACK_HOST` to `slack.review.ninja` which is the instance we use for ReviewNinja right now.

2) If you wish to bring up [the slack bot we made](https://github.com/reviewninja/slack-hooks) locally as opposed to using our hosted slack bot, get that running first (. Then, set `SLACK_HOST` to whatever host you're running that on, `SLACK_PORT` to whatever port you're running it on, and `SLACK_PATH` to the path that the bot's running on if you wanted a path for it.

Hope this helps!

**Comment by ijunes** [comment]
Yep! Thanks for the info!
