### ISSUE TITLE
1000 user balloon drop

### ISSUE THREAD

**Issue by dfarr** [reviewninja/review.ninja#917]
- [x] inflate balloons
- [ ] build the drop bag
- [ ] fill up the drop bag
- [x] deploy to ceiling
- [x] drop @ 1000

**Comment by rwreynard** [comment]
:laughing:

**Comment by gruiz17** [comment]
did someone say [drop](https://soundcloud.com/brosafari/bro-safari-the-drop)

**Comment by rwreynard** [comment]
:+1: :laughing:

**Comment by withkiki** [comment]
Yeah!!!

**Comment by benboeser** [comment]
We decided for a more permanent solution than the drop. But it looks nice. I will mark this as closed... Yay to 1000!

**Comment by jyguyomarch** [comment]
:+1:
