### ISSUE TITLE
Add ability to remove stars (not just your own)

### ISSUE THREAD

**Issue by TechniPoet** [reviewninja/review.ninja#920]
I have been looking into using review ninja for my company however while we really want the star functionality, we run into the issue of reviewers staring the pull request but then another reviewer finds another issue that causes the code to change drastically. Since the code has changed drastically then the stars that are already given are moot and should be able to be cleared.

I ask that you either add the ability to remove all stars OR add a system that allows you to see where in the history the star was given so it's validity can be assessed.

Something similar to the latter proposal is implemented with https://reviewable.io
![capture](https://cloud.githubusercontent.com/assets/5553576/8484572/709178bc-20c6-11e5-9989-fded34458f75.PNG)

Above you can see where certain reviews were made in the commit history.

Thanks!

**Comment by dtornow** [comment]
That is a great idea! @benboeser @dfarr @gruiz17 I prefer option #2, what do you think?

**Comment by dfarr** [comment]
I agree #2. @TechniPoet ninja stars are assigned to **commits** so we already have all necessary information necessary to create such a chart. Currently, when a new commit is added all ninja stars are cleared.

**Comment by dfarr** [comment]
It sounds like you would like a way to clear the stars **immediately** before a commit is added, is this correct?

**Comment by TechniPoet** [comment]
I have not used your system too much so I did not realize that all ninja stars were cleared after a new commit. 

Just to be sure I understand correctly first:
* 2 ninja stars are given to the pull request.
* I make a new commit.
* No ninja stars exist on the pull request anymore and I need 2 more for this specific commit to merge?

**Comment by dfarr** [comment]
Exactly. Depending on your ninja star threshold you have set in your settings.

**Comment by czebrose** [comment]
Ideally, we'd like the option to display when people starred a pull request instead of clearing the stars on a new commit. We have a lot of commits that are just cleaning up code which should force  everyone to re-star. However if there's a major change to a pull request, we'd like to be able to reset the star count and make it easy for returning reviewers to see what has changed since they last starred the pull request.

**Comment by TechniPoet** [comment]
To avoid confusion, @czebrose and I work together, our requests are 1 and the same. :)

**Comment by dfarr** [comment]
:+1: Thanks for the suggestions! We are currently working on implementing #919, this will definitely be on our backlog after that!

**Comment by TechniPoet** [comment]
Awesome thanks! 

#919 was also going to be a request of ours, glad it is being addressed. 

If at some point an eta for this feature could be provided that would be great as we are probably going to hold off on using review ninja until this feature is provided.

Thanks again!

**Comment by dfarr** [comment]
We don't like the idea to "transfer" stars on behalf of others from one commit to a new commit. However, it would be good to surface which commits were starred, and enable the ability to compare these old commits to the most recent commit.

I will open up a new issue for this.

**Comment by dfarr** [comment]
Please #974
