### ISSUE TITLE
Is there a way to add multiple comments and "send" them together?

### ISSUE THREAD

**Issue by Thatkookooguy** [reviewninja/review.ninja#934]
When adding comments, each time I finish writing a comment it's already attached to the review.
I usually write comments and the later comments help me redefine some of the previous comments I added.

Is there a way to write all the comments you like and then "submit" them?

**Comment by dfarr** [comment]
Currently this is not possible, in GitHub it is possible to edit a review comment (a functionality we could also offer in ReviewNinja). Would this solve your problem?

**Comment by Thatkookooguy** [comment]
The github edit functionality doesn't help since it requires me to:
1. use reviewNinja on your site
2. each time I add a new comment I need to open github and change the previous comment I just added.

going back and forth between github and reviewNinja kinds of eliminates the comfort of using a specific tool for this task.

And about developing this kind of feature:
You can always wait until someone clicks a "finished" or "publish" button before sending all the comments to github and interact with the github API.

This is indeed possible since other tools who do code reviews for github are doing so.
