### ISSUE TITLE
Ability to get an email after a user adds his messages?

### ISSUE THREAD

**Issue by Thatkookooguy** [reviewninja/review.ninja#935]
Can't find in the documentation how to get notifications on new comments.

Is there an ability like that?
Can it be set to send the messages email as a bundle?

**Comment by dfarr** [comment]
Our documentation site needs updating as we just quietly pushed a major update (review comment #897).

For the time being you can subscribe to github notifications in order to receive notifications when comments are made (by default you only get notifications on @ mentions).

**Comment by dfarr** [comment]
Will close in favour of relying on GH notifications/emails, instead of RN email.
