### ISSUE TITLE
Comments on issues are not shown immediately

### ISSUE THREAD

**Issue by sebastianwoinar** [reviewninja/review.ninja#940]
The whole sidebar especially the comments do not seem quite reactive.

It happened to me a couple of times, that after I've created a comment, it vanishes in the sidebar. 
That gave me the impression that something was going wrong.

But it was only in creation and wasn't retrieved from github, yet.
After I've reloaded the page, the comment was shown.

**Comment by dfarr** [comment]
Thank you @sebastianwoinar we will investigate.

**Comment by dfarr** [comment]
Right now we append new comments when we receive websocket messages *in order to avoid duplication*. Alternatively, we should immediately append the new comment and avoid duplication by filtering by id's.

**Comment by huit-tvachon** [comment]
This is also a big UI/UX problem for us.  If we create/update/etc anything in the sidebar, it seems like it fails to save, yet it clearly does not (after a refresh of the page)

**Comment by caplan** [comment]
yep, we'd love to start using reviewninja but this is a show stopper for us.

**Comment by huit-tvachon** [comment]
I actually bypassed nginx, tried another browser, nothing.  Its a bug seemingly in the code on Github, but not the code on review.ninja

**Comment by huit-tvachon** [comment]
@dfarr here is a direct comparison between the hosted version and the "release" branch (master acts similarly).  I have also tried 1.3.1 but it exhibits the same behavior.  I wanted to match as close as possible, the version app.review.ninja has running:

On app.review.ninja
1. On an existing review, change "!fix" to "!fixed"
2. This issues a "call" in angular.js:9866 and a getactions in angular.js:9866
3. Socket.IO refreshes the page using the polling transport
4. Several more calls and a "wrap" all are executed as the github status and service status are updated

On self-hosted (direct to node.js)
1. On an existing review, change "!fix" to "!fixed"
2. This issues a "call" in angular.js:9866 and a getactions in angular.js:9866

Socket.IO's callback is never invoked by getactions

**Comment by dfarr** [comment]
Thank you for all this information @huit-tvachon. We will prioritize fixing this. 

In the meantime, can you check out the "Webhooks and Services" tab in your github repo settings, find the one with your self-hosted URL, and let me know if these are sent/received successfully?

**Comment by huit-tvachon** [comment]
@dfarr you are spot on, it happens when the webhooks are failing back from Github.  I had a few repos which were ok, a the testing one was not. Maybe a troubeshooting article would be a good win here.

**Comment by dfarr** [comment]
Interesting, webhooks should be added *automatically*. 

I can imagine two scenarios, which may cause this to happen:
- webhook is never set (can happen if user who enables RN does not have **admin** access)
- webhook fails to reach RN

If it's the former case we should *fail gracefully*, the solution proposed in this issue would solve this. If it's the latter there may be an unrelated bug. Could you post a screenshot of the webhook responses that are failing?

Thanks!

**Comment by huit-tvachon** [comment]
It looks like it was the latter, or maybe the handshake wasn’t 100%.  I nuke them, so I don’t have screenshots to share

From: David Farr
Reply-To: "reviewninja/review.ninja"
Date: Tuesday, August 4, 2015 at 1:42 PM
To: "reviewninja/review.ninja"
Cc: Thomas Vachon
Subject: Re: [review.ninja] Comments on issues are not shown immediately (#940)


Interesting, webhooks should be added automatically.

I can imagine two scenarios, which may cause this to happen:

  *   webhook is never set (can happen if user who enables RN does not have admin access)
  *   webhook fails to reach RN

If it's the former case we should fail gracefully, the solution proposed in this issue would solve this. If it's the latter there may be an unrelated bug. Could you post a screenshot of the webhook responses that are failing?

Thanks!

**Comment by golubev** [comment]
I'm having the same issue on the app.review.ninja and I am getting `failed: Error during WebSocket handshake: Unexpected response code: 400` and other `400 (Bad Request)` errors in my Chromium.

**Comment by dfarr** [comment]
Just merged #959 which should take care of the delay. 

@golubev I am still investigating the cause of that error, I get it too, but it appears the websocket connection is still working regardless.

**Comment by golubev** [comment]
Thanks, @dfarr, for taking care about it!
