### ISSUE TITLE
Scroll to line

### ISSUE THREAD

**Issue by dfarr** [reviewninja/review.ninja#960]
When the user clicks on a review, if the line number is out of the viewport we should automatically scroll down to the correct file/line number.

**Comment by golubev** [comment]
+1
Just wanted to add the same issue.

**Comment by golubev** [comment]
I think that this should be done in a pair with #968 - to be able to navigate through a PR's code quickly.

**Comment by dfarr** [comment]
Implemented in a hidden manner - if you click on the review "label" you can scroll down to that issue (if it is not already in view). The review label is now in the bottom right of the list of review threads.

I will close this issue for now, in the future we may auto-scroll when you select a review thread, but I want to make sure we implement this right as taking control of user scrolling can be an intrusive action.

**Comment by golubev** [comment]
I agree with you @dfarr that autoscrolling may be a very annoing thing.

IMHO, it is better to let the user to control scrolling like it was said in the https://github.com/reviewninja/review.ninja/issues/1012.
