### ISSUE TITLE
Button to fold/unfold all files on Diffs tab when reviewing pull request

### ISSUE THREAD

**Issue by dmitry-nazarov** [reviewninja/review.ninja#962]

**Comment by dfarr** [comment]
:+1:

**Comment by dfarr** [comment]
In case you're not aware, you can currently do this individually. Also, you may be interested in the[ [.ninjaignore file](https://docs.review.ninja/quickstart/#ignoring-files), any matching file will be minimized by default.

**Comment by rwreynard** [comment]
Hi @aspectmkn8rd - would be super helpful for me to understand the context. Why would this be helpful for you? THANKS!!

**Comment by dfarr** [comment]
As ReviewNinja is no longer in active development mode (see #1132), I will close this issue.
