### ISSUE TITLE
"Expand" button for the unchanged code

### ISSUE THREAD

**Issue by golubev** [reviewninja/review.ninja#963]
It would be great to have a button that would expand unchanged code that is collapsed by default - like in the original GitHub's diff view. See a screenshot below.

![image](https://cloud.githubusercontent.com/assets/951364/9552526/77b1a3ba-4dc1-11e5-9d49-cebb1b66812f.png)

**Comment by dfarr** [comment]
:+1: this is on our backlog

**Comment by golubev** [comment]
OK, thanks @dfarr!

**Comment by golubev** [comment]
Sorry, @dfarr, but I have not seen any way to expand the collapsed code on the app.review.ninja - there is no link, or button there:

![image](https://cloud.githubusercontent.com/assets/951364/10735880/d188eb08-7c12-11e5-8e8b-63468ed45709.png)

**Comment by dfarr** [comment]
Slightly different in ReviewNinja, look for the + button in the top right corner

<img width="1036" alt="screen shot 2015-10-26 at 9 53 36 pm" src="https://cloud.githubusercontent.com/assets/1387834/10742226/55f6e8ea-7c2c-11e5-9701-049d5111f101.png">

**Comment by golubev** [comment]
OK! Thanks, @dfarr! That's interesting, because sometimes on GitHub I'm pressing "expand" several times to see a piece of code I need, whereas in ReviewNinja you expand the whole file at once.

But still: I think that for GitHub users this control is not obviuos. I don't know whether this is a problem ))

**Comment by dfarr** [comment]
It seems to be common practice that when a line is modified (deletion + addition), the *deletion* is shown before the *addition*.

GitHub, git
-
+

ReviewNinja (after expand)
-
+

**Comment by dfarr** [comment]
:+1:

**Comment by golubev** [comment]
Thanks, @dfarr! :smiley:
