### ISSUE TITLE
Losing a text typed when clicking on another line

### ISSUE THREAD

**Issue by golubev** [reviewninja/review.ninja#964]
It is a quite annoing peculiarity (can not call it a bug): when I have a long comment typed I am clicking another code line and the whole text is lost and I can not recover it.

Not only when you accidentally click other code line. E.g. you want to copy/paste some other line of code from the PR's diff, and when you highlight something in a single line of code (it is not reproduced e.g. when highlighting two lines of code) the line is being selected by the application and the text you typed is completely lost.

**Comment by dfarr** [comment]
Thanks for the suggestion, I like the idea of persisting what you have written.

**Comment by golubev** [comment]
Inline commenting (#799) simply solves this when you need to press a button to discard what you have typed (like it is done on the GitHub).

**Comment by dfarr** [comment]
:+1:

**Comment by dfarr** [comment]
Comments will now be maintained when you switch the line you are currently commenting on.

**Comment by golubev** [comment]
Thanks, @dfarr. Looks better to me :+1:
