### ISSUE TITLE
Missing autocomplete for mentions and emoji

### ISSUE THREAD

**Issue by golubev** [reviewninja/review.ninja#967]
It would be great to have an autocomplete for mentions and emoji - when you type `@` or `:`.

**Comment by dfarr** [comment]
:+1:

**Comment by dfarr** [comment]
We could also generate a dropdown when a user inputs an exclamation mark (!)

**Comment by golubev** [comment]
> We could also generate a dropdown when a user inputs an exclamation mark (!)

I was thinking about this. Seems to me, that it could be annoying. Especially, when a very emotional reviewer will place exclamation mark in the end of each sentence ))

**Comment by dfarr** [comment]
Good point, maybe a stipulation to only have a dropdown when the exclamation mark is at the beginning of a word would be good.

**Comment by golubev** [comment]
Nice idea, @dfarr. You can say it another way: autocomplete when the special symbol (e.g. `!`) is:

1. at the beginning of the line (`^` in regexp in the multi-line mode;)
2. after a space character (`\s` in regexp).

**Comment by dfarr** [comment]
Implemented!

**Comment by golubev** [comment]
:+1: 

Thanks, @dfarr!
