### ISSUE TITLE
Lines highlight colors and icons

### ISSUE THREAD

**Issue by golubev** [reviewninja/review.ninja#968]
It seems to me that current highlight color of the selected line lacks some contrast, so it is harder to find it quickly visually. I think that it must be more saturated than the color of a line with a review.

![image](https://cloud.githubusercontent.com/assets/951364/9637216/2bf12c30-51a8-11e5-860d-f3b0c5c738ba.png)

Also I think that when a line is selected and there is no review yet, there should not be the same icon, like on a line with review (both types of lines now have the same icon - exclamation mark in a circle).

**Comment by golubev** [comment]
Another point of this issue is about lines of the fixed review threads. I think that they should not be highlighted with a red-orange color, and should not have the exclamation mark icon. Why not highlilght them with a shade of green and put a checkmark icon?

**Comment by dfarr** [comment]
Thanks @golubev! @rwreynard would love to get your opinion here?

**Comment by rwreynard** [comment]
Hi @golubev - any chance you'd be available for a quick call / screen share so I can understand better all your points in the context of you using the tool?

**Comment by golubev** [comment]
Hi, @rwreynard! If you don't mind I can answer your questions here, in the text mode.

:smiley:

**Comment by rwreynard** [comment]
Hi @golubev - it'll be a first for me for this kind of discussion, but let's try it! :smile:

**Comment by rwreynard** [comment]
@golubev can you try to describe the sequence (flow) of what you're doing, and also why you're doing each step? This helps me understand how highlighting and icon selection fits into the bigger picture.  

E.g.,
1. I'm viewing someone else's pull request so that I can check the code is ok to merge
2. I notice a problem with particular line and click on a line number to select it
3. etc.

Also, if you can, describe what you *expect* to see at each step (highlighting & icons). I'm basically trying to see the interactions through your eyes :grinning: 

I'm really curious to see if this kind of discussion is possible in a GitHub issue!

**Comment by golubev** [comment]
@rwreynard, let's say I'm doing a review for my colleague's PR.

One of the main issues for me in the code reviewing tools is that I want to orient quickly in the critical comments I've left in the PR - comments that need to be fixed. Let's call them "PR-issues". For me it is important to:
- see how much PR-issues are there still open and the total number (e.g. `3 open, 10 total`, or `3/10 open`, etc.);
- see status icons at the code lines: which lines have issues, which of them have been resolved (_checkmark icon, green color_), which of them still have open issues (_exclamation mark icon, red color, must be quite contrast to attract my attention_);
- see those PR-issues as a separate list (like issues page on GitHub).

This is not a comprehensive list :smiley: 

Doing a PR review in GitHub I have a problem - there is not easy way to find out whether all my PR-issues are resolved and I can merge the PR.

The second problem is with outdated diffs - when someone does some changes my comment can become outdated and it will be hidden in the interface, but the problem I stated in the comment (PR-mini-issue) may still persist and the comment _must not be hidden_.

Each PR review for me looks like a separate local mini-issue tracker and I want to have a nice tool to manage those PR-issues.

__Some use cases__

1) when there is a fresh PR, not reviewed yet
![image](https://cloud.githubusercontent.com/assets/951364/10519163/3c13738e-736d-11e5-8122-1566a60d8f92.png)

When you click on a line I think that there is no need to place an icon on the left, because there are no comments there yet. Simply highlight the line - like in the GitHub. But better to highlight the full line:
![image](https://cloud.githubusercontent.com/assets/951364/10519243/9f68e00e-736d-11e5-92ce-190380476ea6.png)
In the ReviewNinja only a piece of a line on the left near the number is being highlighted (see the first screenshot). But this remark, IMHO, only refers to a _clicked code line_. In the case of a line with a PR-issue the length of a color highlight is OK.

The color of the line highlight _for the clicked line_ is OK to be like it is now.

2) a PR on the N-th iteration of review
![image](https://cloud.githubusercontent.com/assets/951364/10539948/573077bc-740c-11e5-9b04-164290ff85fe.png)

I want to leave such comments on this image (numbers below correspond to arrow numbers above):

1. line without a PR-issue - just a clicked line - IMHO, there should be no icon not to confuse reviewer or programmer, expand the highlight to the right, as I wrote above;
2. this is a line with all PR-issues resolved - there should be an icon saying to me "there was an issue, but everything is OK here now", and the color of the line highlight should also be "positive" (e.g. green), not too attractive. The length of the highlight in this case is OK and it should not be longer. If you would click on this line, IMHO, it should have two highlights: one of a _line with a PR-issue_ (green and as short as it is now) and another of a _clicked line_ that fills the rest of the line (on this image starting near the minus sign and spreading to the end of the line)
3. a line of a PR-issue that had not been resolved yet. Pretty much the same as with the point 2. Should differ in highlight of the line and the type of the icon. As I wrote above: there should be an icon saying "Look! Still having some problems here!", the highlight color should say the same (e.g.  red color). And the _color, must be quite contrast to attract my attention_.

Sorry if my comments will appear confused to you, I had to hurry while writing them.

P.S. on the GitHub they use green color for an opened issue, and the red for the closed one, and both have the exclamation mark, only the closed ones have a small checkmark sign :smiley: 

![image](https://cloud.githubusercontent.com/assets/951364/10540375/1ccc9e44-7410-11e5-8979-6514c09c2385.png)

**Comment by rwreynard** [comment]
Wow, thanks @golubev! Let me go through this in detail, and follow-up with any questions I have.

MUCH APPRECIATED!!!

**Comment by golubev** [comment]
OK, @rwreynard! I would answer your questions if you will have any.

**Comment by dfarr** [comment]
One thing to add. In the `diff` context I think red/green indicate deleted/inserted lines of code respectively. This is different from the issue context of open/closed. 

I like the idea of differentiating which lines have *resolved* comments and which are still *unresolved*, perhaps the best way to do this would by with a different icon (the one with a check mark) instead of a different colour which may be confusing in this context.

Thanks so much for all this info @golubev!

**Comment by golubev** [comment]
You are welcome, @dfarr!

**Comment by rwreynard** [comment]
Hi @golubev - I've mocked up some ideas that I think address your (excellent!) points, and that I think would help improve things quite a bit. 

First, full line highlighting (which I think we're doing now @dfarr?)

![highlight-1](https://cloud.githubusercontent.com/assets/4131576/10986513/9e9380a8-83df-11e5-83e0-0ab7bbc7c4d0.png)

**Comment by golubev** [comment]
Thanks a lot, @rwreynard! Nice job!

A resolved comment icon - looks really great! :+1: 

![image](https://cloud.githubusercontent.com/assets/951364/11028807/69295b16-86ca-11e5-9525-3e164408721e.png)

Have some other comments.

1) not resolved comment icon:

![image](https://cloud.githubusercontent.com/assets/951364/11028542/0ef6ff06-86c8-11e5-9869-aa6b8259ef29.png)

Looks "too bold" for me. Why not to do it like the unresolved one - draw outline only, without the checkmark, perhaps it can be the same color, as it is now.

I understand that you want to do it more contrast. I don't know the best way how to do it :smiley: Maybe you will find another nice solution.

2) not resolved comment line highlight

I think that the rest of the line starting with `+require('node-env-file')...`:

![image](https://cloud.githubusercontent.com/assets/951364/11028610/a5bfb7f2-86c8-11e5-8a13-497cf9ecc0f8.png)

should be the same color as a normal line highlight:

![image](https://cloud.githubusercontent.com/assets/951364/11028644/fbd9d42e-86c8-11e5-860d-c7be721f1f58.png)

Let's try to do it consisting of two colors: starting with orange "not resolved" color and continuing to the end with the sand color.

Because it is a more complicated case when a highlighted line can be of several colors: in some cases it can be sand-coloured, in other ones - orange. I think that the less things a programmer should keep in his brain (e.g. visual patterns of a highlighted line) - the more nice a coding process will be to him. Our job is too complicated to use complicated tools :smiley: 

Once a programmer got used to the one color of a line highight - I think we should not complicate this point for him :smiley: 

3) Not evident icon for me:

![image](https://cloud.githubusercontent.com/assets/951364/11028873/4b538688-86cb-11e5-869d-6d0fcbe0cff6.png)

I really don't know what it meens :smiley:

**Comment by rwreynard** [comment]
Thanks @golubev! 

The thinking behind making the unresolved comment icon solid is simply to provide more contrast when there are many resolved / unresolved icons in a diff. Happy to try outline only first - we have color + the checkmark to differentiate, I agree, this should be sufficient contrast :+1: 

I hear you on the highlighting: thought it might be easier to quickly distinguish "highlighted with comment" vs "regular highlighting". No desire to overcomplicate things though :smile: 
Perhaps the combo can work. What is most important I think is not obscuring the fact there's a comment with the highlighting (which currently happens). 

Ah! Interesting... this icon and placement we chose to inherit from GitHub - it simply provides a quick visual cue as to the state of status checks (e.g., failing build etc.). Will look into why it doesn't link to the Services tab. 
Do you use / notice this icon on GitHub? Just curious.

Will discuss all with @dfarr who's back from vacation next week :smile:

**Comment by golubev** [comment]
> Do you use / notice this icon on GitHub? Just curious.

@rwreynard, it seems to me that I have never noticed anything similar to it on GitHub :smiley:

**Comment by golubev** [comment]
Thanks for your comments, @rwreynard. Completely agree with them :smiley:

**Comment by rwreynard** [comment]
![screen shot 2015-11-19 at 4 11 33 pm](https://cloud.githubusercontent.com/assets/4131576/11288371/3ee6370a-8ed8-11e5-8081-e2c5508a523b.png)

Font Awesome icon: fa-stop, 16px, #ffffff, border: 4px #df843e
+
Font Awesome icon: fa-exclamation, 12px, #df843e, border: 2px #ffffff

**Comment by rwreynard** [comment]
![screen shot 2015-11-19 at 4 15 30 pm](https://cloud.githubusercontent.com/assets/4131576/11288433/cc1b1d98-8ed8-11e5-929b-3c1457f1ab56.png)

Font Awesome icon: fa-stop, 16px, #ffffff, border: 4px, #3e9a94
+
Font Awesome icon: fa-exclamation, 12px, #3e9a94, border: 2px #ffffff
+
Font Awesome icon: fa-check, 10px, #3e9a94, border: 2px #ffffff

@dfarr if stacking 3 and offsetting the check a little doesn't work I'll find a 2 stack combo

**Comment by rwreynard** [comment]
![screen shot 2015-11-19 at 4 28 00 pm](https://cloud.githubusercontent.com/assets/4131576/11288617/8ee06fc6-8eda-11e5-8dd0-ad56c23e1033.png)

If possible, make orange highlight color over line numbers a little darker to stand out more.
#df843e 80% opacity.

Also, if we do this, can the number itself get correspondingly darker? Otherwise the line number itself will disappear against the darker orange highlight. Let's try #666666.

**Comment by rwreynard** [comment]
As discussed, yellow highlighting no longer obscures orange line number highlighting. E.g.:

![screen shot 2015-11-19 at 4 34 32 pm](https://cloud.githubusercontent.com/assets/4131576/11288738/7d03cab8-8edb-11e5-808d-3106c29ade67.png)

**Comment by rwreynard** [comment]
Update to PR list view

![screen shot 2015-11-19 at 4 43 12 pm](https://cloud.githubusercontent.com/assets/4131576/11288914/a7baa776-8edc-11e5-9c0f-865654551f61.png)

**Comment by rwreynard** [comment]
@golubev thanks for all your suggestions and feedback on this! We tried a few variations of icons, and ultimately opted for very simple (just exclamations & checks) - gets a lot less crowded on the diff view.

Let us know what you think about all these changes, and if they address the points you were seeing.

Also, let us know any other suggestions you have!

**Comment by golubev** [comment]
Thanks @dfarr and @rwreynard! It was very pleasant for me to be helpful and to see that my issues had been taken into account and resolved!

Very nice job! :+1: 

I am quite occupied at my job at [lun.ua](http://www.lun.ua/) now, but I think that I will try again ReviewNinja for a code review if there will be a suitable branch in our repository for a PR :smiley: If I will have issues I will address them to you! :smiley: 

Greetings from Kyiv, Ukraine! :wave:

**Comment by rwreynard** [comment]
Thanks @golubev! Pleasure working with you also :+1:
