### ISSUE TITLE
Submit comment with Ctrl + Enter

### ISSUE THREAD

**Issue by golubev** [reviewninja/review.ninja#969]
IMHO, it would be nice to be able to submit a comment with Ctrl + Enter, like it is done on GitHub.

**Comment by dfarr** [comment]
:+1:

**Comment by dfarr** [comment]
Implemented!

**Comment by golubev** [comment]
Thanks, @dfarr!

Looks like it has not been released yet on `app.review.ninja`. Autocomplete works there, but Ctrl + Enter does not work for me.

**Comment by dfarr** [comment]
`ctrl+enter` was working, extended support for `cmd+enter`, please try again!

**Comment by golubev** [comment]
@dfarr, just tested once more.

> Ubuntu 12.04, Chrome 45.0.2454.93 (64-bit)

`Ctrl + Enter` does not work. Neither with the left `Ctrl` nor with the right one.

`Windows + Enter` works :smiley:

**Comment by golubev** [comment]
I was testing at the `app.review.ninja`.

**Comment by golubev** [comment]
@dfarr, tested again on `app.review.ninja` - did not work for me :disappointed:

**Comment by golubev** [comment]
* `Ctrl + Enter` did not work
