### ISSUE TITLE
Support protected branches

### ISSUE THREAD

**Issue by dfarr** [reviewninja/review.ninja#970]
https://developer.github.com/changes/2015-09-03-ensure-your-app-is-ready-for-protected-branches/

We will need to:
- [x] disable "delete branch" for protected branches
- [x] show special _required_ status checks
- [x] disable merge button until required status checks have passed

**Comment by dfarr** [comment]
Cannot implement until necessary data is included in the GitHub API

**Comment by benboeser** [comment]
it's here(almost): https://developer.github.com/changes/2015-11-11-protected-branches-api/
