### ISSUE TITLE
ReviewNinja survey invite/pop-up

### ISSUE THREAD

**Issue by dfarr** [reviewninja/review.ninja#973]

**Comment by rwreynard** [comment]
Links to surveys:

External version: https://surveys.sap.com/SE/?SID=SV_9NZR08gVgWWT8NL
Internal version: https://surveys.sap.com/SE/?SID=SV_ePRj9fQt1FrVOsZ

**Comment by rwreynard** [comment]
Copy for invite: 

We could sure use your help! Would you be willing to give us some quick (5-10 mins) feedback? Sure! (links to survey) No, thanks (dismiss forever). Thank you for helping us improve ReviewNinja!

**Comment by dfarr** [comment]
Implemented!

**Comment by rwreynard** [comment]
:+1:
