### ISSUE TITLE
Surface old commits in git graph

### ISSUE THREAD

**Issue by dfarr** [reviewninja/review.ninja#974]
It would be nice if we could surface old commits in the git graph. On top of this we could surface additional information and functionality such as:
- ninja star on specific commits
- the ability to compare old commits to other old commit and latest commit

**Comment by hollasch** [comment]
I'll second the ability for more fine-grained review in lines of development. I typically use a chain of commits to address specific tasks in a feature, and this is often strategic in understanding a large complicated pull request.
