### ISSUE TITLE
Review sometimes has an "invisible" open issue

### ISSUE THREAD

**Issue by disordered** [reviewninja/review.ninja#983]
I am not sure what triggers it and I have not found a way to remove it. Some pull requests just get one persistent open issue that does not show up in issues list. Services tab will say that Review Ninja service is failing due to one open issue, even though all have been fixed. It also happens on PRs with or without general conversations (without !fix tags).

It started after upgrade to use github comments.

**Comment by dfarr** [comment]
Interesting... If you update the status of the PR does it still report an issue? For example by starring the PR and then unstarring?

**Comment by dfarr** [comment]
I will keep investigating, so far cannot replicate.

**Comment by disordered** [comment]
Yes it remains. We tried adding extra !fix, !fixed, !resolved, etc. tried creating new issues and resolving, adding !fixed on conversations (the comments without !fix tag), also tried pushing new code to the branch. Nothing helps.

We don't have a pull request right now with this issue, but once we do, I can delay the merge for a day or two and ping you, so you can investigate.

**Comment by dfarr** [comment]
Okay, I have two theories as to what may be happening here.

1) You have more than 100 review comments

GitHub's API is paginated, right now I grab 100 review comments to calculate a PR status, if there are >100 the calculation could be off. You can [see the code here](https://github.com/reviewninja/review.ninja/blob/master/src/server/services/pullRequest.js#L26). This is a known limitation, I planned to dealing with this whenever it became a problem.

2) Subsequent review comments (after a new commit) are not being grouped properly.

We group comments by commit/file/line position, it's possible comments on later commits are not being grouped properly causing "orphaned" threads to always report a failing status. [here is the code](https://github.com/reviewninja/review.ninja/blob/master/src/server/services/flags.js#L20-L22), I think this is the more likely scenario.

**Comment by disordered** [comment]
I sent you an email with some closed PRs that have the problem, maybe this can help you.

**Comment by dfarr** [comment]
I believe I have found the problem, please see the commit message in 1a86d56 for a detailed explanation.

**Comment by disordered** [comment]
Thanks, David. I will let you know in case it reappears.
