### ISSUE TITLE
Assignee filter from Pull Request list

### ISSUE THREAD

**Issue by Masadow** [reviewninja/review.ninja#985]
Thanks for adding the possibility to assign someone from the platform.

To add the most value out of it, it would be great to be able to filter pull request list by assignee or at least view `assigned to me` pull requests.

Thanks !

**Comment by casche** [comment]
Hey @Masadow, 

This functionality is covered via the search field. You can filter for the assignee via the assignee's name:

![screen shot 2015-10-16 at 2 49 00 pm](https://cloud.githubusercontent.com/assets/5832943/10549057/0f344822-7415-11e5-9408-90ce92605bbd.png)

**Comment by dfarr** [comment]
I will close for now as not high priority and their is a nice way to replicate this functionality as suggested by @casche
