### ISSUE TITLE
Please add support for gitter

### ISSUE THREAD

**Issue by warden** [reviewninja/review.ninja#998]
It would be great to have Gitter support alongside the Slack support. Great project!

**Comment by dfarr** [comment]
Going to hijack this request to add it may be nice to create a common "integrations" strategy to make it easier to create any integration. Eg) campfire, gitter, etc.

**Comment by warden** [comment]
:+1:

**Comment by dfarr** [comment]
As ReviewNinja is no longer in active development mode (see #1132), I will close this issue.
